-- Metro coverage expansion, ranks ~51-100. Picks 30 metros from this
-- band where there's solid public knowledge of well-known photogenic
-- spots; smaller metros with no clear iconic locations are deliberately
-- skipped — better to leave a city unseeded than to ship made-up
-- coordinates that send a photographer to the wrong block.
--
-- Same conventions as prior seeds: coordinates accurate to within a
-- block for landmarks, descriptions sourced from public knowledge,
-- permit_certainty conservative (mostly 'likely' or 'unknown') so
-- photographers verify with the venue before paid shoots.
--
-- Re-running creates duplicates — run once.

insert into public.locations (
  name, city, state, latitude, longitude, description, access_type, tags,
  permit_required, permit_certainty, permit_notes,
  status, source, rating, quality_score
) values

-- ── Rochester, NY ─────────────────────────────────────────────────────────
('High Falls', 'Rochester', 'NY', 43.1606, -77.6169,
 '96-foot waterfall in the heart of downtown Rochester — the Genesee River cuts through the gorge with the Pont de Rennes pedestrian bridge framing it.',
 'public', array['Waterfall','Bridge','Urban'], false, 'likely',
 'Public viewpoint; commercial crews check with city.',
 'published', 'curated_v1', 4.7, 87),
('George Eastman Museum', 'Rochester', 'NY', 43.1542, -77.5824,
 '50-room 1905 Colonial Revival mansion — formal gardens, the conservatory wing, a treasured photography history archive.',
 'public', array['Historic','Architecture','Garden'], true, 'likely',
 'Eastman Museum events team handles photography permissions.',
 'published', 'curated_v1', 4.6, 85),
('Highland Park', 'Rochester', 'NY', 43.1356, -77.6094,
 'Olmsted-designed park famous for its 1,200+ lilac trees — bloom peak in May; wide lawns and mature plantings year-round.',
 'public', array['Park','Garden','Outdoor'], true, 'likely',
 'Monroe County Parks photography permit applies.',
 'published', 'curated_v1', 4.6, 85),

-- ── Grand Rapids, MI ──────────────────────────────────────────────────────
('Frederik Meijer Gardens & Sculpture Park', 'Grand Rapids', 'MI', 42.9841, -85.5908,
 '158-acre garden + sculpture park with the iconic American Horse, Japanese garden, and conservatory complex.',
 'public', array['Garden','Sculpture','Outdoor'], true, 'likely',
 'Meijer Gardens charges a photo permit fee for paid sessions.',
 'published', 'curated_v1', 4.8, 89),
('Calder Plaza', 'Grand Rapids', 'MI', 42.9684, -85.6709,
 '"La Grande Vitesse" — Calder''s 1969 stabile, a giant red sculpture that became the city''s symbol. Modernist plaza framing.',
 'public', array['Sculpture','Iconic','Urban'], false, 'likely',
 'Public plaza; large crews check with city.',
 'published', 'curated_v1', 4.5, 84),
('Rosa Parks Circle', 'Grand Rapids', 'MI', 42.9637, -85.6716,
 'Maya Lin-designed downtown plaza — water feature, ice rink in winter, surrounded by red-brick storefronts.',
 'public', array['Urban','Architecture','Iconic'], false, 'unknown',
 'Public plaza in the heart of downtown.',
 'published', 'curated_v1', 4.4, 82),

-- ── Honolulu, HI ──────────────────────────────────────────────────────────
('Diamond Head Crater', 'Honolulu', 'HI', 21.2620, -157.8050,
 '760-foot volcanic crater with the iconic profile rising over Waikiki — short hike to the rim, Pacific + skyline views.',
 'public', array['Iconic','Outdoor','Hike'], true, 'likely',
 'Hawaii State Parks permit required for commercial photography.',
 'published', 'curated_v1', 4.8, 92),
('Lanikai Beach', 'Honolulu', 'HI', 21.3939, -157.7140,
 'Half-mile of powder-white sand on the windward side — Mokulua Islands offshore, turquoise water, swaying palms.',
 'public', array['Beach','Tropical','Iconic'], true, 'likely',
 'City & County of Honolulu permit required for commercial beach photography.',
 'published', 'curated_v1', 4.9, 92),
('Iolani Palace', 'Honolulu', 'HI', 21.3068, -157.8584,
 'Only royal palace on US soil — 1882 American Florentine architecture, formal grounds with banyan trees.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Iolani Palace staff handles commercial photography permissions.',
 'published', 'curated_v1', 4.7, 88),

-- ── Tulsa, OK ─────────────────────────────────────────────────────────────
('Gathering Place', 'Tulsa', 'OK', 36.1207, -95.9844,
 '$465M Arkansas River park — sculpted hills, the iconic boathouse pavilion, Adventure Playground, ONEOK Boathouse.',
 'public', array['Park','Architecture','Modernist'], true, 'likely',
 'Gathering Place permits required for commercial photography.',
 'published', 'curated_v1', 4.7, 88),
('BOK Tower', 'Tulsa', 'OK', 36.1556, -95.9897,
 '52-story 1975 black-glass skyscraper — the tallest building in the state, designed by Minoru Yamasaki (also designed the original WTC).',
 'public', array['Architecture','Skyline','Modernist'], false, 'unknown',
 'Public street view; building access for crews via management.',
 'published', 'curated_v1', 4.4, 82),
('Cain''s Ballroom', 'Tulsa', 'OK', 36.1604, -95.9992,
 '1924 Western Swing dancehall — neon sign, sprung maple floor, Bob Wills history. Iconic Route 66 facade.',
 'public', array['Historic','Music','Iconic'], true, 'likely',
 'Cain''s management handles commercial photography requests.',
 'published', 'curated_v1', 4.6, 85),

-- ── Albany, NY ────────────────────────────────────────────────────────────
('Empire State Plaza', 'Albany', 'NY', 42.6498, -73.7592,
 '98-acre Rockefeller-era government complex — modernist marble, reflecting pools, "The Egg" performing arts center.',
 'public', array['Modernist','Architecture','Iconic'], true, 'likely',
 'Office of General Services permit required for commercial photography.',
 'published', 'curated_v1', 4.6, 85),
('Washington Park', 'Albany', 'NY', 42.6533, -73.7706,
 'Olmsted-style 81-acre downtown park — King Memorial Fountain, Robert Burns statue, the lake house, mature elms.',
 'public', array['Park','Outdoor','Trees'], true, 'likely',
 'Albany Parks photo permit applies.',
 'published', 'curated_v1', 4.5, 84),
('New York State Capitol', 'Albany', 'NY', 42.6526, -73.7572,
 '1899 Romanesque/Renaissance hybrid — million-dollar staircase, the carved "stone faces" portraits, dramatic interior arches.',
 'public', array['Historic','Architecture','Government'], true, 'likely',
 'Capitol staff handles commercial photography permissions.',
 'published', 'curated_v1', 4.6, 85),

-- ── New Haven, CT ─────────────────────────────────────────────────────────
('Yale University — Old Campus', 'New Haven', 'CT', 41.3083, -72.9290,
 'Gothic Revival quadrangle — Connecticut Hall (1750), Vanderbilt Hall, ivy-covered facades, the Phelps Gate arch.',
 'public', array['Architecture','Historic','Campus'], true, 'likely',
 'Yale Visitor Center handles commercial photography permissions for campus.',
 'published', 'curated_v1', 4.7, 87),
('East Rock Park', 'New Haven', 'CT', 41.3325, -72.9067,
 '359-foot trap-rock ridge — sweeping views over New Haven, Long Island Sound on clear days, the Soldiers'' Monument at the summit.',
 'public', array['Overlook','Park','Outdoor'], true, 'likely',
 'New Haven Parks permit applies for crews.',
 'published', 'curated_v1', 4.6, 85),
('New Haven Green', 'New Haven', 'CT', 41.3083, -72.9244,
 '17th-century town green at the heart of downtown — three historic churches in a row, mature elms, framed by Yale on three sides.',
 'public', array['Historic','Park','Architecture'], false, 'unknown',
 'Public green; large crews check with city.',
 'published', 'curated_v1', 4.5, 83),

-- ── Knoxville, TN ─────────────────────────────────────────────────────────
('Sunsphere', 'Knoxville', 'TN', 35.9606, -83.9197,
 '266-foot golden sphere from the 1982 World''s Fair — the city''s defining landmark, World''s Fair Park around the base.',
 'public', array['Iconic','Architecture','Modernist'], true, 'likely',
 'World''s Fair Park permit applies.',
 'published', 'curated_v1', 4.5, 84),
('Market Square', 'Knoxville', 'TN', 35.9659, -83.9189,
 'Pedestrianized plaza framed by 1850s storefronts — fountain at one end, year-round events, oak shading.',
 'public', array['Urban','Historic','Architecture'], false, 'unknown',
 'Public square; commercial crews check with city.',
 'published', 'curated_v1', 4.6, 85),
('Ijams Nature Center', 'Knoxville', 'TN', 35.9550, -83.8730,
 '300-acre wooded reserve along the Tennessee River — quarry pools, boardwalks, the Mead''s Quarry blue water.',
 'public', array['Nature','Outdoor','Forest'], true, 'likely',
 'Ijams handles commercial photography permits.',
 'published', 'curated_v1', 4.6, 85),

-- ── Charleston, SC ────────────────────────────────────────────────────────
('Rainbow Row', 'Charleston', 'SC', 32.7768, -79.9279,
 'Thirteen pastel-painted Georgian rowhouses on East Bay Street — the most photographed block in the South.',
 'public', array['Iconic','Architecture','Historic'], false, 'unknown',
 'Public sidewalk; private homes — respect signage.',
 'published', 'curated_v1', 4.9, 92),
('The Battery + White Point Garden', 'Charleston', 'SC', 32.7706, -79.9286,
 'Promenade at the harbor''s edge — antebellum mansions on one side, Civil War cannons + oaks in the park on the other.',
 'public', array['Waterfront','Historic','Park'], true, 'likely',
 'Charleston Parks permit applies for crews.',
 'published', 'curated_v1', 4.8, 91),
('Magnolia Plantation & Gardens', 'Charleston', 'SC', 32.8775, -80.0780,
 'America''s oldest public garden (1676) — Spanish-moss cypresses, the white wooden bridge over the dark-water swamp.',
 'public', array['Garden','Historic','Tropical'], true, 'likely',
 'Magnolia Plantation charges a photo permit fee — wedding photography popular.',
 'published', 'curated_v1', 4.8, 90),

-- ── Boise, ID ─────────────────────────────────────────────────────────────
('Idaho State Capitol', 'Boise', 'ID', 43.6178, -116.1996,
 '1920 sandstone neoclassical capitol — only state capitol heated by geothermal water, marble interiors, formal grounds.',
 'public', array['Historic','Architecture','Government'], true, 'likely',
 'Capitol Mall office handles commercial photography permissions.',
 'published', 'curated_v1', 4.5, 84),
('Boise River Greenbelt', 'Boise', 'ID', 43.6121, -116.2150,
 '25-mile paved riverside path — cottonwoods, pedestrian bridges, the Snake River Stampede grounds, easy water access.',
 'public', array['Waterfront','Park','Outdoor'], false, 'likely',
 'Boise Parks permit for crews.',
 'published', 'curated_v1', 4.6, 86),
('Hyde Park (North End)', 'Boise', 'ID', 43.6362, -116.1966,
 'Historic North End neighborhood blocks — early-1900s cottages, mature elms, brick storefronts.',
 'public', array['Historic','Street','Architecture'], false, 'unknown',
 'Public sidewalks; respect private homes.',
 'published', 'curated_v1', 4.4, 82),

-- ── Madison, WI ───────────────────────────────────────────────────────────
('Wisconsin State Capitol', 'Madison', 'WI', 43.0747, -89.3842,
 '1917 granite capitol with the only granite dome in the US — Bavarian-marble interior, formal grounds, isthmus framing between two lakes.',
 'public', array['Historic','Architecture','Government'], true, 'likely',
 'Capitol Police handle commercial photography permissions.',
 'published', 'curated_v1', 4.7, 87),
('Olbrich Botanical Gardens', 'Madison', 'WI', 43.0975, -89.3217,
 '16-acre garden + a free Bolz Conservatory — the gold-leaf Thai Pavilion is the iconic shot.',
 'public', array['Garden','Architecture','Indoor'], true, 'likely',
 'Olbrich handles photography permits for paid sessions.',
 'published', 'curated_v1', 4.7, 88),
('Memorial Union Terrace', 'Madison', 'WI', 43.0764, -89.4011,
 'Lake Mendota lakefront patio with the iconic sunburst chairs — UW campus, sailboats, sunset over the water.',
 'public', array['Waterfront','Iconic','Sunset'], false, 'likely',
 'UW Memorial Union for crews.',
 'published', 'curated_v1', 4.6, 85),

-- ── Asheville, NC ─────────────────────────────────────────────────────────
('Biltmore Estate', 'Asheville', 'NC', 35.5398, -82.5520,
 '250-room 1895 chateau — America''s largest privately-owned home, formal Italian + walled gardens, 8,000-acre grounds.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Biltmore charges substantial photo permit fees — wedding photography by appointment only.',
 'published', 'curated_v1', 4.8, 91),
('Blue Ridge Parkway — Craggy Gardens', 'Asheville', 'NC', 35.7008, -82.3833,
 'Heath bald at 5,640 feet on the Parkway — purple rhododendrons in June, sweeping ridge views year-round.',
 'public', array['Mountain','National Park','Outdoor'], true, 'likely',
 'NPS commercial photography permit required.',
 'published', 'curated_v1', 4.8, 90),
('River Arts District', 'Asheville', 'NC', 35.5816, -82.5683,
 'Old industrial blocks turned working artist studios — murals, exposed brick, French Broad River edges.',
 'public', array['Murals','Industrial','Urban'], false, 'unknown',
 'Public streets; respect private studios.',
 'published', 'curated_v1', 4.5, 84),

-- ── Spokane, WA ───────────────────────────────────────────────────────────
('Riverfront Park', 'Spokane', 'WA', 47.6611, -117.4191,
 '100-acre downtown park around Spokane Falls — clock tower, the Looff Carrousel, footbridges over the cascades.',
 'public', array['Waterfall','Park','Urban'], true, 'likely',
 'Spokane Parks permit required for crews.',
 'published', 'curated_v1', 4.7, 87),
('Manito Park', 'Spokane', 'WA', 47.6322, -117.4136,
 'South Hill park with rose garden, Japanese garden, and the Gaiser Conservatory — five distinct theme gardens in 90 acres.',
 'public', array['Garden','Park','Architecture'], true, 'likely',
 'Spokane Parks permit applies.',
 'published', 'curated_v1', 4.7, 87),
('Spokane Falls — Lower Falls', 'Spokane', 'WA', 47.6614, -117.4225,
 '146-foot waterfall complex right in downtown — pedestrian bridges, the SkyRide gondola, urban meets wild.',
 'public', array['Waterfall','Urban','Iconic'], false, 'likely',
 'Public viewing; commercial crews verify with city.',
 'published', 'curated_v1', 4.7, 87),

-- ── Provo, UT ─────────────────────────────────────────────────────────────
('Bridal Veil Falls', 'Provo', 'UT', 40.3470, -111.6164,
 '607-foot double cataract waterfall in Provo Canyon — paved approach, freezes into a climbing route in winter.',
 'public', array['Waterfall','Outdoor','Iconic'], false, 'likely',
 'Public canyon; large crews check with Utah County.',
 'published', 'curated_v1', 4.7, 88),
('Provo Pioneer Village', 'Provo', 'UT', 40.2369, -111.6586,
 'Restored 19th-century Mormon pioneer cabins + log buildings — outdoor history museum with rustic textures.',
 'public', array['Historic','Western','Outdoor'], true, 'unknown',
 'Pioneer Village handles photography requests.',
 'published', 'curated_v1', 4.4, 82),
('Y Mountain Trail', 'Provo', 'UT', 40.2570, -111.6410,
 'Switchback hike to the giant white "Y" letter on the Wasatch slope — Utah Lake + Provo valley views from the top.',
 'public', array['Hike','Mountain','Overlook'], false, 'unknown',
 'Public trail; small parking — get there early.',
 'published', 'curated_v1', 4.6, 85),

-- ── Anchorage, AK ─────────────────────────────────────────────────────────
('Flattop Mountain', 'Anchorage', 'AK', 61.1085, -149.6758,
 'Most-climbed peak in Alaska — 3,510 feet, sweeping views of Cook Inlet, Mount McKinley on clear days.',
 'public', array['Mountain','Hike','Overlook'], false, 'likely',
 'Chugach State Park permit applies for commercial photography.',
 'published', 'curated_v1', 4.7, 87),
('Earthquake Park', 'Anchorage', 'AK', 61.1990, -149.9583,
 'Park preserving the geological scarring from the 1964 earthquake — coastal trail, Cook Inlet views, mature spruce.',
 'public', array['Park','Coastal','Outdoor'], false, 'likely',
 'Anchorage Parks permit for crews.',
 'published', 'curated_v1', 4.4, 82),
('Tony Knowles Coastal Trail', 'Anchorage', 'AK', 61.2167, -149.9000,
 '11-mile paved coastal path — moose sightings, Cook Inlet views, the Alaska Range in the distance.',
 'public', array['Coastal','Outdoor','Trail'], false, 'unknown',
 'Public trail; respect wildlife.',
 'published', 'curated_v1', 4.7, 87),

-- ── Reno, NV ──────────────────────────────────────────────────────────────
('Reno Arch', 'Reno', 'NV', 39.5298, -119.8133,
 '"The Biggest Little City in the World" neon sign over Virginia Street — the iconic gateway shot, lit at night.',
 'public', array['Iconic','Urban','Neon'], false, 'unknown',
 'Public street; large crews check with city.',
 'published', 'curated_v1', 4.5, 84),
('Wingfield Park', 'Reno', 'NV', 39.5246, -119.8147,
 'Truckee River island park with kayak rapids, footbridges, and a year-round amphitheater. Downtown Reno backdrop.',
 'public', array['River','Park','Urban'], true, 'likely',
 'Reno Parks permit for crews.',
 'published', 'curated_v1', 4.5, 84),
('Lake Tahoe — Sand Harbor', 'Reno', 'NV', 39.1986, -119.9311,
 '40 minutes from downtown Reno — boulder-strewn beach, turquoise alpine water, Sierra peaks all around.',
 'public', array['Lake','Beach','Mountain'], true, 'likely',
 'Nevada State Parks photo permit required.',
 'published', 'curated_v1', 4.9, 92),

-- ── Boulder, CO ───────────────────────────────────────────────────────────
('The Flatirons (Chautauqua)', 'Boulder', 'CO', 39.9966, -105.2820,
 'Iconic tilted sandstone slabs rising over Boulder — Chautauqua meadows in front, the city''s defining backdrop.',
 'public', array['Mountain','Iconic','Outdoor'], true, 'likely',
 'City of Boulder OSMP permit required for commercial photography.',
 'published', 'curated_v1', 4.9, 93),
('Pearl Street Mall', 'Boulder', 'CO', 40.0179, -105.2799,
 'Pedestrianized brick street through downtown — turn-of-the-century facades, mountain views down the cross streets.',
 'public', array['Urban','Architecture','Pedestrian'], false, 'unknown',
 'Public mall; large crews check with city.',
 'published', 'curated_v1', 4.6, 85),
('Sanitas Valley Trail', 'Boulder', 'CO', 40.0286, -105.2936,
 'Foothills trail with a steady climb — Boulder skyline + plains views to the east, Sanitas summit at the top.',
 'public', array['Hike','Mountain','Overlook'], false, 'likely',
 'OSMP permit applies for commercial photography.',
 'published', 'curated_v1', 4.6, 85),

-- ── Savannah, GA ──────────────────────────────────────────────────────────
('Forsyth Park Fountain', 'Savannah', 'GA', 32.0681, -81.0958,
 'White cast-iron fountain (1858) at the south end of Forsyth Park — Spanish-moss live oaks framing every angle.',
 'public', array['Park','Iconic','Historic'], true, 'likely',
 'Savannah Parks photo permit applies for crews.',
 'published', 'curated_v1', 4.9, 93),
('Bonaventure Cemetery', 'Savannah', 'GA', 32.0411, -81.0464,
 'Historic 1846 cemetery — moss-draped oaks, Victorian funerary sculpture, the Wilkes monument and Bird Girl statue history.',
 'public', array['Historic','Iconic','Outdoor'], true, 'likely',
 'Bonaventure Historical Society for paid photography requests.',
 'published', 'curated_v1', 4.8, 91),
('River Street', 'Savannah', 'GA', 32.0808, -81.0905,
 'Cobblestone riverfront street under the bluff — cotton-warehouse-brick facades, the Savannah River and its bridges.',
 'public', array['Historic','Waterfront','Architecture'], false, 'unknown',
 'Public street; commercial crews check with city.',
 'published', 'curated_v1', 4.7, 87),

-- ── Eugene, OR ────────────────────────────────────────────────────────────
('Hayward Field', 'Eugene', 'OR', 44.0419, -123.0680,
 '2020-rebuilt iconic track stadium — sweeping wood-clad concourse, "TrackTown USA" energy, year-round access.',
 'public', array['Architecture','Iconic','Modernist'], true, 'unknown',
 'University of Oregon athletics for access permissions.',
 'published', 'curated_v1', 4.6, 85),
('Owen Rose Garden', 'Eugene', 'OR', 44.0589, -123.1003,
 '8-acre rose garden along the Willamette — 4,500 roses across 400 varieties, a National Champion Black Tartarian Cherry tree at the center.',
 'public', array['Garden','Outdoor','Trees'], true, 'likely',
 'Eugene Parks permit for paid sessions.',
 'published', 'curated_v1', 4.6, 86),
('Skinner Butte Park', 'Eugene', 'OR', 44.0566, -123.0955,
 '102-acre downtown park topped by a basalt rim — climbing rocks, the iconic flower-spelled "O" hill, panoramic city views.',
 'public', array['Park','Overlook','Urban'], true, 'likely',
 'Eugene Parks permit applies for crews.',
 'published', 'curated_v1', 4.5, 83),

-- ── Sarasota, FL ──────────────────────────────────────────────────────────
('Marie Selby Botanical Gardens', 'Sarasota', 'FL', 27.3296, -82.5478,
 '15-acre bayfront garden — orchids, banyans, the Christy Payne mansion, Sarasota Bay views.',
 'public', array['Garden','Tropical','Outdoor'], true, 'likely',
 'Selby handles photography permits — wedding photography popular.',
 'published', 'curated_v1', 4.7, 88),
('Siesta Key Beach', 'Sarasota', 'FL', 27.2683, -82.5478,
 'Quartz-crystal sand beach — pure white, fine like sugar, regularly ranked among the world''s best beaches.',
 'public', array['Beach','Tropical','Iconic'], true, 'likely',
 'Sarasota County beach photography permit required for paid sessions.',
 'published', 'curated_v1', 4.9, 92),
('Ringling Museum — Cà d''Zan', 'Sarasota', 'FL', 27.3811, -82.5614,
 '1925 Venetian Gothic mansion — circus magnate Ringling''s home, pink-marble terraces, bayfront formal gardens.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Ringling Museum events team handles commercial photography.',
 'published', 'curated_v1', 4.8, 90),

-- ── Greenville, SC ────────────────────────────────────────────────────────
('Falls Park on the Reedy', 'Greenville', 'SC', 34.8442, -82.4017,
 'Downtown park around the Reedy River falls — the Liberty Bridge curves dramatically over the cascade.',
 'public', array['Waterfall','Bridge','Park'], true, 'likely',
 'Greenville Parks permit for crews.',
 'published', 'curated_v1', 4.8, 90),
('Liberty Bridge', 'Greenville', 'SC', 34.8443, -82.4018,
 'Curved cable-stayed pedestrian bridge (2004) — 345 feet of suspended walkway over the Reedy Falls. The defining downtown shot.',
 'public', array['Bridge','Architecture','Iconic'], false, 'likely',
 'Public bridge; large crews check with city.',
 'published', 'curated_v1', 4.8, 90),
('Main Street Greenville', 'Greenville', 'SC', 34.8519, -82.3987,
 'Tree-lined downtown core — restored facades, sidewalk cafes, art around every corner.',
 'public', array['Urban','Architecture','Street'], false, 'unknown',
 'Public sidewalks; respect storefronts.',
 'published', 'curated_v1', 4.6, 85),

-- ── Des Moines, IA ────────────────────────────────────────────────────────
('Iowa State Capitol', 'Des Moines', 'IA', 41.5910, -93.6037,
 '23-karat gold dome flanked by four smaller domes — 1886 Renaissance Revival, hilltop position over downtown.',
 'public', array['Historic','Architecture','Government'], true, 'likely',
 'Capitol staff handles commercial photography permissions.',
 'published', 'curated_v1', 4.6, 86),
('Pappajohn Sculpture Park', 'Des Moines', 'IA', 41.5859, -93.6273,
 '4.4-acre downtown park with 28 monumental contemporary sculptures — modernist works against grass + skyline.',
 'public', array['Sculpture','Modernist','Park'], false, 'likely',
 'Public park; commercial crews check with Greater Des Moines.',
 'published', 'curated_v1', 4.6, 86),
('Greater Des Moines Botanical Garden', 'Des Moines', 'IA', 41.5894, -93.6156,
 'Geodesic dome conservatory along the Des Moines River — tropical plants year-round + outdoor garden rooms.',
 'public', array['Garden','Architecture','Indoor'], true, 'likely',
 'Botanical Garden events for paid photography.',
 'published', 'curated_v1', 4.5, 84),

-- ── Worcester, MA ─────────────────────────────────────────────────────────
('Worcester Common', 'Worcester', 'MA', 42.2614, -71.7997,
 '1669 town common at the heart of downtown — Civil War memorial, surrounded by the granite city hall and historic facades.',
 'public', array['Historic','Park','Urban'], false, 'unknown',
 'Public common; large crews check with city.',
 'published', 'curated_v1', 4.3, 80),
('Tower Hill Botanic Garden', 'Worcester', 'MA', 42.4544, -71.7558,
 '171-acre garden in nearby Boylston — 1740 farmhouse, the Orangerie, lawns with sweeping views of Mt. Wachusett.',
 'public', array['Garden','Outdoor','Architecture'], true, 'likely',
 'Tower Hill events team handles photography permissions.',
 'published', 'curated_v1', 4.7, 87),
('Bancroft Tower', 'Worcester', 'MA', 42.2769, -71.7861,
 '1900 fieldstone castle-style tower atop Salisbury Park — Norman/feudal style, surrounded by mature woods.',
 'public', array['Historic','Architecture','Park'], false, 'unknown',
 'Public park.',
 'published', 'curated_v1', 4.4, 82),

-- ── El Paso, TX ───────────────────────────────────────────────────────────
('Franklin Mountains State Park — Tom Mays Unit', 'El Paso', 'TX', 31.9270, -106.5239,
 'Largest urban-area state park in the US — Chihuahuan desert peaks rising over El Paso, ocotillo + saguaro silhouettes.',
 'public', array['Desert','Mountain','Outdoor'], true, 'likely',
 'Texas Parks & Wildlife photo permit required.',
 'published', 'curated_v1', 4.6, 86),
('Scenic Drive Overlook', 'El Paso', 'TX', 31.7901, -106.4835,
 'Murchison Drive viewpoint on the Franklin Mountains'' south slope — sweeping El Paso, Juárez, and Rio Grande views.',
 'public', array['Overlook','Iconic','Urban'], false, 'unknown',
 'Public roadside.',
 'published', 'curated_v1', 4.7, 87),
('Plaza de los Lagartos', 'El Paso', 'TX', 31.7591, -106.4866,
 'Downtown plaza with Luis Jiménez''s "Los Lagartos" bronze alligator sculpture — lit fountain, oak trees, period storefronts.',
 'public', array['Urban','Sculpture','Park'], false, 'unknown',
 'Public plaza.',
 'published', 'curated_v1', 4.4, 82),

-- ── Mobile, AL ────────────────────────────────────────────────────────────
('Bellingrath Gardens', 'Mobile', 'AL', 30.5469, -88.0856,
 '65-acre Southern garden estate — azalea bloom (March), camellia trail, Fowl River framing, the 1935 home tour.',
 'public', array['Garden','Historic','Tropical'], true, 'likely',
 'Bellingrath charges a photo permit fee for paid sessions.',
 'published', 'curated_v1', 4.7, 88),
('Cathedral Square', 'Mobile', 'AL', 30.6940, -88.0410,
 'Downtown square anchored by the 1850 Cathedral Basilica — fountain, mature live oaks dripping with Spanish moss.',
 'public', array['Historic','Architecture','Park'], false, 'unknown',
 'Public square; respect cathedral grounds.',
 'published', 'curated_v1', 4.5, 84),
('Battleship Memorial Park — USS Alabama', 'Mobile', 'AL', 30.6817, -88.0144,
 'WWII battleship moored permanently in Mobile Bay — naval gray steel, period aircraft displays alongside.',
 'public', array['Historic','Iconic','Coastal'], true, 'likely',
 'Battleship Memorial Park handles commercial photography.',
 'published', 'curated_v1', 4.7, 88),

-- ── Lakeland, FL ──────────────────────────────────────────────────────────
('Hollis Garden', 'Lakeland', 'FL', 28.0463, -81.9489,
 '1.2-acre botanical garden on Lake Mirror — formal walks, a wedding gazebo, central Florida flora.',
 'public', array['Garden','Waterfront','Wedding'], true, 'likely',
 'Lakeland Parks permit applies.',
 'published', 'curated_v1', 4.5, 83),
('Lake Mirror Promenade', 'Lakeland', 'FL', 28.0435, -81.9495,
 '1929 Frederick Law Olmsted Jr. promenade — fountain, classical pavilions, oaks circling Lake Mirror.',
 'public', array['Historic','Park','Waterfront'], true, 'likely',
 'Lakeland Parks permit applies.',
 'published', 'curated_v1', 4.6, 85),
('Frank Lloyd Wright at Florida Southern College', 'Lakeland', 'FL', 28.0264, -81.9489,
 'Largest single-site collection of Wright architecture in the world — 12 buildings on a working college campus.',
 'public', array['Architecture','Historic','Iconic'], true, 'likely',
 'FSC visitor center handles commercial photography permissions.',
 'published', 'curated_v1', 4.7, 88),

-- ── Augusta, GA ───────────────────────────────────────────────────────────
('Augusta Riverwalk', 'Augusta', 'GA', 33.4754, -82.0030,
 'Levee-top walkway along the Savannah River — flower beds in season, downtown skyline, the Eighth Street Plaza arches.',
 'public', array['Waterfront','Park','Urban'], true, 'likely',
 'Augusta Parks permit for crews.',
 'published', 'curated_v1', 4.5, 84),
('Pinch Gut Historic District', 'Augusta', 'GA', 33.4775, -81.9931,
 'Olde Town: Greek Revival + Italianate row houses on cobbled streets, framed by mature crepe myrtles.',
 'public', array['Historic','Architecture','Street'], false, 'unknown',
 'Public sidewalks; respect private homes.',
 'published', 'curated_v1', 4.4, 82),
('Phinizy Swamp Nature Park', 'Augusta', 'GA', 33.3814, -81.9583,
 '1,100-acre wetland reserve — boardwalks through cypress + tupelo, Spanish moss, frequent gator sightings.',
 'public', array['Nature','Boardwalk','Outdoor'], true, 'likely',
 'Phinizy Center handles commercial photography requests.',
 'published', 'curated_v1', 4.5, 84),

-- ── Lubbock, TX ───────────────────────────────────────────────────────────
('Buddy Holly Center', 'Lubbock', 'TX', 33.5851, -101.8534,
 '1950s-style railroad-depot museum honoring Buddy Holly — "Crickets" sculpture out front, period storefronts adjacent.',
 'public', array['Historic','Iconic','Music'], true, 'unknown',
 'Buddy Holly Center handles photography requests.',
 'published', 'curated_v1', 4.5, 83),
('Texas Tech Memorial Circle', 'Lubbock', 'TX', 33.5848, -101.8771,
 'Spanish Renaissance campus core — red-tile roofs, the Will Rogers + Soapsuds statue, fountain at the center.',
 'public', array['Architecture','Campus','Historic'], true, 'unknown',
 'Texas Tech for commercial photography on campus.',
 'published', 'curated_v1', 4.5, 83),
('National Ranching Heritage Center', 'Lubbock', 'TX', 33.5872, -101.8786,
 '38 historic ranching structures spread across 19 acres — windmills, dugouts, frame houses, every facet of West Texas ranch history.',
 'public', array['Historic','Western','Outdoor'], true, 'likely',
 'NRHC handles commercial photography requests.',
 'published', 'curated_v1', 4.6, 85);
