-- Seed batch 2: cities 29-50 of top US metros × 5 photoshoot locations each.
-- Same conventions as 20260426_seed_top_metros.sql:
--   - lat/lng accurate within a city block for landmarks, ballpark for districts
--   - permit_certainty conservative ('unknown' or 'likely' unless well-documented)
--   - status='published', source='curated_v1' for easy filtering / cleanup
-- Re-running creates duplicate rows. Run once.

insert into public.locations (
  name, city, state, latitude, longitude, description, access_type, tags,
  permit_required, permit_certainty, permit_notes,
  status, source, rating, quality_score
) values

-- ── San Antonio, TX ───────────────────────────────────────────────────────
('The Alamo Plaza', 'San Antonio', 'TX', 29.4259, -98.4861,
 'Iconic 1718 Spanish mission. Plaza in front and the chapel facade are the classic shots.',
 'public', array['Historic','Iconic','Architecture'], true, 'verified',
 'Texas General Land Office permit required for any organized commercial / wedding shoot. Personal handheld OK.',
 'published', 'curated_v1', 4.7, 89),
('San Antonio River Walk', 'San Antonio', 'TX', 29.4253, -98.4861,
 '15 miles of pedestrian walkways one story below street level, lined with cypress, bridges, and stone arches.',
 'public', array['Waterfront','Urban','Iconic'], false, 'likely',
 'City of San Antonio permit needed for crews. Walk-up shoots OK.',
 'published', 'curated_v1', 4.8, 92),
('Mission San José', 'San Antonio', 'TX', 29.3635, -98.4775,
 'Largest of the Spanish missions on the UNESCO trail — sandstone walls, rose window, granary ruins.',
 'public', array['Historic','Architecture','Mission'], true, 'verified',
 'NPS — San Antonio Missions National Historical Park. Commercial photography permit required.',
 'published', 'curated_v1', 4.7, 89),
('Hemisfair Park — Yanaguana Garden', 'San Antonio', 'TX', 29.4204, -98.4830,
 'Redeveloped 1968 World''s Fair grounds with the Tower of the Americas behind.',
 'public', array['Park','Urban','Skyline'], true, 'likely',
 'San Antonio Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.5, 85),
('Pearl District', 'San Antonio', 'TX', 29.4419, -98.4753,
 'Restored 1880s brewery turned mixed-use district — brick, ironwork, modern restaurant terraces.',
 'public', array['Historic','Urban','Architecture'], false, 'likely',
 'Pearl is privately managed; commercial shoots require Pearl management approval.',
 'published', 'curated_v1', 4.6, 87),

-- ── Fort Worth, TX ────────────────────────────────────────────────────────
('Fort Worth Stockyards — Exchange Avenue', 'Fort Worth', 'TX', 32.7884, -97.3470,
 'Historic cattle district with brick streets, livestock pens, neon signs, and twice-daily cattle drive.',
 'public', array['Historic','Urban','Iconic'], false, 'likely',
 'Stockyards Heritage Development requires permit for organized commercial photography.',
 'published', 'curated_v1', 4.7, 89),
('Fort Worth Water Gardens', 'Fort Worth', 'TX', 32.7468, -97.3293,
 'Brutalist concrete water sculpture park — terraced descending pools and a quiet meditation pool.',
 'public', array['Architecture','Brutalist','Water'], true, 'likely',
 'City of Fort Worth Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.6, 87),
('Fort Worth Botanic Garden — Japanese Garden', 'Fort Worth', 'TX', 32.7423, -97.3658,
 '7.5 acres with koi ponds, pagodas, moon-viewing pavilions, and seasonal cherry blossoms.',
 'private', array['Garden','Asian','Quiet'], true, 'verified',
 'Botanic Garden photography permit required: $100 portrait, $1000+ wedding.',
 'published', 'curated_v1', 4.7, 89),
('Sundance Square', 'Fort Worth', 'TX', 32.7536, -97.3296,
 '35-block downtown district with red-brick streets, public art, and the Chisholm Trail mural.',
 'public', array['Urban','Mural','Historic'], false, 'likely',
 'Sundance Square Management permit needed for plaza shoots.',
 'published', 'curated_v1', 4.5, 85),
('Trinity Park — Heritage Trees', 'Fort Worth', 'TX', 32.7395, -97.3667,
 '252-acre park along the Trinity River with mature oaks, walking paths, and downtown skyline behind.',
 'public', array['Park','Trees','Skyline'], true, 'likely',
 'Fort Worth Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.4, 83),

-- ── Columbus, OH ──────────────────────────────────────────────────────────
('Topiary Park — A Sunday Afternoon', 'Columbus', 'OH', 39.9633, -82.9925,
 'Sculpted-shrub recreation of Seurat''s "A Sunday Afternoon on the Island of La Grande Jatte". One of a kind.',
 'public', array['Park','Sculpture','Iconic'], false, 'likely',
 'Columbus Recreation & Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.6, 87),
('Franklin Park Conservatory', 'Columbus', 'OH', 39.9682, -82.9446,
 '88-acre Victorian glasshouse with biome rooms — desert, rainforest, palm — plus outdoor gardens.',
 'private', array['Garden','Indoor','Floral'], true, 'verified',
 'Conservatory photography permit required: $150 portrait, $750+ wedding.',
 'published', 'curated_v1', 4.7, 89),
('Short North Arts District', 'Columbus', 'OH', 39.9786, -83.0040,
 'High Street between downtown and OSU — concentrated murals, gallery storefronts, and the iconic neon arches.',
 'public', array['Urban','Mural','Neon'], false, 'unknown',
 'Public sidewalks. Some murals on private buildings.',
 'published', 'curated_v1', 4.5, 85),
('Scioto Mile Promenade', 'Columbus', 'OH', 39.9603, -83.0035,
 'Riverfront park with the downtown skyline directly across the Scioto River.',
 'public', array['Waterfront','Skyline','Park'], false, 'likely',
 'Columbus Parks permit needed for organized shoots.',
 'published', 'curated_v1', 4.5, 85),
('German Village — Schiller Park', 'Columbus', 'OH', 39.9456, -82.9944,
 '233-acre historic district of mid-1800s brick row houses, cobblestone streets, and a 23-acre park.',
 'public', array['Historic','Cobblestone','Architecture'], false, 'likely',
 'Public streets. Park shoots need a Columbus Parks permit.',
 'published', 'curated_v1', 4.6, 87),

-- ── El Paso, TX ───────────────────────────────────────────────────────────
('Franklin Mountains State Park — Ron Coleman Trailhead', 'El Paso', 'TX', 31.9159, -106.5097,
 '24,000-acre desert park with Chihuahuan flora and 360° views of El Paso/Juárez.',
 'public', array['Outdoor','Desert','Mountain'], true, 'verified',
 'Texas State Parks photo permit required for organized shoots.',
 'published', 'curated_v1', 4.7, 88),
('Scenic Drive Overlook', 'El Paso', 'TX', 31.7937, -106.4881,
 'Mountainside overlook with sweeping views of downtown El Paso and Ciudad Juárez.',
 'public', array['Hilltop','Skyline','Sunset'], false, 'unknown',
 'Public road pullout. No permit for personal shoots.',
 'published', 'curated_v1', 4.6, 86),
('Mission Trail — Ysleta del Sur Pueblo', 'El Paso', 'TX', 31.6976, -106.3104,
 '1682 mission and adobe buildings of the oldest continuously inhabited community in Texas.',
 'public', array['Historic','Mission','Cultural'], true, 'likely',
 'Tigua tribal council approval needed for organized shoots on pueblo grounds.',
 'published', 'curated_v1', 4.5, 85),
('Plaza Theatre — Downtown El Paso', 'El Paso', 'TX', 31.7572, -106.4862,
 '1930 Spanish Colonial Revival theater with star-painted ceiling and original neon marquee.',
 'private', array['Historic','Architecture','Neon'], true, 'verified',
 'Plaza Theatre management approval required for any non-snapshot photography.',
 'published', 'curated_v1', 4.6, 87),
('Hueco Tanks State Park', 'El Paso', 'TX', 31.9197, -106.0464,
 'Granite outcrops with prehistoric pictographs. Requires reservation; one of the more dramatic desert landscapes near El Paso.',
 'public', array['Outdoor','Desert','Dramatic'], true, 'verified',
 'Texas State Parks permit + reservation required. North Mountain has open access; rest requires a guide.',
 'published', 'curated_v1', 4.7, 89),

-- ── Oklahoma City, OK ─────────────────────────────────────────────────────
('Myriad Botanical Gardens — Crystal Bridge', 'Oklahoma City', 'OK', 35.4655, -97.5185,
 '17-acre downtown garden with a 224-foot cylindrical glass conservatory.',
 'public', array['Garden','Architecture','Indoor'], true, 'verified',
 'Myriad Gardens photography permit required: $50 portrait.',
 'published', 'curated_v1', 4.6, 87),
('OKC National Memorial — Field of Empty Chairs', 'Oklahoma City', 'OK', 35.4731, -97.5170,
 'Reflecting pool, gates of time, and 168 chairs. A solemn, powerful spot — handle accordingly.',
 'public', array['Memorial','Reflective','Historic'], true, 'verified',
 'Memorial requires permission for organized photography on the grounds.',
 'published', 'curated_v1', 4.8, 91),
('Bricktown Canal', 'Oklahoma City', 'OK', 35.4634, -97.5060,
 'Mile-long canal through the Bricktown entertainment district with brick warehouses on both sides.',
 'public', array['Waterfront','Urban','Historic'], false, 'likely',
 'Bricktown management approval needed for crews.',
 'published', 'curated_v1', 4.5, 85),
('Wheeler District — Wheeler Ferris Wheel', 'Oklahoma City', 'OK', 35.4574, -97.5165,
 '100-foot ferris wheel relocated from Santa Monica, fronted by an Airstream-trailer food court.',
 'public', array['Iconic','Urban','Colorful'], false, 'unknown',
 'Public riverfront park.',
 'published', 'curated_v1', 4.4, 83),
('Heritage Hills — Mesta Park', 'Oklahoma City', 'OK', 35.4825, -97.5259,
 'Tree-lined neighborhood of early-1900s mansions in Tudor, Colonial, and Craftsman styles.',
 'public', array['Historic','Architecture','Trees'], false, 'unknown',
 'Public sidewalks.',
 'published', 'curated_v1', 4.5, 85),

-- ── Louisville, KY ────────────────────────────────────────────────────────
('Big Four Bridge', 'Louisville', 'KY', 38.2603, -85.7458,
 'Pedestrian bridge over the Ohio River — connects Louisville to Jeffersonville, IN. Skyline views in both directions.',
 'public', array['Bridge','Waterfront','Skyline'], false, 'likely',
 'Louisville Metro Parks permit needed for crews.',
 'published', 'curated_v1', 4.7, 89),
('Cherokee Park — Scenic Loop', 'Louisville', 'KY', 38.2440, -85.6979,
 '409-acre Olmsted-designed park with 2.4-mile scenic loop, mature oaks, and stone bridges.',
 'public', array['Park','Trees','Olmsted'], true, 'likely',
 'Metro Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.6, 87),
('Old Louisville — St. James Court', 'Louisville', 'KY', 38.2335, -85.7634,
 'Largest preservation district of Victorian mansions in the US. Cobblestone court with the Filson Historical Society.',
 'public', array['Historic','Architecture','Cobblestone'], false, 'likely',
 'Public street. Be respectful of residences.',
 'published', 'curated_v1', 4.7, 89),
('Yew Dell Botanical Gardens', 'Crestwood', 'KY', 38.3498, -85.4639,
 '60-acre former private estate, now public gardens with rare conifers and stone outbuildings. 20 minutes east of Louisville.',
 'private', array['Garden','Estate','Quiet'], true, 'verified',
 'Yew Dell photography permit required: $100 portrait, $500+ wedding.',
 'published', 'curated_v1', 4.6, 87),
('Falls of the Ohio — Indiana side', 'Clarksville', 'IN', 38.2745, -85.7651,
 '390-million-year-old fossil beds exposed in low water. Across the Ohio from Louisville with a clear skyline view.',
 'public', array['Outdoor','Geology','Waterfront'], true, 'likely',
 'Indiana State Parks photo permit required.',
 'published', 'curated_v1', 4.5, 85),

-- ── Baltimore, MD ─────────────────────────────────────────────────────────
('Inner Harbor — Federal Hill Park', 'Baltimore', 'MD', 39.2790, -76.6094,
 'Hilltop park overlooking the harbor, the National Aquarium, and the downtown skyline.',
 'public', array['Skyline','Park','Hilltop'], false, 'likely',
 'Baltimore City Recreation and Parks permit needed for crews.',
 'published', 'curated_v1', 4.7, 89),
('Fells Point — Thames Street', 'Baltimore', 'MD', 39.2820, -76.5928,
 'Cobblestone streets along the harbor, brick rowhouses, and the iconic Broadway Pier.',
 'public', array['Cobblestone','Historic','Waterfront'], false, 'likely',
 'Public sidewalks. Crews need a permit.',
 'published', 'curated_v1', 4.6, 87),
('Mount Vernon — Washington Monument', 'Baltimore', 'MD', 39.2974, -76.6157,
 '1815 Doric column (the first major monument to George Washington), with surrounding tree-lined squares.',
 'public', array['Historic','Architecture','Iconic'], false, 'likely',
 'Public park. Mount Vernon Place Conservancy approval recommended for crews.',
 'published', 'curated_v1', 4.6, 87),
('Cylburn Arboretum', 'Baltimore', 'MD', 39.3590, -76.6573,
 '207-acre arboretum with formal gardens, woodland trails, and a stone Victorian mansion.',
 'public', array['Garden','Mansion','Trees'], true, 'verified',
 'Cylburn Association photo permit required: $75 portrait.',
 'published', 'curated_v1', 4.6, 87),
('Patapsco Valley State Park — Cascade Falls', 'Ellicott City', 'MD', 39.2602, -76.7884,
 '32-mile-long park along the Patapsco River with stone arch bridges, swinging bridges, and a small waterfall.',
 'public', array['Waterfall','Outdoor','Forest'], true, 'verified',
 'Maryland State Parks photo permit required.',
 'published', 'curated_v1', 4.5, 85),

-- ── Milwaukee, WI ─────────────────────────────────────────────────────────
('Milwaukee Art Museum — Quadracci Pavilion', 'Milwaukee', 'WI', 43.0405, -87.8970,
 'Calatrava''s white-winged building on Lake Michigan — wings open and close throughout the day.',
 'public', array['Architecture','Iconic','Waterfront'], true, 'verified',
 'MAM approval required for any commercial / wedding photography on the grounds.',
 'published', 'curated_v1', 4.9, 94),
('North Point Lighthouse — Lake Park', 'Milwaukee', 'WI', 43.0680, -87.8722,
 'Octagonal 1888 lighthouse in an Olmsted-designed lakefront park.',
 'public', array['Lighthouse','Park','Historic'], false, 'likely',
 'Milwaukee County Parks permit needed for organized shoots.',
 'published', 'curated_v1', 4.6, 87),
('Historic Third Ward', 'Milwaukee', 'WI', 43.0322, -87.9090,
 'Cream-city brick warehouses, cobblestone streets, and the public market — Milwaukee''s most photogenic district.',
 'public', array['Historic','Urban','Architecture'], false, 'likely',
 'Public streets. Crews need a city film permit.',
 'published', 'curated_v1', 4.6, 88),
('Boerner Botanical Gardens', 'Hales Corners', 'WI', 42.9445, -88.0334,
 '40 acres of formal gardens — peony, rose, herb — within Milwaukee County''s Whitnall Park.',
 'private', array['Garden','Park','Floral'], true, 'verified',
 'Boerner photography permit required: $50 portrait, $250+ wedding.',
 'published', 'curated_v1', 4.6, 87),
('Milwaukee Riverwalk — Bronze Fonz', 'Milwaukee', 'WI', 43.0394, -87.9106,
 'River-level walkway through downtown with bridges, public art, and the iconic bronze Fonzie statue.',
 'public', array['Waterfront','Urban','Iconic'], false, 'likely',
 'City permit needed for crews.',
 'published', 'curated_v1', 4.4, 83),

-- ── Albuquerque, NM ───────────────────────────────────────────────────────
('Petroglyph National Monument — Boca Negra Canyon', 'Albuquerque', 'NM', 35.1631, -106.7196,
 'Volcanic basalt boulders covered with 24,000+ Ancestral Puebloan and Spanish petroglyphs.',
 'public', array['Outdoor','Cultural','Historic'], true, 'verified',
 'NPS commercial photography permit required.',
 'published', 'curated_v1', 4.6, 87),
('Sandia Peak — Crest Trail', 'Albuquerque', 'NM', 35.2089, -106.4474,
 'Watermelon-pink granite ridge at 10,378 feet with views over Albuquerque and the Rio Grande Valley.',
 'public', array['Mountain','Sunset','Hilltop'], false, 'likely',
 'USFS Cibola National Forest permit required for commercial shoots.',
 'published', 'curated_v1', 4.8, 91),
('Old Town Albuquerque — San Felipe de Neri Church', 'Albuquerque', 'NM', 35.0975, -106.6700,
 '1793 adobe church on the Old Town plaza, surrounded by adobe shops and restaurants.',
 'public', array['Historic','Adobe','Cultural'], false, 'likely',
 'Public plaza. Church requires permission for interior shots.',
 'published', 'curated_v1', 4.6, 87),
('ABQ BioPark — Botanic Garden Sasebo Japanese Garden', 'Albuquerque', 'NM', 35.0962, -106.6802,
 '36-acre garden with themed Mediterranean, desert, Japanese, and rose sections.',
 'private', array['Garden','Floral','Asian'], true, 'verified',
 'ABQ BioPark photography permit required.',
 'published', 'curated_v1', 4.5, 85),
('Rio Grande Nature Center State Park — Bosque Trail', 'Albuquerque', 'NM', 35.1419, -106.6822,
 'Cottonwood bosque (riparian forest) along the Rio Grande — golden in autumn.',
 'public', array['Outdoor','Forest','Quiet'], true, 'verified',
 'NM State Parks photo permit required.',
 'published', 'curated_v1', 4.5, 85),

-- ── Tucson, AZ ────────────────────────────────────────────────────────────
('Saguaro National Park — Saguaro West', 'Tucson', 'AZ', 32.2503, -111.1969,
 '90,000+ saguaro cacti across rolling Sonoran desert, with red-orange sunset glow.',
 'public', array['Outdoor','Desert','Iconic'], true, 'verified',
 'NPS commercial photography permit required.',
 'published', 'curated_v1', 4.9, 94),
('Mission San Xavier del Bac', 'Tucson', 'AZ', 32.1063, -111.0090,
 '1797 white Spanish Colonial mission known as "the white dove of the desert".',
 'public', array['Historic','Mission','Architecture'], true, 'likely',
 'Mission tribal council permission needed for commercial shoots.',
 'published', 'curated_v1', 4.8, 92),
('Sabino Canyon — Tram Stop 9', 'Tucson', 'AZ', 32.3163, -110.8195,
 'Sonoran desert canyon with seasonal pools, stone bridges, and big saguaros against red rock walls.',
 'public', array['Outdoor','Desert','Canyon'], true, 'verified',
 'USFS Coronado National Forest permit required.',
 'published', 'curated_v1', 4.7, 89),
('Tucson Mountain Park — Gates Pass', 'Tucson', 'AZ', 32.2266, -111.1153,
 'Mountain pass overlook into the saguaro-covered valley. Famous sunset spot.',
 'public', array['Hilltop','Sunset','Desert'], false, 'likely',
 'Pima County Parks permit needed for organized shoots.',
 'published', 'curated_v1', 4.7, 89),
('Tohono Chul Park', 'Tucson', 'AZ', 32.3494, -110.9888,
 '49-acre desert botanical garden with adobe-style galleries and bird-rich gardens.',
 'private', array['Garden','Desert','Adobe'], true, 'verified',
 'Tohono Chul photo permit required: $75 portrait.',
 'published', 'curated_v1', 4.5, 85),

-- ── Fresno, CA ────────────────────────────────────────────────────────────
('Forestiere Underground Gardens', 'Fresno', 'CA', 36.8385, -119.8252,
 '10 acres of subterranean rooms, courtyards, and citrus trees hand-dug by Baldassare Forestiere over 40 years.',
 'private', array['Indoor','Architecture','Hidden'], true, 'verified',
 'Forestiere requires reservation + photography permission for non-tour shoots.',
 'published', 'curated_v1', 4.7, 89),
('Shinzen Friendship Garden — Woodward Park', 'Fresno', 'CA', 36.8694, -119.7665,
 'Authentic Japanese stroll garden with koi ponds, stone bridges, and seasonal cherry/maple displays.',
 'public', array['Garden','Asian','Quiet'], true, 'likely',
 'Fresno Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.6, 87),
('Tower District — Tower Theatre', 'Fresno', 'CA', 36.7614, -119.7902,
 '1939 Streamline Moderne theater with original neon marquee, anchoring a small bohemian arts district.',
 'public', array['Historic','Neon','Architecture'], false, 'unknown',
 'Public sidewalk. Theatre interior requires booking.',
 'published', 'curated_v1', 4.5, 85),
('Roeding Park — Sumida Garden', 'Fresno', 'CA', 36.7660, -119.8324,
 '157-acre park with mature trees, lakes, and a small Japanese garden donated by Fresno''s sister city.',
 'public', array['Park','Garden','Trees'], true, 'likely',
 'Fresno Parks permit required.',
 'published', 'curated_v1', 4.3, 81),
('Kearney Park — Kearney Mansion', 'Fresno', 'CA', 36.7497, -119.9485,
 '225-acre park with a long palm-lined drive and the 1903 Kearney Mansion at the end.',
 'public', array['Mansion','Trees','Historic'], true, 'likely',
 'Fresno County Parks permit required.',
 'published', 'curated_v1', 4.4, 83),

-- ── Sacramento, CA ────────────────────────────────────────────────────────
('Tower Bridge', 'Sacramento', 'CA', 38.5810, -121.5066,
 'Gold-painted vertical-lift bridge over the Sacramento River, framing the Capitol behind.',
 'public', array['Bridge','Iconic','Skyline'], false, 'likely',
 'City of Sacramento permit needed for crews.',
 'published', 'curated_v1', 4.7, 89),
('Old Sacramento Waterfront', 'Sacramento', 'CA', 38.5828, -121.5057,
 'Wood-plank boardwalks and Gold Rush-era brick buildings along the river.',
 'public', array['Historic','Waterfront','Boardwalk'], false, 'likely',
 'State of California Parks permit required for organized commercial shoots.',
 'published', 'curated_v1', 4.5, 85),
('California State Capitol — Rose Garden', 'Sacramento', 'CA', 38.5762, -121.4929,
 '40 acres of grounds around the 1874 white-domed Capitol, including a 1,200-bush rose garden.',
 'public', array['Architecture','Garden','Historic'], true, 'likely',
 'California Highway Patrol approval required for organized shoots on Capitol grounds.',
 'published', 'curated_v1', 4.6, 87),
('McKinley Park — Rose Garden', 'Sacramento', 'CA', 38.5780, -121.4628,
 '32-acre East Sacramento park with a 1,200-bush rose garden and a quiet pond.',
 'public', array['Park','Garden','Floral'], true, 'verified',
 'Sacramento Parks photo permit required: $50 portrait.',
 'published', 'curated_v1', 4.6, 87),
('American River Parkway — Discovery Park', 'Sacramento', 'CA', 38.6018, -121.5085,
 '23-mile riverside parkway. Discovery Park is at the confluence with the Sacramento River.',
 'public', array['Waterfront','Park','Outdoor'], true, 'likely',
 'Sacramento County Parks permit required.',
 'published', 'curated_v1', 4.4, 83),

-- ── Mesa, AZ ──────────────────────────────────────────────────────────────
('Riparian Preserve at Water Ranch', 'Gilbert', 'AZ', 33.3641, -111.7341,
 '110 acres of constructed wetlands with seven ponds, walking trails, and abundant birds. East of Mesa.',
 'public', array['Wetland','Outdoor','Quiet'], false, 'unknown',
 'Free public preserve.',
 'published', 'curated_v1', 4.6, 87),
('Salt River — Coon Bluff', 'Mesa', 'AZ', 33.5450, -111.6219,
 'Tonto National Forest river access with desert cliffs, cottonwoods, and frequent wild horses.',
 'public', array['Outdoor','River','Desert'], true, 'verified',
 'USFS Tonto National Forest permit required for organized shoots.',
 'published', 'curated_v1', 4.7, 89),
('Usery Mountain Regional Park — Wind Cave Trail', 'Mesa', 'AZ', 33.4762, -111.6202,
 'Saguaro forest with the Pass Mountains rising behind. Wind Cave is a small geological cave at trail''s end.',
 'public', array['Outdoor','Desert','Mountain'], true, 'verified',
 'Maricopa County Parks permit required.',
 'published', 'curated_v1', 4.5, 85),
('Saguaro Lake — Butcher Jones Beach', 'Mesa', 'AZ', 33.5704, -111.5328,
 'Reservoir in the desert with red bluffs, saguaros, and clear water — about 30 minutes northeast.',
 'public', array['Lake','Outdoor','Desert'], true, 'likely',
 'USFS permit required for organized shoots.',
 'published', 'curated_v1', 4.6, 87),
('Mesa Arts Center', 'Mesa', 'AZ', 33.4150, -111.8311,
 'Modernist arts campus with terra-cotta-toned walls, water features, and shaded courtyards.',
 'public', array['Architecture','Modernist','Urban'], true, 'likely',
 'Mesa Arts Center approval needed for commercial photography on the campus.',
 'published', 'curated_v1', 4.4, 83),

-- ── Long Beach, CA ────────────────────────────────────────────────────────
('Naples Island — Canals & Bridges', 'Long Beach', 'CA', 33.7548, -118.1217,
 'Italian-style residential canals lined with bridges, gondolas, and waterfront homes.',
 'public', array['Waterfront','Quaint','Architecture'], false, 'likely',
 'Public sidewalks; be respectful of residences.',
 'published', 'curated_v1', 4.6, 87),
('Queen Mary', 'Long Beach', 'CA', 33.7522, -118.1903,
 '1934 ocean liner permanently moored in the harbor — Art Deco interiors and dramatic exterior.',
 'private', array['Historic','Architecture','Iconic'], true, 'verified',
 'Queen Mary photography packages required for any organized shoot.',
 'published', 'curated_v1', 4.6, 87),
('Belmont Pier', 'Long Beach', 'CA', 33.7596, -118.1376,
 '1,300-foot fishing pier extending into the Pacific. Sunset framed by Catalina Island on clear days.',
 'public', array['Pier','Sunset','Coastal'], false, 'unknown',
 'Public pier.',
 'published', 'curated_v1', 4.4, 83),
('Long Beach Lighthouse — Lions Lighthouse for Sight', 'Long Beach', 'CA', 33.7558, -118.1907,
 '1908 cast-iron lighthouse moved to Shoreline Drive, painted bright white with red trim.',
 'public', array['Lighthouse','Coastal','Historic'], false, 'unknown',
 'Public park.',
 'published', 'curated_v1', 4.4, 83),
('Earl Burns Miller Japanese Garden — CSU Long Beach', 'Long Beach', 'CA', 33.7869, -118.1108,
 '1.3-acre stroll garden on the CSU campus with koi ponds, a tea house, and zen garden.',
 'private', array['Garden','Asian','Quiet'], true, 'verified',
 'CSU LB photography permit required for organized shoots.',
 'published', 'curated_v1', 4.5, 85),

-- ── Colorado Springs, CO ──────────────────────────────────────────────────
('Garden of the Gods — Balanced Rock', 'Colorado Springs', 'CO', 38.8786, -104.8866,
 '300-foot red sandstone formations against the snow-capped Pikes Peak.',
 'public', array['Outdoor','Dramatic','Iconic'], true, 'verified',
 'Colorado Springs Parks photo permit required: $75 portrait.',
 'published', 'curated_v1', 4.9, 95),
('Manitou Cliff Dwellings', 'Manitou Springs', 'CO', 38.8633, -104.8945,
 'Ancestral Puebloan-style cliff dwellings rebuilt at the foot of Pikes Peak.',
 'private', array['Historic','Outdoor','Cultural'], true, 'likely',
 'Cliff Dwellings permit required for organized shoots.',
 'published', 'curated_v1', 4.5, 85),
('Helen Hunt Falls — North Cheyenne Cañon Park', 'Colorado Springs', 'CO', 38.7965, -104.8744,
 '35-foot waterfall with a foot bridge crossing directly above the drop.',
 'public', array['Waterfall','Outdoor','Forest'], true, 'likely',
 'Colorado Springs Parks permit required.',
 'published', 'curated_v1', 4.6, 87),
('Seven Falls', 'Colorado Springs', 'CO', 38.7869, -104.8750,
 '181-foot cascade in seven distinct drops, climbed via 224 steps. Privately operated; admission required.',
 'private', array['Waterfall','Outdoor','Dramatic'], true, 'verified',
 'Seven Falls (operated by The Broadmoor) requires advance booking for commercial / wedding photography.',
 'published', 'curated_v1', 4.7, 89),
('Pikes Peak Highway — Crystal Reservoir', 'Cascade', 'CO', 38.8566, -104.9986,
 'Reservoir at 9,200 feet with Pikes Peak rising directly behind. Admission via toll road.',
 'private', array['Mountain','Lake','Hilltop'], true, 'likely',
 'Pikes Peak — America''s Mountain (City of Colorado Springs) photo permit required.',
 'published', 'curated_v1', 4.7, 89),

-- ── Raleigh, NC ───────────────────────────────────────────────────────────
('Dorothea Dix Park — Flower Field', 'Raleigh', 'NC', 35.7715, -78.6498,
 '308-acre park with a sunflower field (peak July), and the Raleigh skyline rising behind.',
 'public', array['Park','Floral','Skyline'], true, 'likely',
 'Dix Park Conservancy photo permit required for organized shoots during bloom season.',
 'published', 'curated_v1', 4.7, 89),
('JC Raulston Arboretum', 'Raleigh', 'NC', 35.8013, -78.6973,
 '10-acre NC State arboretum with themed gardens and one of the country''s best plant-collection diversities.',
 'private', array['Garden','Quiet','Floral'], true, 'verified',
 'NC State JC Raulston photo permit required: $50 portrait.',
 'published', 'curated_v1', 4.6, 87),
('William B. Umstead State Park — Sycamore Trail', 'Raleigh', 'NC', 35.8717, -78.7506,
 '5,500-acre park with hardwood forest, three lakes, and stone-arch bridges from CCC era.',
 'public', array['Forest','Outdoor','Lake'], true, 'verified',
 'NC State Parks photo permit required.',
 'published', 'curated_v1', 4.6, 87),
('Pullen Park — Carousel', 'Raleigh', 'NC', 35.7872, -78.6610,
 '66-acre park with a 1911 Dentzel carousel, paddle boats, and old hardwoods.',
 'public', array['Park','Carousel','Historic'], true, 'likely',
 'Raleigh Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.5, 85),
('Fayetteville Street — Downtown Raleigh', 'Raleigh', 'NC', 35.7796, -78.6386,
 'Pedestrian-friendly main street running from the Capitol to the convention center, with sculpture and historic facades.',
 'public', array['Urban','Historic','Architecture'], false, 'likely',
 'Public street.',
 'published', 'curated_v1', 4.4, 83),

-- ── Virginia Beach, VA ────────────────────────────────────────────────────
('Virginia Beach Boardwalk — Neptune Statue', 'Virginia Beach', 'VA', 36.8543, -75.9758,
 '34-foot bronze Neptune statue at 31st Street, fronting a 3-mile boardwalk.',
 'public', array['Beach','Iconic','Sculpture'], false, 'unknown',
 'Public boardwalk.',
 'published', 'curated_v1', 4.6, 87),
('First Landing State Park — Bald Cypress Trail', 'Virginia Beach', 'VA', 36.9145, -76.0489,
 'Forested park with bald cypress in salt marshes, dunes, and a Chesapeake Bay shoreline.',
 'public', array['Outdoor','Marsh','Forest'], true, 'verified',
 'Virginia State Parks photo permit required.',
 'published', 'curated_v1', 4.7, 89),
('Cape Henry Lighthouse', 'Virginia Beach', 'VA', 36.9259, -76.0103,
 '1792 sandstone lighthouse — the first authorized by the US Federal government.',
 'public', array['Lighthouse','Historic','Coastal'], true, 'likely',
 'Preservation Virginia approval needed for organized shoots.',
 'published', 'curated_v1', 4.5, 85),
('Back Bay National Wildlife Refuge', 'Virginia Beach', 'VA', 36.6845, -75.9224,
 '9,250-acre coastal refuge with maritime forests, dunes, and freshwater impoundments.',
 'public', array['Outdoor','Wildlife','Marsh'], true, 'verified',
 'USFWS commercial photography permit required.',
 'published', 'curated_v1', 4.6, 87),
('Pungo — Lavender Fields (seasonal)', 'Virginia Beach', 'VA', 36.6984, -76.0322,
 'Several u-pick lavender farms in the Pungo agricultural area, peak mid-June.',
 'private', array['Floral','Field','Seasonal'], true, 'verified',
 'Each farm sets its own photography fee — typically $50–150 per session. Book ahead.',
 'published', 'curated_v1', 4.7, 89),

-- ── Omaha, NE ─────────────────────────────────────────────────────────────
('Old Market — cobblestone streets', 'Omaha', 'NE', 41.2563, -95.9302,
 '11-block warehouse district in the original commercial heart of Omaha. Brick streets, ironwork, vintage marquees.',
 'public', array['Historic','Cobblestone','Urban'], false, 'likely',
 'Public streets. City of Omaha film permit needed for crews.',
 'published', 'curated_v1', 4.6, 87),
('Lauritzen Gardens', 'Omaha', 'NE', 41.2241, -95.9285,
 '100 acres of formal gardens, model railroad garden, and indoor conservatory.',
 'private', array['Garden','Park','Floral'], true, 'verified',
 'Lauritzen photo permit required: $75 portrait, $750+ wedding.',
 'published', 'curated_v1', 4.7, 89),
('Bob Kerrey Pedestrian Bridge', 'Omaha', 'NE', 41.2690, -95.9230,
 '3,000-foot S-curved cable-stayed pedestrian bridge spanning the Missouri River.',
 'public', array['Bridge','Waterfront','Iconic'], false, 'likely',
 'City of Omaha permit needed for crews.',
 'published', 'curated_v1', 4.7, 89),
('Joslyn Castle', 'Omaha', 'NE', 41.2616, -95.9622,
 '1903 Scottish Baronial mansion with limestone exterior, mature oaks, and 5.5-acre grounds.',
 'private', array['Mansion','Architecture','Historic'], true, 'verified',
 'Joslyn Castle wedding/photo packages required.',
 'published', 'curated_v1', 4.6, 87),
('Heartland of America Park — Lewis & Clark Landing', 'Omaha', 'NE', 41.2569, -95.9171,
 'Riverfront park with downtown skyline behind. Recently renovated with new sculptures and lawns.',
 'public', array['Waterfront','Park','Skyline'], false, 'likely',
 'City permit needed for crews.',
 'published', 'curated_v1', 4.4, 83),

-- ── Oakland, CA ───────────────────────────────────────────────────────────
('Lake Merritt — Necklace of Lights', 'Oakland', 'CA', 37.8045, -122.2620,
 'Tidal lagoon in the heart of Oakland, surrounded by 3.4 miles of paths and 3,400 globe lights.',
 'public', array['Waterfront','Park','Urban'], true, 'likely',
 'Oakland Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.6, 87),
('Mountain View Cemetery', 'Oakland', 'CA', 37.8401, -122.2454,
 '226-acre Frederick Law Olmsted-designed cemetery with mausoleums, mature trees, and city views.',
 'private', array['Historic','Trees','Quiet'], true, 'verified',
 'Mountain View Cemetery requires advance permission for organized photography out of respect for visitors.',
 'published', 'curated_v1', 4.7, 89),
('Redwood Regional Park — Stream Trail', 'Oakland', 'CA', 37.8166, -122.1641,
 '1,830-acre park with second-growth coast redwoods 15 minutes from downtown.',
 'public', array['Forest','Outdoor','Quiet'], true, 'verified',
 'East Bay Regional Parks photo permit required.',
 'published', 'curated_v1', 4.7, 89),
('Jack London Square Waterfront', 'Oakland', 'CA', 37.7949, -122.2773,
 'Restored Inner Harbor district with the historic Heinold''s First and Last Chance saloon and ferry boats.',
 'public', array['Waterfront','Historic','Urban'], false, 'likely',
 'Public waterfront. Crews need a permit.',
 'published', 'curated_v1', 4.4, 83),
('Joaquin Miller Park — Sequoia Arena', 'Oakland', 'CA', 37.8154, -122.1770,
 '500-acre hilltop park with redwood groves, an outdoor amphitheater of stone, and Bay views.',
 'public', array['Forest','Park','Hilltop'], true, 'likely',
 'Oakland Parks permit required.',
 'published', 'curated_v1', 4.5, 85),

-- ── Tulsa, OK ─────────────────────────────────────────────────────────────
('The Gathering Place', 'Tulsa', 'OK', 36.1180, -95.9854,
 '66.5-acre riverfront park designed by Michael Van Valkenburgh — sculpture-like playgrounds, lagoons, and open lawns.',
 'public', array['Park','Sculpture','Urban'], true, 'verified',
 'Gathering Place photography permit required: $50 portrait.',
 'published', 'curated_v1', 4.8, 92),
('Center of the Universe — Bob Wills Plaza', 'Tulsa', 'OK', 36.1546, -95.9908,
 'Acoustic anomaly on a pedestrian bridge in downtown — your voice echoes back at you. The brick circle marks the spot.',
 'public', array['Iconic','Quirky','Urban'], false, 'unknown',
 'Public pedestrian bridge.',
 'published', 'curated_v1', 4.4, 83),
('Philbrook Museum of Art — Italian Gardens', 'Tulsa', 'OK', 36.1260, -95.9640,
 '23-acre 1927 Italian-Renaissance villa with formal gardens, fountains, and tempietto.',
 'private', array['Mansion','Garden','Historic'], true, 'verified',
 'Philbrook photography permit required: $200+ for portraits, more for weddings.',
 'published', 'curated_v1', 4.8, 92),
('Greenwood District — Black Wall Street Memorial', 'Tulsa', 'OK', 36.1612, -95.9847,
 'Restored historic district with memorials to the 1921 Tulsa Race Massacre. Cultural and historic depth — handle with care.',
 'public', array['Historic','Cultural','Urban'], false, 'likely',
 'Public sidewalks.',
 'published', 'curated_v1', 4.6, 87),
('Tulsa Botanic Garden', 'Tulsa', 'OK', 36.2521, -96.0742,
 '170-acre botanic garden 15 minutes north of downtown — formal gardens, native woodlands, and a children''s discovery garden.',
 'private', array['Garden','Park','Floral'], true, 'verified',
 'Tulsa Botanic photography permit required: $75 portrait.',
 'published', 'curated_v1', 4.6, 87),

-- ── Arlington, TX ─────────────────────────────────────────────────────────
('River Legacy Park — Founder''s Plaza', 'Arlington', 'TX', 32.7704, -97.1216,
 '1,300-acre park along the Trinity River with stone bridges, hardwood forest, and walking trails.',
 'public', array['Park','Forest','River'], true, 'likely',
 'Arlington Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.5, 85),
('AT&T Stadium — Plaza', 'Arlington', 'TX', 32.7473, -97.0945,
 '1.2-million-square-foot retractable-roof stadium. The plaza and exterior architecture are striking.',
 'public', array['Architecture','Iconic','Modernist'], true, 'likely',
 'Stadium management approval required for shoots on the plaza.',
 'published', 'curated_v1', 4.4, 83),
('Lake Arlington — South Shore', 'Arlington', 'TX', 32.6922, -97.2126,
 '1,939-acre reservoir with a 9-mile loop — sunset over the water with downtown Fort Worth in the distance.',
 'public', array['Lake','Sunset','Outdoor'], false, 'likely',
 'Arlington Parks permit needed for organized shoots.',
 'published', 'curated_v1', 4.3, 80),
('Levitt Pavilion — Main Street', 'Arlington', 'TX', 32.7359, -97.1080,
 'Outdoor concert venue with terraced lawn, concrete shell, and downtown Arlington behind.',
 'public', array['Urban','Architecture','Park'], false, 'unknown',
 'Public lawn outside event hours.',
 'published', 'curated_v1', 4.2, 79),
('The Parks Mall — Reflecting Pool & Sculptures', 'Arlington', 'TX', 32.6815, -97.1305,
 'Outdoor sculpture garden and reflecting pool fronting the mall — quietly photogenic at golden hour.',
 'public', array['Urban','Sculpture','Modernist'], false, 'unknown',
 'Public sidewalks; mall property — be respectful.',
 'published', 'curated_v1', 4.0, 75),

-- ── Wichita, KS ───────────────────────────────────────────────────────────
('Keeper of the Plains', 'Wichita', 'KS', 37.6877, -97.3343,
 '44-foot Native American statue at the confluence of the Big and Little Arkansas Rivers. Twin pedestrian bridges span to the base.',
 'public', array['Iconic','Sculpture','Waterfront'], false, 'likely',
 'City of Wichita Parks permit needed for organized shoots.',
 'published', 'curated_v1', 4.7, 89),
('Botanica Wichita', 'Wichita', 'KS', 37.6977, -97.3499,
 '17.6-acre botanical garden with themed sections including a Children''s Garden, Shakespearean Garden, and Asian gardens.',
 'private', array['Garden','Park','Floral'], true, 'verified',
 'Botanica photography permit required: $100 portrait, $500+ wedding.',
 'published', 'curated_v1', 4.6, 87),
('Old Town Wichita', 'Wichita', 'KS', 37.6886, -97.3304,
 'Restored brick warehouse district with cobblestone streets, neon signage, and the Old Town Square fountain.',
 'public', array['Historic','Cobblestone','Urban'], false, 'likely',
 'Public streets. City film permit for crews.',
 'published', 'curated_v1', 4.4, 83),
('Riverside Park — McLean Boulevard', 'Wichita', 'KS', 37.6993, -97.3470,
 'River-edge park with mature pecan and oak trees, a footbridge, and the Wichita skyline.',
 'public', array['Park','Waterfront','Skyline'], false, 'likely',
 'Wichita Parks permit needed for organized shoots.',
 'published', 'curated_v1', 4.4, 83),
('Cowtown — Old Cowtown Museum', 'Wichita', 'KS', 37.6918, -97.3573,
 'Restored 1865-era frontier town with 50+ historic buildings, dirt streets, and period-dress staff.',
 'private', array['Historic','Western','Cultural'], true, 'verified',
 'Old Cowtown Museum photo permit required: $200+ for organized commercial / wedding shoots.',
 'published', 'curated_v1', 4.5, 85);

-- 22 cities × 5 locations = 110 rows. Combined with batch 1 (28 cities, 140 rows)
-- this brings the total seeded coverage to 50 metros / 250 locations.
