-- Mountain West small towns + wine country + New England + California
-- coast + Florida coastal + Hawaii (Maui & Kauai). 18 places, 3 each
-- = 54 new rows. Apostrophes escaped with '' doubling.

insert into public.locations (
  name, city, state, latitude, longitude, description, access_type, tags,
  permit_required, permit_certainty, permit_notes,
  status, source, rating, quality_score
) values

-- ── Whitefish, MT (Glacier-adjacent) ─────────────────────────────────────
('Whitefish Lake', 'Whitefish', 'MT', 48.4308, -114.3431,
 'Glacier-fed lake at the foot of Big Mountain — sailboats, mountain backdrop, the historic City Beach and lakeside resort.',
 'public', array['Lake','Mountain','Outdoor'], true, 'likely',
 'Whitefish Parks photo permit applies for crews.',
 'published', 'curated_v1', 4.7, 87),
('Big Mountain Summit (Whitefish Mountain Resort)', 'Whitefish', 'MT', 48.4869, -114.3464,
 '6,817-foot summit accessed via the year-round Big Mountain chairlift — sweeping Glacier NP + Flathead Valley views.',
 'public', array['Mountain','Overlook','Iconic'], true, 'likely',
 'Whitefish Mountain Resort handles commercial photography requests.',
 'published', 'curated_v1', 4.8, 89),
('Downtown Whitefish — Central Avenue', 'Whitefish', 'MT', 48.4108, -114.3372,
 'Restored railroad-era main street — log cabin storefronts, Cascade Range backdrop, the iconic 1927 Great Northern depot.',
 'public', array['Historic','Architecture','Mountain'], false, 'unknown',
 'Public sidewalks.',
 'published', 'curated_v1', 4.5, 84),

-- ── Cody, WY (Yellowstone east gateway) ──────────────────────────────────
('Buffalo Bill Center of the West', 'Cody', 'WY', 44.5267, -109.0808,
 'Five museums under one roof — Buffalo Bill memorabilia, Native American galleries, the Plains Indian Museum, period architecture.',
 'public', array['Historic','Iconic','Western'], true, 'likely',
 'BBCW handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 88),
('Old Trail Town', 'Cody', 'WY', 44.5239, -109.1186,
 '26 historic frontier-era buildings collected from across Wyoming — Butch Cassidy''s cabin, Crow grave sites, prairie behind.',
 'public', array['Historic','Western','Outdoor'], true, 'likely',
 'Old Trail Town handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Beartooth Highway — Top of the World', 'Cody', 'WY', 44.9722, -109.4717,
 'Highway through 10,947-foot Beartooth Pass — alpine tundra, glacial tarns, sweeping views all the way to Yellowstone''s east entrance.',
 'public', array['Mountain','Iconic','Overlook'], true, 'likely',
 'Custer Gallatin NF photo permit may apply; closed in winter.',
 'published', 'curated_v1', 4.9, 92),

-- ── Steamboat Springs, CO ─────────────────────────────────────────────────
('Fish Creek Falls', 'Steamboat Springs', 'CO', 40.4886, -106.7836,
 '283-foot waterfall five minutes from downtown — paved overlook trail, classic Colorado mountain setting.',
 'public', array['Waterfall','Mountain','Outdoor'], true, 'likely',
 'Routt NF photo permit may apply.',
 'published', 'curated_v1', 4.7, 87),
('Strawberry Park Hot Springs', 'Steamboat Springs', 'CO', 40.5439, -106.8197,
 'Sandstone-tiered natural hot springs in a forested canyon — clothing-optional after dark, mountain stream nearby.',
 'public', array['Spring','Mountain','Outdoor'], true, 'likely',
 'Strawberry Park handles photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Mt Werner Summit', 'Steamboat Springs', 'CO', 40.4592, -106.7728,
 '10,568-foot summit accessed via the gondola at Steamboat Resort — wildflower meadows in summer, sweeping Yampa Valley views.',
 'public', array['Mountain','Overlook','Outdoor'], true, 'likely',
 'Steamboat Resort handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),

-- ── Ouray, CO ─────────────────────────────────────────────────────────────
('Box Canyon Falls', 'Ouray', 'CO', 38.0144, -107.6739,
 '285-foot waterfall through a 20-foot-wide quartzite slot canyon — bridge views from above, walkway directly under the falls below.',
 'public', array['Waterfall','Canyon','Iconic'], true, 'likely',
 'Ouray Parks photo permit applies.',
 'published', 'curated_v1', 4.8, 89),
('Million Dollar Highway — Red Mountain Pass', 'Ouray', 'CO', 37.8989, -107.7128,
 '11,018-foot pass on US-550 — the most dramatic 23 miles of road in the Rockies, no guardrails, San Juan peaks all around.',
 'public', array['Mountain','Iconic','Overlook'], false, 'likely',
 'Public road; commercial crews check with CDOT.',
 'published', 'curated_v1', 4.9, 92),
('Bear Creek Falls Overlook', 'Ouray', 'CO', 37.9669, -107.6494,
 'Roadside overlook on US-550 — 227-foot waterfall plunging directly under the highway bridge, San Juan Mountains framing.',
 'public', array['Waterfall','Mountain','Bridge'], false, 'unknown',
 'Public roadside.',
 'published', 'curated_v1', 4.7, 86),

-- ── Mammoth Lakes, CA ─────────────────────────────────────────────────────
('Devils Postpile National Monument', 'Mammoth Lakes', 'CA', 37.6256, -119.0844,
 '60-foot columnar basalt — hexagonal lava columns formed 100,000 years ago, the iconic Sierra geology shot.',
 'public', array['Iconic','Mountain','Outdoor'], true, 'likely',
 'NPS commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),
('Mono Lake — South Tufa', 'Mammoth Lakes', 'CA', 37.9408, -119.0269,
 'Saltwater lake with calcium-carbonate tufa towers rising from the water — alien landscape east of Yosemite, sunrise reflections.',
 'public', array['Lake','Iconic','Outdoor'], true, 'likely',
 'Mono Basin Scenic Area photo permit required.',
 'published', 'curated_v1', 4.9, 92),
('Convict Lake', 'Mammoth Lakes', 'CA', 37.5894, -118.8594,
 'Glacial lake with 12,268-foot Mt Morrison rising directly behind — easy 3-mile loop, golden aspens in October.',
 'public', array['Lake','Mountain','Iconic'], true, 'likely',
 'Inyo NF photo permit may apply.',
 'published', 'curated_v1', 4.8, 89),

-- ── Sun Valley, ID ────────────────────────────────────────────────────────
('Sawtooth Mountains — Galena Summit Overlook', 'Sun Valley', 'ID', 43.8783, -114.7050,
 '8,701-foot pass on Highway 75 — sweeping panorama of the Sawtooths and the Salmon River headwaters.',
 'public', array['Mountain','Overlook','Iconic'], false, 'likely',
 'Sawtooth NF photo permit may apply.',
 'published', 'curated_v1', 4.9, 92),
('Sun Valley Lodge', 'Sun Valley', 'ID', 43.6953, -114.3528,
 '1936 alpine lodge — Hemingway lived here, period stone-and-timber architecture, Bald Mountain backdrop.',
 'public', array['Architecture','Historic','Mountain'], true, 'likely',
 'Sun Valley Resort handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Redfish Lake', 'Sun Valley', 'ID', 44.1503, -114.9181,
 'Cobalt-blue glacial lake at the foot of the Sawtooth Mountains — sandy beaches, the lodge dock, paddle-board reflections.',
 'public', array['Lake','Mountain','Iconic'], true, 'likely',
 'Sawtooth NRA photo permit required.',
 'published', 'curated_v1', 4.9, 92),

-- ── Sonoma, CA (wine country) ─────────────────────────────────────────────
('Sonoma Plaza', 'Sonoma', 'CA', 38.2917, -122.4581,
 'Largest plaza in California (8 acres) — 1823 mission, Bear Flag Monument, century-old olive trees, formal city hall in the center.',
 'public', array['Historic','Iconic','Park'], true, 'likely',
 'Sonoma Parks photo permit applies.',
 'published', 'curated_v1', 4.7, 88),
('Mission San Francisco Solano', 'Sonoma', 'CA', 38.2933, -122.4561,
 'Last and northernmost Spanish mission in California (1823) — adobe walls, restored interior, on the Sonoma plaza.',
 'public', array['Historic','Religious','Architecture'], true, 'likely',
 'CA State Parks photo permit required.',
 'published', 'curated_v1', 4.6, 85),
('Sonoma Valley Vineyards (Carneros)', 'Sonoma', 'CA', 38.2369, -122.4628,
 'Rolling vineyard hills along Highway 121 — Domaine Carneros chateau visible, gold-hour light on Pinot rows.',
 'public', array['Garden','Outdoor','Wedding'], true, 'likely',
 'Individual wineries handle commercial photography requests.',
 'published', 'curated_v1', 4.8, 89),

-- ── Dundee, OR (Willamette Valley wine) ──────────────────────────────────
('Domaine Drouhin Oregon', 'Dundee', 'OR', 45.2761, -123.0628,
 'Hilltop French-style estate winery — terraced Pinot vineyards, Cascade view (Mt Hood + Mt Jefferson on clear days).',
 'public', array['Garden','Mountain','Wedding'], true, 'likely',
 'DDO handles commercial photography requests.',
 'published', 'curated_v1', 4.8, 89),
('Red Hills of Dundee', 'Dundee', 'OR', 45.2767, -123.0231,
 'Iconic Willamette Valley wine-country hills — patchwork vineyards on volcanic red soil, sweeping valley views.',
 'public', array['Outdoor','Garden','Iconic'], false, 'unknown',
 'Public roads; respect winery property.',
 'published', 'curated_v1', 4.7, 87),
('Sokol Blosser Winery', 'Dundee', 'OR', 45.2700, -123.0631,
 'Modern wood-clad tasting room on a vineyard slope — sustainable architecture, Cascade-view terrace, golden-hour rows.',
 'public', array['Architecture','Garden','Modernist'], true, 'likely',
 'Sokol Blosser handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),

-- ── Camden, ME ────────────────────────────────────────────────────────────
('Mount Battie Summit', 'Camden', 'ME', 44.2208, -69.0769,
 '780-foot summit in Camden Hills SP — stone tower at the top, Penobscot Bay islands spread below, the iconic Maine coast view.',
 'public', array['Overlook','Coastal','Iconic'], true, 'likely',
 'Maine State Parks photo permit required.',
 'published', 'curated_v1', 4.8, 89),
('Camden Harbor', 'Camden', 'ME', 44.2106, -69.0644,
 'Working harbor with classic Maine schooners — windjammer fleet docked, Curtis Island Light beyond, mountains rising right behind.',
 'public', array['Waterfront','Coastal','Iconic'], false, 'unknown',
 'Public harbor.',
 'published', 'curated_v1', 4.8, 89),
('Curtis Island Lighthouse', 'Camden', 'ME', 44.2050, -69.0500,
 'Small white-painted 1896 lighthouse on a rocky island guarding Camden Harbor — best photographed from the harbor or the Mt Battie summit.',
 'public', array['Lighthouse','Coastal','Iconic'], false, 'unknown',
 'Island accessible only by private boat.',
 'published', 'curated_v1', 4.6, 85),

-- ── Portsmouth, NH ────────────────────────────────────────────────────────
('Strawbery Banke Museum', 'Portsmouth', 'NH', 43.0769, -70.7556,
 '10-acre living-history museum — 32 historic 17th-19th-century homes, period gardens, the one preserved colonial neighborhood.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Strawbery Banke handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Market Square', 'Portsmouth', 'NH', 43.0772, -70.7547,
 'North Church Steeple over a brick-faced colonial square — boutiques, cafes, the heart of historic Portsmouth.',
 'public', array['Historic','Architecture','Urban'], false, 'unknown',
 'Public square.',
 'published', 'curated_v1', 4.7, 87),
('Prescott Park Waterfront', 'Portsmouth', 'NH', 43.0742, -70.7528,
 'Riverside flower garden — formal beds, fountains, sailboats on the Piscataqua, footbridge to Pierce Island.',
 'public', array['Garden','Waterfront','Park'], true, 'likely',
 'Portsmouth Parks photo permit applies.',
 'published', 'curated_v1', 4.7, 86),

-- ── North Conway, NH (White Mountains) ───────────────────────────────────
('Mount Washington Summit (via Cog Railway or Auto Road)', 'North Conway', 'NH', 44.2706, -71.3033,
 '6,288-foot summit — highest peak in the Northeast, the historic Tip Top House, often-extreme weather views.',
 'public', array['Mountain','Iconic','Overlook'], true, 'likely',
 'Mt Washington State Park photo permit required.',
 'published', 'curated_v1', 4.8, 90),
('Crawford Notch State Park — Silver Cascade', 'North Conway', 'NH', 44.2206, -71.4039,
 '1,000-foot multi-tier waterfall directly off Route 302 — White Mountains framing, autumn-foliage shot.',
 'public', array['Waterfall','Mountain','Outdoor'], true, 'likely',
 'NH State Parks photo permit required.',
 'published', 'curated_v1', 4.7, 87),
('Cathedral Ledge', 'North Conway', 'NH', 44.0658, -71.1806,
 '700-foot granite cliff with a paved drive to the top — sweeping views over Mt Washington Valley, climber-popular face below.',
 'public', array['Overlook','Mountain','Outdoor'], true, 'likely',
 'NH State Parks photo permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Santa Barbara, CA ─────────────────────────────────────────────────────
('Santa Barbara County Courthouse', 'Santa Barbara', 'CA', 34.4214, -119.7036,
 '1929 Spanish-Moorish complex — sandstone facade, hand-painted tiles, the El Mirador clock tower''s 360-degree panorama.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Santa Barbara County handles commercial photography requests.',
 'published', 'curated_v1', 4.8, 90),
('Stearns Wharf', 'Santa Barbara', 'CA', 34.4094, -119.6856,
 'Oldest wooden working wharf in California — sea lions on the pilings, Channel Islands on the horizon, downtown skyline behind.',
 'public', array['Waterfront','Coastal','Iconic'], false, 'unknown',
 'Public wharf.',
 'published', 'curated_v1', 4.7, 87),
('Mission Santa Barbara', 'Santa Barbara', 'CA', 34.4381, -119.7142,
 '1820 "Queen of the Missions" — twin Moorish bell towers, formal rose garden, fountain in front.',
 'public', array['Historic','Religious','Architecture'], true, 'likely',
 'Mission Santa Barbara handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),

-- ── Santa Cruz, CA ────────────────────────────────────────────────────────
('Santa Cruz Beach Boardwalk', 'Santa Cruz', 'CA', 36.9647, -122.0181,
 'West Coast''s oldest amusement park (1907) — wooden Giant Dipper roller coaster, neon at dusk, sand beach in front.',
 'public', array['Iconic','Beach','Boardwalk'], true, 'likely',
 'Boardwalk handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Natural Bridges State Beach', 'Santa Cruz', 'CA', 36.9519, -122.0594,
 'Sandstone arch above the Pacific — tide pools, monarch butterfly grove (Oct-Feb), framed-by-arch sunset.',
 'public', array['Beach','Coastal','Iconic'], true, 'likely',
 'CA State Parks photo permit required.',
 'published', 'curated_v1', 4.8, 89),
('West Cliff Drive', 'Santa Cruz', 'CA', 36.9544, -122.0303,
 '3-mile cliffside path along the Pacific — surfers below, the iconic Lighthouse Field, Steamer Lane swells.',
 'public', array['Coastal','Outdoor','Iconic'], false, 'likely',
 'Santa Cruz Parks photo permit applies for crews.',
 'published', 'curated_v1', 4.8, 89),

-- ── Mendocino, CA ─────────────────────────────────────────────────────────
('Mendocino Headlands', 'Mendocino', 'CA', 39.3083, -123.8089,
 'Bluff-top park wrapping the historic village — sea-stack-strewn cove, weathered cypress windbreaks, Pacific to the horizon.',
 'public', array['Coastal','Outdoor','Iconic'], true, 'likely',
 'CA State Parks photo permit required.',
 'published', 'curated_v1', 4.9, 92),
('Mendocino Village', 'Mendocino', 'CA', 39.3050, -123.7997,
 'Saltbox-style 1850s logging-town village preserved entirely — picket fences, water towers, redwood + ocean horizon every direction.',
 'public', array['Historic','Architecture','Coastal'], false, 'unknown',
 'Public sidewalks; respect private property.',
 'published', 'curated_v1', 4.8, 89),
('Glass Beach (Fort Bragg)', 'Mendocino', 'CA', 39.4533, -123.8133,
 'Pebble beach made of frosted sea glass — old dump site polished by decades of surf, closest beach to Mendocino village.',
 'public', array['Beach','Coastal','Iconic'], true, 'likely',
 'MacKerricher SP photo permit required; please don''t take glass.',
 'published', 'curated_v1', 4.6, 85),

-- ── Pensacola, FL ─────────────────────────────────────────────────────────
('Pensacola Beach Sign + Pier', 'Pensacola', 'FL', 30.3308, -87.1394,
 'Mid-century neon "Pensacola Beach" sign on Bob Sikes Bridge — and the Gulf-side pier, sugar-white sand below, turquoise water beyond.',
 'public', array['Iconic','Beach','Coastal'], false, 'unknown',
 'Public sign + pier.',
 'published', 'curated_v1', 4.7, 87),
('Pensacola Lighthouse + Maritime Museum', 'Pensacola', 'FL', 30.3464, -87.3047,
 '1859 lighthouse on the Pensacola Naval Air Station grounds — climbable, sweeping Gulf + Bay views, Blue Angels flyovers.',
 'public', array['Lighthouse','Historic','Iconic'], true, 'likely',
 'Pensacola Lighthouse Foundation handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Palafox Street Historic District', 'Pensacola', 'FL', 30.4111, -87.2169,
 'Spanish-colonial-influenced downtown — wrought-iron balconies, period storefronts, oak-shaded plazas.',
 'public', array['Historic','Architecture','Street'], false, 'unknown',
 'Public sidewalks.',
 'published', 'curated_v1', 4.6, 85),

-- ── Sanibel Island, FL ────────────────────────────────────────────────────
('Sanibel Island Lighthouse', 'Sanibel', 'FL', 26.4536, -82.0144,
 '1884 cast-iron lighthouse at the eastern tip of the island — stilted skeletal frame, pier and Gulf at the base.',
 'public', array['Lighthouse','Coastal','Historic'], true, 'likely',
 'Sanibel beach photo permit required for paid sessions.',
 'published', 'curated_v1', 4.7, 87),
('J.N. Ding Darling NWR', 'Sanibel', 'FL', 26.4525, -82.1097,
 '6,400-acre mangrove preserve — Wildlife Drive, ibis + roseate spoonbills, classic Florida wetland sunsets.',
 'public', array['Nature','Outdoor','Tropical'], true, 'likely',
 'USFWS commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),
('Bowman''s Beach', 'Sanibel', 'FL', 26.4547, -82.1394,
 'Quiet shell-collecting beach — fewer crowds than the lighthouse end, Gulf sunset, sea-grape trees lining the dunes.',
 'public', array['Beach','Coastal','Tropical'], true, 'likely',
 'Sanibel beach commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Kahului, HI (Maui) ────────────────────────────────────────────────────
('Haleakala Crater Sunrise', 'Kahului', 'HI', 20.7097, -156.2533,
 '10,023-foot summit of Maui''s dormant volcano — above-the-clouds sunrise (reservation required), volcanic moonscape inside the crater.',
 'public', array['Mountain','Sunrise','Iconic'], true, 'likely',
 'NPS Haleakala commercial photography permit required; sunrise reservation required.',
 'published', 'curated_v1', 4.9, 95),
('Iao Valley State Monument', 'Kahului', 'HI', 20.8819, -156.5450,
 '1,200-foot green basalt spire ("Iao Needle") in a tropical-rainforest valley — sacred Native Hawaiian site, paved overlook.',
 'public', array['Mountain','Tropical','Iconic'], true, 'likely',
 'Hawaii State Parks commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),
('Twin Falls — Road to Hana', 'Kahului', 'HI', 20.9075, -156.1525,
 'First major waterfall stop on the Road to Hana — easy short trail, jungle pools, bamboo forest. The classic Hana wallpaper shot.',
 'public', array['Waterfall','Tropical','Outdoor'], true, 'likely',
 'Wailele Farm handles commercial photography permits.',
 'published', 'curated_v1', 4.8, 89),

-- ── Lihue, HI (Kauai) ─────────────────────────────────────────────────────
('Kalalau Lookout', 'Lihue', 'HI', 22.1494, -159.6308,
 '4,000-foot cliff edge over the Na Pali Coast — fluted green-velvet ridges plunging into the Pacific, the iconic Kauai shot.',
 'public', array['Coastal','Iconic','Overlook'], true, 'likely',
 'Hawaii State Parks commercial photography permit required.',
 'published', 'curated_v1', 4.9, 94),
('Wailua Falls', 'Lihue', 'HI', 22.0383, -159.3717,
 '80-foot two-tiered waterfall — the "Fantasy Island" opening shot, accessible via a short paved overlook from the road.',
 'public', array['Waterfall','Iconic','Tropical'], false, 'unknown',
 'Public roadside.',
 'published', 'curated_v1', 4.7, 87),
('Hanapepe Swinging Bridge', 'Lihue', 'HI', 21.9114, -159.5944,
 'Wood-and-cable footbridge over the Hanapepe River — historic plantation town atmosphere, Friday Art Night nearby.',
 'public', array['Bridge','Historic','Tropical'], false, 'unknown',
 'Public bridge.',
 'published', 'curated_v1', 4.5, 84);
