-- Northern Plains + regional filler seed. Heavy coverage of the Dakotas
-- and Nebraska (genuinely under-represented in any photo-location
-- dataset), plus Texas Hill Country, Big Bend, mid-Atlantic + Southeast
-- coastal towns, Midwestern small-town historic strips, and Pacific
-- NW coastal filler.
--
-- 26 places, 3 locations each = 78 rows. Same conventions: coordinates
-- within a block, public-knowledge descriptions, conservative permit
-- info. Apostrophes escaped with '' doubling.

insert into public.locations (
  name, city, state, latitude, longitude, description, access_type, tags,
  permit_required, permit_certainty, permit_notes,
  status, source, rating, quality_score
) values

-- ── Keystone, SD (Mount Rushmore gateway) ────────────────────────────────
('Mount Rushmore National Memorial', 'Keystone', 'SD', 43.8791, -103.4591,
 'The iconic 60-foot granite presidential carvings — Avenue of Flags approach, Grand View Terrace, evening lighting ceremony.',
 'public', array['Iconic','Historic','Mountain'], true, 'likely',
 'NPS commercial photography permit required.',
 'published', 'curated_v1', 4.9, 95),
('Sylvan Lake — Custer State Park', 'Keystone', 'SD', 43.8458, -103.5611,
 'Glacial-blue lake ringed by Black Hills granite — easy lakeside loop, climbable rock formations, the iconic SD Tourism shot.',
 'public', array['Lake','Mountain','Iconic'], true, 'likely',
 'SD State Parks photo permit required for commercial work.',
 'published', 'curated_v1', 4.9, 92),
('Needles Highway', 'Keystone', 'SD', 43.8731, -103.5286,
 '14-mile scenic drive through granite spires — narrow tunnels (some 8-foot-wide), eye-of-the-needle formations.',
 'public', array['Mountain','Outdoor','Iconic'], true, 'likely',
 'SD State Parks photo permit required for commercial work.',
 'published', 'curated_v1', 4.8, 90),

-- ── Custer, SD ────────────────────────────────────────────────────────────
('Custer State Park — Wildlife Loop', 'Custer', 'SD', 43.7142, -103.4356,
 '18-mile drive through open prairie — bison herds, pronghorn, the begging burros, sweeping Black Hills backdrop.',
 'public', array['Outdoor','Mountain','Wildlife'], true, 'likely',
 'SD State Parks photo permit required for commercial photography.',
 'published', 'curated_v1', 4.9, 92),
('Cathedral Spires', 'Custer', 'SD', 43.8542, -103.5500,
 'Granite needle cluster off the Needles Highway — climbers'' destination, cathedral-tall vertical fins.',
 'public', array['Mountain','Outdoor','Iconic'], true, 'likely',
 'SD State Parks photo permit applies.',
 'published', 'curated_v1', 4.7, 87),
('Crazy Horse Memorial', 'Custer', 'SD', 43.8364, -103.6258,
 'In-progress mountain carving (started 1948) of Crazy Horse — currently the world''s largest sculpture in progress, scale impossible to capture.',
 'public', array['Iconic','Historic','Mountain'], true, 'likely',
 'Crazy Horse Memorial Foundation handles commercial photography requests.',
 'published', 'curated_v1', 4.6, 85),

-- ── Wall, SD (Badlands NP gateway) ───────────────────────────────────────
('Badlands NP — Pinnacles Overlook', 'Wall', 'SD', 43.8283, -101.9758,
 'Eroded buttes and pinnacles of striped sediment — sunrise lights the bands fiery orange, mixed-grass prairie below.',
 'public', array['Sunrise','Outdoor','Iconic'], true, 'likely',
 'NPS Badlands commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Badlands NP — Sage Creek Wilderness', 'Wall', 'SD', 43.7775, -102.4192,
 'Wide-open backcountry valley — bison, prairie dogs, vast badlands without crowds.',
 'public', array['Outdoor','Wildlife','Prairie'], true, 'likely',
 'NPS Badlands commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),
('Badlands NP — Door Trail / Window Overlook', 'Wall', 'SD', 43.8508, -101.9292,
 'Paved boardwalk to a "doorway" gap in the formations — most-photographed easy access in the park.',
 'public', array['Outdoor','Iconic','Boardwalk'], true, 'likely',
 'NPS Badlands commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Sioux Falls, SD ───────────────────────────────────────────────────────
('Falls Park', 'Sioux Falls', 'SD', 43.5808, -96.7228,
 'The pink-quartzite cascades of the Big Sioux River right downtown — observation tower, riverside paths, lit at night.',
 'public', array['Waterfall','Park','Iconic'], true, 'likely',
 'Sioux Falls Parks photo permit applies for commercial work.',
 'published', 'curated_v1', 4.8, 90),
('SculptureWalk Downtown', 'Sioux Falls', 'SD', 43.5478, -96.7286,
 '80+ rotating outdoor sculptures lining Phillips Avenue — public art display through the historic downtown core.',
 'public', array['Sculpture','Urban','Street'], false, 'unknown',
 'Public sidewalks; respect storefronts.',
 'published', 'curated_v1', 4.5, 84),
('Big Sioux River Greenway', 'Sioux Falls', 'SD', 43.5394, -96.7100,
 '20+ miles of paved riverside path — pedestrian bridges, mature cottonwoods, cuts straight through downtown.',
 'public', array['River','Park','Outdoor'], false, 'likely',
 'Sioux Falls Parks photo permit applies.',
 'published', 'curated_v1', 4.5, 83),

-- ── Rapid City, SD ────────────────────────────────────────────────────────
('Dinosaur Park', 'Rapid City', 'SD', 44.0828, -103.2444,
 '1936 WPA-era hilltop park — seven concrete dinosaur sculptures, sweeping Rapid City + Black Hills views from the bench at the top.',
 'public', array['Iconic','Outdoor','Overlook'], false, 'unknown',
 'Public park.',
 'published', 'curated_v1', 4.4, 82),
('City of Presidents Statues — Downtown', 'Rapid City', 'SD', 44.0808, -103.2306,
 'Life-size bronze statues of every US president on the downtown corners — outdoor walking gallery covering 6 blocks.',
 'public', array['Sculpture','Urban','Historic'], false, 'unknown',
 'Public sidewalks.',
 'published', 'curated_v1', 4.5, 84),
('Black Hills Aerial Adventures Overlook', 'Rapid City', 'SD', 44.0500, -103.2406,
 'M Hill Trail summit at 3,580 feet — eastern Black Hills overlook, Rapid Valley spread below, Skyline Drive access.',
 'public', array['Overlook','Mountain','Outdoor'], false, 'unknown',
 'Public trail.',
 'published', 'curated_v1', 4.5, 83),

-- ── Deadwood, SD ──────────────────────────────────────────────────────────
('Deadwood Main Street', 'Deadwood', 'SD', 44.3766, -103.7297,
 '1870s gold-rush main street, restored — saloons, brick storefronts, a National Historic Landmark district end-to-end.',
 'public', array['Historic','Western','Street'], false, 'unknown',
 'Public sidewalks; respect storefronts.',
 'published', 'curated_v1', 4.7, 87),
('Mount Moriah Cemetery', 'Deadwood', 'SD', 44.3719, -103.7222,
 'Hilltop cemetery overlooking Deadwood — Wild Bill Hickok and Calamity Jane''s graves, Black Hills panorama.',
 'public', array['Historic','Western','Overlook'], true, 'likely',
 'Deadwood Cemetery handles commercial photography requests.',
 'published', 'curated_v1', 4.5, 84),
('Spearfish Canyon — Bridal Veil Falls', 'Deadwood', 'SD', 44.4717, -103.8356,
 '60-foot waterfall in Spearfish Canyon Scenic Byway — towering limestone cliffs and old-growth spruce all around.',
 'public', array['Waterfall','Canyon','Mountain'], false, 'likely',
 'Black Hills NF photo permit may apply.',
 'published', 'curated_v1', 4.7, 87),

-- ── Medora, ND (Theodore Roosevelt NP gateway) ───────────────────────────
('Painted Canyon Overlook — TRNP', 'Medora', 'ND', 46.8997, -103.3722,
 'Roadside overlook into the multicolored badlands — sediment bands, grassy buttes, the iconic ND landscape shot.',
 'public', array['Iconic','Outdoor','Canyon'], true, 'likely',
 'NPS Theodore Roosevelt commercial photography permit required.',
 'published', 'curated_v1', 4.8, 90),
('Wind Canyon — TRNP', 'Medora', 'ND', 46.9853, -103.5392,
 'Sandstone canyon carved into a U-bend by the Little Missouri River — sunset overlook, the canyon glowing orange.',
 'public', array['Canyon','Sunset','Outdoor'], true, 'likely',
 'NPS Theodore Roosevelt commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),
('Maltese Cross Cabin', 'Medora', 'ND', 46.9156, -103.5247,
 'Theodore Roosevelt''s 1880s ranch cabin — restored log structure preserved in Medora, period interior.',
 'public', array['Historic','Western','Iconic'], true, 'likely',
 'NPS Theodore Roosevelt commercial photography permit required.',
 'published', 'curated_v1', 4.6, 85),

-- ── Fargo, ND ─────────────────────────────────────────────────────────────
('Fargo Theatre Marquee', 'Fargo', 'ND', 46.8772, -96.7892,
 '1926 Art Deco theater on Broadway — neon "FARGO" marquee, restored interior, the iconic main-street shot.',
 'public', array['Architecture','Iconic','Historic'], true, 'unknown',
 'Fargo Theatre handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Hjemkomst Center', 'Fargo', 'ND', 46.8631, -96.7825,
 'Replica 1893 Norwegian stave church + Viking ship — outdoor and indoor, Heritage Center surrounding.',
 'public', array['Architecture','Historic','Iconic'], true, 'likely',
 'HCSCC handles commercial photography requests.',
 'published', 'curated_v1', 4.6, 85),
('Lindenwood Park', 'Fargo', 'ND', 46.8511, -96.7817,
 '113-acre Red River park — riverside paths, a 1930s WPA gazebo, mature cottonwoods, fishing-village feel a block from downtown.',
 'public', array['Park','River','Outdoor'], true, 'likely',
 'Fargo Park District photo permit applies.',
 'published', 'curated_v1', 4.4, 82),

-- ── Bismarck, ND ──────────────────────────────────────────────────────────
('North Dakota State Capitol', 'Bismarck', 'ND', 46.8208, -100.7708,
 '19-story 1934 Art Deco "Skyscraper of the Prairie" — only high-rise capitol, formal grounds, Missouri River horizon to the west.',
 'public', array['Architecture','Historic','Government'], true, 'likely',
 'Capitol staff handles commercial photography permissions.',
 'published', 'curated_v1', 4.6, 86),
('Knife River Indian Villages', 'Bismarck', 'ND', 47.3289, -101.3786,
 'Reconstructed Hidatsa earthen lodges + village floor depressions — Lewis & Clark wintered with Sacagawea here.',
 'public', array['Historic','Outdoor','Iconic'], true, 'likely',
 'NPS commercial photography permit required.',
 'published', 'curated_v1', 4.6, 85),
('Sertoma Park / Missouri Riverside', 'Bismarck', 'ND', 46.7861, -100.8336,
 'Riverside park with the Lewis & Clark Riverboat docking, Sertoma Park''s lit pavilion, sweeping Missouri river views.',
 'public', array['Park','River','Waterfront'], true, 'likely',
 'Bismarck Parks photo permit applies.',
 'published', 'curated_v1', 4.4, 82),

-- ── Omaha, NE ─────────────────────────────────────────────────────────────
('Old Market', 'Omaha', 'NE', 41.2569, -95.9311,
 'Cobblestoned warehouse district — fire-escapes, brick storefronts, art galleries + cafes. The defining Omaha street shot.',
 'public', array['Historic','Urban','Architecture'], false, 'unknown',
 'Public sidewalks; respect storefronts.',
 'published', 'curated_v1', 4.7, 87),
('Bob Kerrey Pedestrian Bridge', 'Omaha', 'NE', 41.2614, -95.9239,
 '3,000-foot S-curving cable-stayed bridge over the Missouri — straddles the Nebraska/Iowa state line, downtown skyline behind.',
 'public', array['Bridge','Skyline','Iconic'], false, 'unknown',
 'Public bridge.',
 'published', 'curated_v1', 4.7, 87),
('Lauritzen Gardens', 'Omaha', 'NE', 41.2367, -95.9214,
 '100-acre botanical garden — Victorian Garden, Children''s Garden, century-old oaks, Marjorie K. Daugherty Conservatory.',
 'public', array['Garden','Architecture','Outdoor'], true, 'likely',
 'Lauritzen handles commercial photography permits.',
 'published', 'curated_v1', 4.7, 88),

-- ── Lincoln, NE ───────────────────────────────────────────────────────────
('Nebraska State Capitol', 'Lincoln', 'NE', 40.8083, -96.6997,
 '1932 Art Deco-Gothic capitol — 400-foot tower with a gold-domed Sower statue on top, intricate murals + mosaics inside.',
 'public', array['Architecture','Historic','Iconic'], true, 'likely',
 'Capitol staff handles commercial photography permissions.',
 'published', 'curated_v1', 4.8, 89),
('Sunken Gardens', 'Lincoln', 'NE', 40.8036, -96.6792,
 '1.5-acre formal garden — annual themed plantings (30,000+ plants), a tiered reflecting pool, the classic ND garden setting.',
 'public', array['Garden','Outdoor','Iconic'], true, 'likely',
 'Lincoln Parks permit required for commercial photography.',
 'published', 'curated_v1', 4.7, 87),
('Historic Haymarket District', 'Lincoln', 'NE', 40.8175, -96.7106,
 'Restored 19th-century warehouse district — exposed brick, red awnings, the Iron Horse Park railroad statue.',
 'public', array['Historic','Urban','Architecture'], false, 'unknown',
 'Public sidewalks.',
 'published', 'curated_v1', 4.5, 84),

-- ── Scottsbluff, NE (Western NE / Oregon Trail) ──────────────────────────
('Scotts Bluff National Monument', 'Scottsbluff', 'NE', 41.8364, -103.7080,
 '800-foot bluff over the North Platte — wagon-train landmark, paved summit road, prairie panorama from the top.',
 'public', array['Outdoor','Historic','Iconic'], true, 'likely',
 'NPS commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),
('Chimney Rock NHS', 'Scottsbluff', 'NE', 41.7022, -103.3464,
 'Volcanic rock spire visible 30 miles away — pioneer-trail icon mentioned in 600+ emigrant journals.',
 'public', array['Iconic','Historic','Outdoor'], true, 'likely',
 'NE State Historical Society handles commercial photography requests.',
 'published', 'curated_v1', 4.6, 85),
('North Platte River Valley Overlook', 'Scottsbluff', 'NE', 41.8319, -103.7242,
 'Saddle Rock Trail to the bluff''s back side — wide prairie expanding to the horizon, perfect western Nebraska shot.',
 'public', array['Overlook','Outdoor','Prairie'], false, 'likely',
 'NPS Scotts Bluff commercial photography permit may apply.',
 'published', 'curated_v1', 4.5, 84),

-- ── Fredericksburg, TX (Hill Country) ─────────────────────────────────────
('Enchanted Rock SNA', 'Fredericksburg', 'TX', 30.5061, -98.8194,
 '425-foot pink-granite pluton — climbable summit dome, sweeping Texas Hill Country panorama, popular for elopements.',
 'public', array['Mountain','Outdoor','Iconic'], true, 'likely',
 'TX Parks & Wildlife photo permit required for commercial work.',
 'published', 'curated_v1', 4.8, 90),
('Main Street Fredericksburg', 'Fredericksburg', 'TX', 30.2750, -98.8722,
 'Restored 1840s German-Texan limestone storefronts — wide main street, beer gardens, Sunday Houses lining side streets.',
 'public', array['Historic','Architecture','Street'], false, 'unknown',
 'Public sidewalks; respect storefronts.',
 'published', 'curated_v1', 4.6, 85),
('Wildseed Farms', 'Fredericksburg', 'TX', 30.2767, -98.7522,
 'Largest working wildflower farm in the US — bluebonnets in spring (March-April), poppies + sunflowers all summer.',
 'public', array['Garden','Outdoor','Wildflowers'], true, 'likely',
 'Wildseed Farms handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),

-- ── Marfa, TX ─────────────────────────────────────────────────────────────
('Prada Marfa', 'Marfa', 'TX', 30.6033, -104.5681,
 'Permanent art installation — fake Prada storefront on a remote highway 35 miles from Marfa. The internet''s favorite Texas photo.',
 'public', array['Iconic','Desert','Architecture'], false, 'unknown',
 'Public roadside; respect the installation.',
 'published', 'curated_v1', 4.7, 88),
('Hotel Paisano', 'Marfa', 'TX', 30.3094, -104.0228,
 '1930 Spanish Colonial Revival hotel where Liz Taylor + Rock Hudson stayed during "Giant" — courtyard, period bar, the iconic Marfa stay.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Hotel Paisano handles commercial photography requests.',
 'published', 'curated_v1', 4.6, 85),
('Marfa Lights Viewing Area', 'Marfa', 'TX', 30.3108, -104.0103,
 'Officially designated overlook for the unexplained Marfa lights — Chinati Mountains horizon, dark-sky desert at night.',
 'public', array['Desert','Outdoor','Night'], false, 'unknown',
 'Public roadside park.',
 'published', 'curated_v1', 4.4, 82),

-- ── Wimberley, TX (Hill Country) ──────────────────────────────────────────
('Jacob''s Well', 'Wimberley', 'TX', 30.0344, -98.1267,
 '12-foot-wide, 100-foot-deep artesian spring — crystal-clear blue water, limestone rim, swimming by reservation in summer.',
 'public', array['Outdoor','Iconic','Spring'], true, 'likely',
 'Hays County Parks reservation + photo permit required.',
 'published', 'curated_v1', 4.8, 89),
('Blue Hole Park', 'Wimberley', 'TX', 30.0006, -98.0911,
 'Cypress-lined Cypress Creek swimming hole — turquoise pools, rope swings, the iconic Hill Country swim spot.',
 'public', array['River','Outdoor','Beach'], true, 'likely',
 'Wimberley Parks photo permit applies; reservations in summer.',
 'published', 'curated_v1', 4.7, 87),
('Hamilton Pool Preserve', 'Wimberley', 'TX', 30.3417, -98.1267,
 'Collapsed grotto with a 50-foot waterfall into a turquoise pool — limestone overhang, ferns, the most-photographed swimming hole in TX.',
 'public', array['Waterfall','Iconic','Outdoor'], true, 'likely',
 'Travis County Parks reservation + photo permit required.',
 'published', 'curated_v1', 4.9, 92),

-- ── Terlingua / Big Bend, TX ──────────────────────────────────────────────
('Santa Elena Canyon — Big Bend NP', 'Terlingua', 'TX', 29.1681, -103.6086,
 '1,500-foot-tall Rio Grande canyon — Texas on one side, Mexico on the other, a 1.7-mile out-and-back trail puts you under the cliffs.',
 'public', array['Canyon','River','Iconic'], true, 'likely',
 'NPS Big Bend commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),
('Lost Mine Trail', 'Terlingua', 'TX', 29.2772, -103.2806,
 '4.8-mile Chisos Mountains hike — Mexican drop-leaf pines, sweeping desert + Sierra del Carmen views from the top.',
 'public', array['Mountain','Hike','Outdoor'], true, 'likely',
 'NPS Big Bend commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),
('Chisos Basin Window View', 'Terlingua', 'TX', 29.2706, -103.3000,
 'Sunset framed in the V-shaped notch of the Chisos Mountains — the iconic Big Bend shot, easy access from the lodge.',
 'public', array['Mountain','Sunset','Iconic'], true, 'likely',
 'NPS Big Bend commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),

-- ── Lancaster, PA ─────────────────────────────────────────────────────────
('Central Market', 'Lancaster', 'PA', 40.0394, -76.3056,
 '1889 brick farmers'' market — oldest continuously-operated public market in the US, towering vendor stalls, German-Pennsylvania textures.',
 'public', array['Historic','Architecture','Indoor'], true, 'likely',
 'Lancaster Central Market handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Amish Countryside — Strasburg', 'Lancaster', 'PA', 40.0144, -76.1839,
 'Patchwork farmlands, horse-drawn buggies, white farmhouses + red barns — but respect Amish privacy: no portraits of identifiable Amish people.',
 'public', array['Outdoor','Historic','Rural'], false, 'unknown',
 'Public roadways; do NOT photograph Amish individuals — religious belief against being depicted.',
 'published', 'curated_v1', 4.8, 89),
('Strasburg Rail Road', 'Lancaster', 'PA', 40.0006, -76.1606,
 '1832 steam railroad — running passenger trains, period stations, working steam engines for railfan photographers.',
 'public', array['Historic','Iconic','Industrial'], true, 'likely',
 'Strasburg Rail Road handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),

-- ── Hilton Head, SC ───────────────────────────────────────────────────────
('Harbour Town Lighthouse', 'Hilton Head', 'SC', 32.1389, -80.8128,
 '93-foot red-and-white-banded lighthouse at Sea Pines marina — the iconic Hilton Head shot, marina + harbor framing.',
 'public', array['Lighthouse','Coastal','Iconic'], true, 'likely',
 'Sea Pines Resort handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Coligny Beach', 'Hilton Head', 'SC', 32.1747, -80.7517,
 'Wide flat Atlantic beach — packed sand at low tide for endless sweeping shots, sea oats on the dunes behind.',
 'public', array['Beach','Coastal','Iconic'], true, 'likely',
 'Hilton Head beach commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),
('Audubon Newhall Preserve', 'Hilton Head', 'SC', 32.1786, -80.7642,
 '50-acre maritime forest — Spanish-moss live oaks, palmetto undergrowth, peaceful Lowcountry setting away from the beach crowds.',
 'public', array['Forest','Outdoor','Tropical'], false, 'unknown',
 'Public preserve; respect trails.',
 'published', 'curated_v1', 4.5, 84),

-- ── Beaufort, SC ──────────────────────────────────────────────────────────
('Bay Street Historic District', 'Beaufort', 'SC', 32.4317, -80.6697,
 'Antebellum mansions on Bay Street facing the Beaufort River — Spanish-moss live oaks, white columns, brick walks.',
 'public', array['Historic','Architecture','Waterfront'], false, 'unknown',
 'Public sidewalks; respect private homes.',
 'published', 'curated_v1', 4.7, 87),
('Hunting Island State Park — Lighthouse', 'Beaufort', 'SC', 32.3719, -80.4458,
 '1875 cast-iron lighthouse on a barrier island — boneyard beach (dead trees on sand), maritime forest, climbable to the top.',
 'public', array['Lighthouse','Beach','Iconic'], true, 'likely',
 'SC State Parks photo permit required.',
 'published', 'curated_v1', 4.8, 89),
('Boneyard Beach — Hunting Island', 'Beaufort', 'SC', 32.3675, -80.4378,
 'Beach littered with dead-tree skeletons — oaks toppled by erosion, photogenic anywhere, especially silver at sunset.',
 'public', array['Beach','Iconic','Coastal'], true, 'likely',
 'SC State Parks photo permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Galena, IL ────────────────────────────────────────────────────────────
('Main Street Galena', 'Galena', 'IL', 42.4153, -90.4292,
 'Untouched 1850s lead-mining-boom main street — 85% of the buildings predate 1900, brick + stone storefronts, hilltop staircases.',
 'public', array['Historic','Architecture','Street'], false, 'unknown',
 'Public sidewalks; respect storefronts.',
 'published', 'curated_v1', 4.8, 89),
('Belvedere Mansion', 'Galena', 'IL', 42.4156, -90.4247,
 '1857 Italianate mansion — period interior used as a Galena history museum, formal gardens, panoramic Galena River views.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Belvedere Mansion handles commercial photography requests.',
 'published', 'curated_v1', 4.6, 85),
('Horseshoe Mound Preserve', 'Galena', 'IL', 42.4214, -90.4117,
 'Hilltop overlook above Galena — sweeping Driftless-region views, prairie restoration, Mississippi River bluffs in the distance.',
 'public', array['Overlook','Park','Outdoor'], false, 'unknown',
 'Public preserve.',
 'published', 'curated_v1', 4.6, 85),

-- ── Iowa City, IA ─────────────────────────────────────────────────────────
('Old Capitol Building', 'Iowa City', 'IA', 41.6608, -91.5358,
 '1842 Greek Revival capitol — Iowa''s first state capitol, gold dome, U of Iowa Pentacrest centerpiece.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'University of Iowa handles commercial photography on campus.',
 'published', 'curated_v1', 4.6, 85),
('Pentacrest', 'Iowa City', 'IA', 41.6608, -91.5378,
 'Five Beaux-Arts academic buildings clustered around the Old Capitol — limestone facades, tree-shaded lawns.',
 'public', array['Architecture','Campus','Historic'], true, 'unknown',
 'University of Iowa for commercial photography on Pentacrest.',
 'published', 'curated_v1', 4.5, 84),
('Iowa River Greenbelt', 'Iowa City', 'IA', 41.6597, -91.5403,
 'Riverside trails through downtown — Iowa River, footbridges, wooded segments, university crew rowing in early mornings.',
 'public', array['River','Park','Outdoor'], false, 'likely',
 'Iowa City Parks photo permit applies.',
 'published', 'curated_v1', 4.4, 82),

-- ── Decorah, IA ───────────────────────────────────────────────────────────
('Dunning''s Spring', 'Decorah', 'IA', 43.3128, -91.7836,
 '200-foot waterfall in a forest setting — Decorah''s defining outdoor spot, easy paved access, photogenic year-round.',
 'public', array['Waterfall','Forest','Outdoor'], true, 'likely',
 'Decorah Parks photo permit applies for commercial work.',
 'published', 'curated_v1', 4.7, 87),
('Vesterheim Norwegian-American Museum', 'Decorah', 'IA', 43.3033, -91.7894,
 'Largest Norwegian-American museum in the world — historic stave-style log buildings, period homes, Norwegian heritage in northeast Iowa.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Vesterheim handles commercial photography requests.',
 'published', 'curated_v1', 4.6, 85),
('Phelps Park', 'Decorah', 'IA', 43.3047, -91.7811,
 'Limestone-cliff park overlooking the Upper Iowa River — bluff-top picnic areas, summer-green tree canopy, autumn color.',
 'public', array['Park','Overlook','Outdoor'], true, 'likely',
 'Decorah Parks photo permit applies.',
 'published', 'curated_v1', 4.5, 84),

-- ── Holland, MI ───────────────────────────────────────────────────────────
('Big Red Lighthouse', 'Holland', 'MI', 42.7728, -86.2125,
 '1872 wooden lighthouse painted bright red on a sand spit at the harbor entrance — Lake Michigan beyond, dunes around.',
 'public', array['Lighthouse','Iconic','Coastal'], true, 'likely',
 'Holland State Park photo permit required.',
 'published', 'curated_v1', 4.8, 89),
('Windmill Island Gardens', 'Holland', 'MI', 42.7964, -86.0939,
 '1761 working Dutch windmill ("De Zwaan") in a 36-acre gardens — tulip beds (April-May for Tulip Time), formal Dutch gardens year-round.',
 'public', array['Garden','Iconic','Architecture'], true, 'likely',
 'Holland Parks handles commercial photography for Windmill Island.',
 'published', 'curated_v1', 4.7, 88),
('Holland State Park Beach', 'Holland', 'MI', 42.7733, -86.2069,
 'Lake Michigan dunes + sand — pier walks, Big Red Lighthouse to the south, sunset over open water.',
 'public', array['Beach','Coastal','Sunset'], true, 'likely',
 'MI State Parks photo permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Duluth, MN ────────────────────────────────────────────────────────────
('Aerial Lift Bridge', 'Duluth', 'MN', 46.7794, -92.0925,
 '1905 vertical-lift bridge over the Duluth ship canal — opens for ore boats, Lake Superior beyond. The defining Duluth shot.',
 'public', array['Bridge','Iconic','Coastal'], false, 'unknown',
 'Public bridge.',
 'published', 'curated_v1', 4.8, 89),
('Canal Park', 'Duluth', 'MN', 46.7806, -92.0942,
 'Restored warehouse-district waterfront — brick + ironwork, Lake Superior seawall, the lift bridge a half-block away.',
 'public', array['Historic','Waterfront','Architecture'], false, 'unknown',
 'Public park.',
 'published', 'curated_v1', 4.7, 87),
('Glensheen Mansion', 'Duluth', 'MN', 46.8181, -92.0531,
 '1908 Jacobean Revival mansion on Lake Superior — formal gardens, lakefront pier, the most-photographed historic house in MN.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Glensheen handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 88),

-- ── Astoria, OR ───────────────────────────────────────────────────────────
('Astoria Column', 'Astoria', 'OR', 46.1822, -123.8044,
 '125-foot 1926 monument painted with Oregon-history murals — climb to the top for sweeping Columbia River + Pacific views.',
 'public', array['Iconic','Architecture','Overlook'], true, 'likely',
 'Astoria Column handles commercial photography requests.',
 'published', 'curated_v1', 4.8, 89),
('Astoria-Megler Bridge Overlook', 'Astoria', 'OR', 46.2014, -123.8511,
 '4.1-mile cantilever bridge — longest continuous truss in North America, dramatically arching over the Columbia River mouth.',
 'public', array['Bridge','Coastal','Iconic'], false, 'unknown',
 'Public viewpoints from Astoria''s riverfront.',
 'published', 'curated_v1', 4.7, 87),
('Cannery Pier Hotel District', 'Astoria', 'OR', 46.1925, -123.8400,
 'Restored cannery on a 600-foot pier into the Columbia — sea-lion docks, river-traffic shipping channel right in front.',
 'public', array['Waterfront','Historic','Industrial'], false, 'unknown',
 'Public boardwalks.',
 'published', 'curated_v1', 4.5, 84),

-- ── La Conner, WA ─────────────────────────────────────────────────────────
('Skagit Valley Tulip Fields', 'La Conner', 'WA', 48.4500, -122.4467,
 'April tulip-bloom fields — Roozengaarde + Tulip Town, rows of pink/red/yellow extending to Mount Baker''s horizon.',
 'public', array['Garden','Wildflowers','Iconic'], true, 'likely',
 'Tulip Festival farms charge photo permit fees during bloom season.',
 'published', 'curated_v1', 4.9, 92),
('Rainbow Bridge', 'La Conner', 'WA', 48.3911, -122.4972,
 '1957 red-orange arch bridge over Swinomish Channel — La Conner''s defining downtown landmark, mountain views beyond.',
 'public', array['Bridge','Iconic','Waterfront'], false, 'unknown',
 'Public bridge.',
 'published', 'curated_v1', 4.7, 87),
('La Conner Waterfront', 'La Conner', 'WA', 48.3914, -122.4958,
 'Wooden boardwalks and stilt-houses on the Swinomish Channel — fishing-village atmosphere, mountain backdrop.',
 'public', array['Waterfront','Coastal','Architecture'], false, 'unknown',
 'Public waterfront.',
 'published', 'curated_v1', 4.6, 85),

-- ── Whidbey Island / Coupeville, WA ───────────────────────────────────────
('Deception Pass Bridge', 'Coupeville', 'WA', 48.4067, -122.6447,
 '976-foot 1935 steel-truss bridge over a deep saltwater channel — drone-style aerial shots of the dramatic gap.',
 'public', array['Bridge','Iconic','Coastal'], false, 'likely',
 'Deception Pass SP photo permit required for commercial work.',
 'published', 'curated_v1', 4.9, 92),
('Coupeville Wharf', 'Coupeville', 'WA', 48.2189, -122.6850,
 'Working pier on Penn Cove — Olympics across Puget Sound, the historic 1905 Captain Whidbey Inn on the bluff.',
 'public', array['Waterfront','Historic','Coastal'], false, 'unknown',
 'Public wharf.',
 'published', 'curated_v1', 4.7, 87),
('Ebey''s Landing', 'Coupeville', 'WA', 48.1956, -122.7117,
 'Bluff-top hike along Whidbey''s west coast — Olympic Mountains across the Strait, prairie meeting open ocean.',
 'public', array['Coastal','Hike','Outdoor'], true, 'likely',
 'NPS Ebey''s Landing National Historical Reserve commercial photography permit required.',
 'published', 'curated_v1', 4.8, 90);
