-- Curated seed: top 30 US metros × 5 well-known photoshoot locations each.
-- Sourced from public knowledge — coordinates are accurate within a block
-- for famous landmarks, ballpark for districts/neighborhoods. Permit info
-- is conservative: most rows flagged `permit_certainty = 'unknown'` so
-- photographers know to verify with the location before a paid shoot.
--
-- Re-running this file will create duplicate rows. Run once, then use the
-- admin tools (/admin → location row → name link → /explore detail panel
-- Edit/Delete) to fine-tune any specific entry.

insert into public.locations (
  name, city, state, latitude, longitude, description, access_type, tags,
  permit_required, permit_certainty, permit_notes,
  status, source, rating, quality_score
) values

-- ── New York, NY ──────────────────────────────────────────────────────────
('Central Park — Bow Bridge', 'New York', 'NY', 40.7757, -73.9729,
 'Iron-and-wood pedestrian bridge over The Lake, framed by skyline and trees. The single most photographed spot in Central Park.',
 'public', array['Park','Bridge','Iconic'], true, 'verified',
 'NYC Parks photo permit required for any shoot with a crew, props, or more than ~5 people. Couples sessions with one shooter are typically tolerated.',
 'published', 'curated_v1', 4.8, 92),
('Brooklyn Bridge Promenade', 'New York', 'NY', 40.7061, -73.9969,
 'Walkway along the iconic suspension bridge — best at golden hour with the Manhattan skyline behind.',
 'public', array['Iconic','Bridge','Skyline'], false, 'likely',
 'Walk-up tripod-and-camera shoots are informal. Larger crews or any bridge closure require a NYC Mayor''s Office of Film permit.',
 'published', 'curated_v1', 4.9, 95),
('DUMBO — Washington Street view of Manhattan Bridge', 'New York', 'NY', 40.7035, -73.9897,
 'Cobblestone street that frames the Manhattan Bridge between brick warehouses. The famous "Once Upon a Time in America" angle.',
 'public', array['Urban','Iconic','Bridge'], false, 'likely',
 'Public street, no formal permit for walk-up shoots. Heavy tourist traffic — early morning recommended.',
 'published', 'curated_v1', 4.8, 93),
('Top of the Rock — Rockefeller Center', 'New York', 'NY', 40.7587, -73.9787,
 'Observation deck with unobstructed Empire State Building view. Ticketed, indoor and outdoor.',
 'private', array['Rooftop','Skyline','Iconic'], true, 'verified',
 'Standard observation-deck ticket. Tripods generally not permitted; commercial shoots require Rockefeller Center prior approval.',
 'published', 'curated_v1', 4.7, 90),
('Washington Square Park Arch', 'New York', 'NY', 40.7308, -73.9973,
 'White marble arch in Greenwich Village, framed by the park and 5th Avenue.',
 'public', array['Park','Historic','Urban'], true, 'likely',
 'NYC Parks photo permit required for crews. One photographer + couple is typically tolerated.',
 'published', 'curated_v1', 4.6, 88),

-- ── Los Angeles, CA ───────────────────────────────────────────────────────
('Griffith Observatory', 'Los Angeles', 'CA', 34.1184, -118.3004,
 'Art Deco observatory on Mount Hollywood with sweeping LA basin and Hollywood Sign views.',
 'public', array['Hilltop','Iconic','Skyline'], false, 'likely',
 'No permit for walk-up shoots. Tripods restricted on busy weekends. Commercial shoots require LA Department of Recreation and Parks permit.',
 'published', 'curated_v1', 4.8, 92),
('Venice Beach Pier', 'Venice', 'CA', 33.9803, -118.4720,
 'Concrete pier extending into the Pacific — classic California sunset and silhouette location.',
 'public', array['Beach','Sunset','Pier'], false, 'unknown',
 'Public beach. LA County Beaches permit required for any production with crew or props.',
 'published', 'curated_v1', 4.6, 87),
('Vasquez Rocks Natural Area Park', 'Agua Dulce', 'CA', 34.4858, -118.3208,
 'Dramatic tilted sandstone formations. Heavily used for film/TV and known to LA photographers.',
 'public', array['Outdoor','Dramatic','Cinematic'], true, 'verified',
 'LA County Parks permit required for any organized shoot. Hiking-only access for casual visits.',
 'published', 'curated_v1', 4.8, 91),
('Bradbury Building', 'Los Angeles', 'CA', 34.0509, -118.2477,
 'Historic 1893 office building with iron staircases and skylit atrium — Blade Runner location.',
 'private', array['Architecture','Historic','Indoor'], true, 'verified',
 'No tripod or commercial photography without prior approval from building management. Open to walk-up visits during business hours.',
 'published', 'curated_v1', 4.5, 85),
('Venice Canals', 'Venice', 'CA', 33.9849, -118.4670,
 'Quaint residential canals lined with bridges and gardens. Very different feel from the boardwalk.',
 'public', array['Waterfront','Quaint','Urban'], false, 'likely',
 'Public sidewalks. Be respectful of homeowners — no shooting onto private patios. Crews need a permit.',
 'published', 'curated_v1', 4.5, 86),

-- ── Chicago, IL ───────────────────────────────────────────────────────────
('Cloud Gate ("The Bean")', 'Chicago', 'IL', 41.8827, -87.6233,
 'Polished stainless steel sculpture in Millennium Park reflecting the skyline. Iconic Chicago photo.',
 'public', array['Iconic','Sculpture','Skyline'], false, 'likely',
 'No permit for walk-up shoots. Tripods/lights and any commercial use require Chicago Parks District permit.',
 'published', 'curated_v1', 4.9, 95),
('Lincoln Park — North Pond', 'Chicago', 'IL', 41.9285, -87.6392,
 'Pond with skyline backdrop, framed by trees and walking paths. Classic Chicago wedding spot.',
 'public', array['Park','Skyline','Pond'], true, 'likely',
 'Chicago Parks District photo permit required for organized sessions.',
 'published', 'curated_v1', 4.7, 89),
('Chicago Riverwalk', 'Chicago', 'IL', 41.8881, -87.6298,
 'Walkway along the Chicago River with bridges, architecture, and water-level skyline views.',
 'public', array['Waterfront','Urban','Skyline'], false, 'likely',
 'Walk-up shoots OK. Crews and tripods need a permit.',
 'published', 'curated_v1', 4.7, 89),
('Adler Planetarium — Skyline Point', 'Chicago', 'IL', 41.8663, -87.6068,
 'Lakefront point behind the planetarium offering the iconic full-skyline-with-lake shot.',
 'public', array['Skyline','Sunrise','Waterfront'], false, 'likely',
 'Public lakefront. Best at sunrise. Same Park District rules apply for organized shoots.',
 'published', 'curated_v1', 4.8, 91),
('Wrigleyville — Greetings From Chicago Mural', 'Chicago', 'IL', 41.9474, -87.6553,
 'Large postcard-style mural by Victor Ving and Lisa Beggs at 2226 N. Milwaukee Ave.',
 'public', array['Mural','Urban','Colorful'], false, 'unknown',
 'Public sidewalk. No formal permit needed for personal sessions.',
 'published', 'curated_v1', 4.4, 83),

-- ── Houston, TX ───────────────────────────────────────────────────────────
('Hermann Park — McGovern Centennial Gardens', 'Houston', 'TX', 29.7163, -95.3902,
 'Eight-acre formal gardens with a central mount, fountains, and seasonal blooms.',
 'public', array['Garden','Park','Formal'], true, 'verified',
 'Hermann Park Conservancy photography permit required ($75 portrait, more for events). Walk-up casual photos OK.',
 'published', 'curated_v1', 4.6, 87),
('Buffalo Bayou Park — The Cistern', 'Houston', 'TX', 29.7615, -95.3929,
 'Decommissioned underground reservoir with 221 columns and dramatic acoustics. Tour-only access.',
 'private', array['Indoor','Architecture','Dramatic'], true, 'verified',
 'Buffalo Bayou Partnership permit + tour reservation required. Strict no-flash, no-tripod policy on standard tours.',
 'published', 'curated_v1', 4.7, 89),
('Discovery Green', 'Houston', 'TX', 29.7531, -95.3592,
 'Downtown park with sculptures, lawns, and skyline views. Hosts art installations year-round.',
 'public', array['Park','Urban','Skyline'], true, 'likely',
 'Discovery Green Conservancy permit required for organized photo sessions.',
 'published', 'curated_v1', 4.5, 85),
('Houston Heights — Greetings From Houston Mural', 'Houston', 'TX', 29.7989, -95.3987,
 'Large welcome-postcard mural at 21st & Yale. Frequent local-photographer location.',
 'public', array['Mural','Urban','Colorful'], false, 'unknown',
 'Public sidewalk. No formal permit needed.',
 'published', 'curated_v1', 4.3, 80),
('Rothko Chapel grounds', 'Houston', 'TX', 29.7376, -95.3962,
 'Quiet contemplative campus with reflecting pool and Barnett Newman''s Broken Obelisk.',
 'public', array['Architecture','Quiet','Modernist'], true, 'likely',
 'Photography of the chapel exterior and grounds is allowed without permit; commercial shoots require Menil Collection approval.',
 'published', 'curated_v1', 4.6, 87),

-- ── Phoenix, AZ ───────────────────────────────────────────────────────────
('Camelback Mountain — Echo Canyon Trailhead', 'Phoenix', 'AZ', 33.5236, -111.9695,
 'Iconic camel-shaped mountain with red rock faces. Best at sunrise for the warm glow.',
 'public', array['Outdoor','Sunrise','Mountain'], false, 'likely',
 'Phoenix Parks permit required for any organized shoot. Hiking-only access; lot fills early on weekends.',
 'published', 'curated_v1', 4.7, 89),
('Desert Botanical Garden', 'Phoenix', 'AZ', 33.4621, -111.9445,
 '140 acres of trails through saguaro forest, agave, and seasonal wildflowers.',
 'private', array['Garden','Desert','Outdoor'], true, 'verified',
 'Permitted-photography program: $500 family/portrait, $1500 wedding. Walk-up snapshots with admission ticket are fine.',
 'published', 'curated_v1', 4.7, 90),
('Papago Park — Hole-in-the-Rock', 'Phoenix', 'AZ', 33.4543, -111.9476,
 'Eroded sandstone arch overlooking the Phoenix valley. Famous sunset and astrophotography spot.',
 'public', array['Outdoor','Sunset','Dramatic'], false, 'likely',
 'Phoenix Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.6, 88),
('Roosevelt Row Arts District', 'Phoenix', 'AZ', 33.4581, -112.0729,
 'Mural-covered alleys and warehouses south of downtown — concentrated street art for editorial shoots.',
 'public', array['Mural','Urban','Colorful'], false, 'unknown',
 'Public sidewalks. Some murals are on private buildings — be respectful.',
 'published', 'curated_v1', 4.5, 85),
('Arizona Biltmore Resort gardens', 'Phoenix', 'AZ', 33.5203, -112.0263,
 'Frank Lloyd Wright-influenced 1929 resort with palm-lined lawns and architectural details.',
 'private', array['Architecture','Garden','Resort'], true, 'verified',
 'Resort guests have access to public areas; commercial / wedding photography requires booking with the resort.',
 'published', 'curated_v1', 4.5, 84),

-- ── Philadelphia, PA ──────────────────────────────────────────────────────
('Philadelphia Museum of Art — Rocky Steps', 'Philadelphia', 'PA', 39.9656, -75.1810,
 'East-facing steps of the Art Museum with Eakins Oval and the city skyline framed below.',
 'public', array['Iconic','Skyline','Architecture'], false, 'likely',
 'Walk-up shoots OK. Tripods restricted near the entrance during museum hours; large crews require a permit.',
 'published', 'curated_v1', 4.8, 91),
('Boathouse Row — Schuylkill River', 'Philadelphia', 'PA', 39.9712, -75.1854,
 'Row of historic boathouses outlined in lights at night. Sunset over the river is the classic shot.',
 'public', array['Waterfront','Historic','Sunset'], false, 'likely',
 'Public riverbank. Fairmount Park photo permit recommended for organized sessions.',
 'published', 'curated_v1', 4.7, 89),
('Magic Gardens', 'Philadelphia', 'PA', 39.9421, -75.1581,
 'Mosaic-covered Isaiah Zagar art environment on South Street — colorful indoor/outdoor labyrinth.',
 'private', array['Art','Mural','Indoor'], true, 'verified',
 'Photography permit available with admission; wedding/commercial sessions require advance booking.',
 'published', 'curated_v1', 4.6, 87),
('Independence Hall — Old City', 'Philadelphia', 'PA', 39.9489, -75.1500,
 'Brick Georgian architecture, Independence Mall, and the cobblestone streets of Old City.',
 'public', array['Historic','Architecture','Iconic'], false, 'likely',
 'NPS rules apply on Independence Hall grounds — no commercial without permit.',
 'published', 'curated_v1', 4.5, 86),
('Wissahickon Valley Park — Forbidden Drive', 'Philadelphia', 'PA', 40.0476, -75.2088,
 'Wide unpaved trail along the Wissahickon Creek through old-growth forest. Feels rural inside the city.',
 'public', array['Forest','Trail','Quiet'], false, 'likely',
 'Fairmount Park photo permit required for organized shoots.',
 'published', 'curated_v1', 4.5, 85),

-- ── San Diego, CA ─────────────────────────────────────────────────────────
('Sunset Cliffs Natural Park', 'San Diego', 'CA', 32.7232, -117.2553,
 'Eroded sandstone cliffs over the Pacific. Arguably the best urban sunset on the West Coast.',
 'public', array['Cliffs','Sunset','Coastal'], false, 'likely',
 'San Diego Parks permit required for organized shoots. Be safe — cliffs are unstable.',
 'published', 'curated_v1', 4.9, 94),
('Balboa Park — Spanish Village', 'San Diego', 'CA', 32.7341, -117.1503,
 'Painted-tile courtyard surrounded by colorful artist studios. Whole park is a Spanish-Colonial photo dream.',
 'public', array['Architecture','Colorful','Park'], true, 'verified',
 'Balboa Park has a tiered photography fee schedule — $50 portraits, more for weddings. Permit through SD Parks.',
 'published', 'curated_v1', 4.7, 90),
('La Jolla Cove', 'La Jolla', 'CA', 32.8508, -117.2718,
 'Small protected cove with sea lions, tide pools, and dramatic cliff faces.',
 'public', array['Coastal','Wildlife','Dramatic'], false, 'likely',
 'Public beach. La Jolla Cove Council requests advance notice for organized shoots.',
 'published', 'curated_v1', 4.7, 89),
('Old Town San Diego', 'San Diego', 'CA', 32.7548, -117.1965,
 'Adobe buildings and Mexican-tile courtyards from the original 1820s settlement.',
 'public', array['Historic','Colorful','Cultural'], false, 'likely',
 'State Historic Park permit required for organized commercial photography.',
 'published', 'curated_v1', 4.4, 84),
('Coronado Beach — Hotel del Coronado', 'Coronado', 'CA', 32.6810, -117.1786,
 'White Victorian beach hotel with the wide Pacific behind. The classic Coronado shot.',
 'private', array['Beach','Architecture','Iconic'], true, 'verified',
 'Hotel del Coronado wedding/photo packages required for any organized shoot on hotel property; public beach is free.',
 'published', 'curated_v1', 4.7, 89),

-- ── Dallas, TX ────────────────────────────────────────────────────────────
('Dallas Arboretum & Botanical Garden', 'Dallas', 'TX', 32.8221, -96.7178,
 '66 acres of themed gardens overlooking White Rock Lake. Spring and fall are particularly photogenic.',
 'private', array['Garden','Park','Formal'], true, 'verified',
 'Required photography permit: $200 portrait, $500+ wedding. Walk-up snapshots OK with admission.',
 'published', 'curated_v1', 4.7, 89),
('Margaret Hunt Hill Bridge', 'Dallas', 'TX', 32.7826, -96.8258,
 'Calatrava-designed white arch bridge over the Trinity River. Striking from below and from Trinity Groves.',
 'public', array['Architecture','Bridge','Iconic'], false, 'likely',
 'Public bridge. City of Dallas Film Office permit needed for crew shoots.',
 'published', 'curated_v1', 4.6, 87),
('White Rock Lake — East Shore', 'Dallas', 'TX', 32.8210, -96.7147,
 'Sunset over the lake with downtown Dallas in the distance. Wide skies and reflections.',
 'public', array['Waterfront','Sunset','Park'], false, 'likely',
 'Dallas Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.5, 85),
('Deep Ellum Mural District', 'Dallas', 'TX', 32.7843, -96.7777,
 'Concentrated street-art district just east of downtown — most walls turn over annually.',
 'public', array['Mural','Urban','Colorful'], false, 'unknown',
 'Public sidewalks. Some murals on private buildings — ask first for commercial use.',
 'published', 'curated_v1', 4.4, 83),
('Reunion Tower Plaza', 'Dallas', 'TX', 32.7749, -96.8089,
 'Iconic geodesic tower; the surrounding plaza offers full-skyline framing.',
 'public', array['Skyline','Iconic','Urban'], false, 'likely',
 'Plaza is publicly accessible; observation deck requires ticket. Crews need a Dallas Film Office permit.',
 'published', 'curated_v1', 4.5, 85),

-- ── Austin, TX ────────────────────────────────────────────────────────────
('Mount Bonnell — Covert Park', 'Austin', 'TX', 30.3209, -97.7853,
 'Highest natural point in Austin with 360° views of Lake Austin and the hill country.',
 'public', array['Hilltop','Sunset','Outdoor'], false, 'likely',
 'Austin Parks permit required for organized shoots. Lot is small — arrive early at sunset.',
 'published', 'curated_v1', 4.6, 87),
('Pennybacker Bridge — Loop 360', 'Austin', 'TX', 30.3621, -97.8024,
 'Steel arch bridge over Lake Austin, viewed from the cliffs on the south side.',
 'public', array['Bridge','Hilltop','Iconic'], false, 'likely',
 'Trail to the overlook is unpaved. Park permit required for crews.',
 'published', 'curated_v1', 4.7, 88),
('McKinney Falls State Park', 'Austin', 'TX', 30.1816, -97.7251,
 'Limestone falls and cypress trees on Onion Creek. Variety of light and water textures.',
 'public', array['Waterfall','Outdoor','Nature'], true, 'verified',
 'Texas State Parks photo permit required for wedding/commercial sessions.',
 'published', 'curated_v1', 4.5, 86),
('South Congress Avenue — "I love you so much" mural', 'Austin', 'TX', 30.2495, -97.7501,
 'Iconic green mural on the side of Jo''s Coffee. Full of tourists midday — go early.',
 'public', array['Mural','Iconic','Urban'], false, 'unknown',
 'Public sidewalk. Mural is on a private business — don''t block the entrance.',
 'published', 'curated_v1', 4.4, 82),
('Zilker Botanical Garden — Japanese Garden', 'Austin', 'TX', 30.2691, -97.7715,
 'Quiet stone bridges, koi ponds, and bamboo. Different feel from the rest of Texas.',
 'public', array['Garden','Quiet','Asian'], true, 'likely',
 'Austin Parks photo permit required. Cheaper than the surrounding private gardens.',
 'published', 'curated_v1', 4.5, 85),

-- ── Jacksonville, FL ──────────────────────────────────────────────────────
('Friendship Fountain', 'Jacksonville', 'FL', 30.3197, -81.6526,
 'One of the world''s tallest fountains, framed by the St. Johns River and downtown skyline.',
 'public', array['Waterfront','Urban','Sunset'], false, 'likely',
 'Public riverwalk. Crews need a Jacksonville Parks permit.',
 'published', 'curated_v1', 4.4, 82),
('Treaty Oak — Jessie Ball duPont Park', 'Jacksonville', 'FL', 30.3164, -81.6472,
 '250+ year-old live oak with a 25-foot trunk and a 145-foot canopy.',
 'public', array['Outdoor','Trees','Quiet'], false, 'unknown',
 'Public park. No permit for personal sessions.',
 'published', 'curated_v1', 4.6, 87),
('Atlantic Beach — North End', 'Atlantic Beach', 'FL', 30.3358, -81.3989,
 'Wide sandy beach with sea oat dunes — quieter than Jacksonville Beach proper.',
 'public', array['Beach','Sunrise','Coastal'], false, 'unknown',
 'Public beach. City of Atlantic Beach permit recommended for crews.',
 'published', 'curated_v1', 4.5, 85),
('Riverside — 5 Points District', 'Jacksonville', 'FL', 30.3225, -81.6792,
 'Historic neighborhood with pastel Victorians, brick streets, and mural-covered alleys.',
 'public', array['Historic','Architecture','Urban'], false, 'unknown',
 'Public streets. Be respectful of residences.',
 'published', 'curated_v1', 4.3, 80),
('Castaway Island Preserve', 'Jacksonville', 'FL', 30.3059, -81.4344,
 'Salt-marsh boardwalks, oaks draped in Spanish moss, and quiet water views.',
 'public', array['Outdoor','Marsh','Quiet'], false, 'likely',
 'Jacksonville Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.5, 84),

-- ── Indianapolis, IN ──────────────────────────────────────────────────────
('Indianapolis Canal Walk', 'Indianapolis', 'IN', 39.7717, -86.1657,
 'Three-mile downtown canal lined with bridges, sculptures, and fountains.',
 'public', array['Waterfront','Urban','Bridge'], false, 'likely',
 'City of Indianapolis Parks permit needed for organized sessions.',
 'published', 'curated_v1', 4.5, 85),
('Soldiers and Sailors Monument — Monument Circle', 'Indianapolis', 'IN', 39.7686, -86.1581,
 'Limestone monument at the heart of downtown — full city skyline backdrop.',
 'public', array['Iconic','Historic','Skyline'], false, 'likely',
 'Public street. State of Indiana approval needed for commercial production on monument grounds.',
 'published', 'curated_v1', 4.6, 86),
('Newfields — The Garden', 'Indianapolis', 'IN', 39.8276, -86.1842,
 '152 acres of formal gardens, woodland paths, and contemporary outdoor art.',
 'private', array['Garden','Art','Park'], true, 'verified',
 'Newfields photo permits range $50–$500 depending on shoot type. Walk-up with admission OK.',
 'published', 'curated_v1', 4.7, 89),
('Holliday Park — Ruins', 'Indianapolis', 'IN', 39.8631, -86.1797,
 'Architectural ruins from the demolished St. Paul Building — columns, pediments, and a fountain.',
 'public', array['Ruins','Architecture','Park'], true, 'likely',
 'Indy Parks photography permit required.',
 'published', 'curated_v1', 4.6, 87),
('Mass Ave — Cultural District', 'Indianapolis', 'IN', 39.7771, -86.1493,
 'Diagonal street with murals, the Athenæum, and historic theater marquees.',
 'public', array['Urban','Mural','Historic'], false, 'unknown',
 'Public sidewalks. Some murals are on private buildings.',
 'published', 'curated_v1', 4.3, 81),

-- ── Charlotte, NC ─────────────────────────────────────────────────────────
('Freedom Park', 'Charlotte', 'NC', 35.1908, -80.8435,
 '98-acre park with a lake, willow trees, and skyline visible through the trees.',
 'public', array['Park','Lake','Skyline'], true, 'verified',
 'Mecklenburg County Parks photography permit required: $35 portrait fee.',
 'published', 'curated_v1', 4.6, 87),
('Romare Bearden Park', 'Charlotte', 'NC', 35.2247, -80.8484,
 'Five-acre uptown park with sculptures and a clear view of the Charlotte skyline.',
 'public', array['Park','Skyline','Urban'], true, 'likely',
 'Same Mecklenburg County permit applies.',
 'published', 'curated_v1', 4.5, 85),
('NoDa Arts District Murals', 'Charlotte', 'NC', 35.2469, -80.8125,
 'North Davidson neighborhood — concentrated murals between 35th and 36th streets.',
 'public', array['Mural','Urban','Colorful'], false, 'unknown',
 'Public sidewalks.',
 'published', 'curated_v1', 4.4, 83),
('McGill Rose Garden', 'Charlotte', 'NC', 35.2336, -80.8244,
 'Free 1-acre garden with 200+ rose varieties and ornamental trees, peak May–June.',
 'public', array['Garden','Quiet','Floral'], false, 'unknown',
 'Free admission. No formal permit for personal sessions.',
 'published', 'curated_v1', 4.5, 84),
('Reedy Creek Park', 'Charlotte', 'NC', 35.2783, -80.7269,
 '737-acre nature preserve with old-growth forest, ponds, and meadows.',
 'public', array['Forest','Outdoor','Quiet'], true, 'likely',
 'Mecklenburg County Parks permit required.',
 'published', 'curated_v1', 4.4, 83),

-- ── San Francisco, CA ─────────────────────────────────────────────────────
('Golden Gate Bridge — Battery Spencer', 'Sausalito', 'CA', 37.8299, -122.4795,
 'North-side overlook on the Marin Headlands — the classic full-bridge angle with the city behind.',
 'public', array['Iconic','Bridge','Hilltop'], false, 'likely',
 'NPS — Golden Gate National Recreation Area. Walk-up shoots OK; commercial requires NPS permit.',
 'published', 'curated_v1', 4.9, 96),
('Palace of Fine Arts', 'San Francisco', 'CA', 37.8029, -122.4485,
 '1915 Beaux-Arts rotunda and lagoon — the Bay Area''s most reused photo location.',
 'public', array['Architecture','Iconic','Lagoon'], true, 'verified',
 'SF Recreation & Parks photo permit required for any organized shoot.',
 'published', 'curated_v1', 4.8, 91),
('Lands End — Sutro Baths Ruins', 'San Francisco', 'CA', 37.7805, -122.5135,
 'Concrete ruins of Victorian seawater baths perched above Pacific cliffs and the Cliff House.',
 'public', array['Ruins','Coastal','Historic'], false, 'likely',
 'NPS land — same Golden Gate NRA rules. Walk-up free; commercial needs permit.',
 'published', 'curated_v1', 4.8, 92),
('Painted Ladies — Alamo Square', 'San Francisco', 'CA', 37.7762, -122.4346,
 'Row of pastel Victorians with the downtown skyline behind. The "Full House" view.',
 'public', array['Iconic','Architecture','Skyline'], false, 'likely',
 'Park photo permit needed for crews; one shooter and a couple typically tolerated.',
 'published', 'curated_v1', 4.7, 90),
('Baker Beach — North End', 'San Francisco', 'CA', 37.7935, -122.4838,
 'Sandy beach with the Golden Gate Bridge framed by the Marin Headlands.',
 'public', array['Beach','Coastal','Iconic'], false, 'likely',
 'NPS land — same rules.',
 'published', 'curated_v1', 4.7, 89),

-- ── Seattle, WA ───────────────────────────────────────────────────────────
('Kerry Park', 'Seattle', 'WA', 47.6294, -122.3599,
 'Queen Anne Hill viewpoint with Space Needle, downtown skyline, and Mt. Rainier on clear days.',
 'public', array['Skyline','Iconic','Hilltop'], false, 'likely',
 'Seattle Parks photo permit required for organized shoots. Limited parking — go off-peak.',
 'published', 'curated_v1', 4.9, 94),
('Discovery Park — West Point Lighthouse', 'Seattle', 'WA', 47.6612, -122.4365,
 'Lighthouse at the tip of a 534-acre park where Puget Sound meets the bluffs.',
 'public', array['Coastal','Lighthouse','Outdoor'], false, 'likely',
 'Seattle Parks permit needed for crews.',
 'published', 'curated_v1', 4.7, 89),
('Pike Place Market — Public Market sign', 'Seattle', 'WA', 47.6097, -122.3422,
 'Iconic neon sign and clock above the historic market entrance.',
 'public', array['Iconic','Urban','Historic'], false, 'likely',
 'Public sidewalks; Pike Place Market PDA approval required for commercial production inside the market.',
 'published', 'curated_v1', 4.7, 89),
('Gas Works Park', 'Seattle', 'WA', 47.6456, -122.3344,
 'Rusted gasification structures preserved as sculpture overlooking Lake Union and the skyline.',
 'public', array['Industrial','Skyline','Park'], true, 'verified',
 'Seattle Parks photo permit required: $50 portrait, $250 wedding.',
 'published', 'curated_v1', 4.6, 87),
('Snoqualmie Falls', 'Snoqualmie', 'WA', 47.5417, -121.8377,
 '270-foot waterfall 30 minutes east of Seattle — the Twin Peaks falls.',
 'public', array['Waterfall','Outdoor','Dramatic'], false, 'likely',
 'Public viewpoints free. Salish Lodge property requires permission for hotel-side shots.',
 'published', 'curated_v1', 4.7, 90),

-- ── Denver, CO ────────────────────────────────────────────────────────────
('Red Rocks Park & Amphitheatre', 'Morrison', 'CO', 39.6654, -105.2057,
 'Towering red sandstone formations and the famous open-air amphitheatre.',
 'public', array['Outdoor','Dramatic','Iconic'], true, 'verified',
 'Denver Mountain Parks photo permit required for organized shoots: $200+ depending on day.',
 'published', 'curated_v1', 4.9, 94),
('Denver Botanic Gardens', 'Denver', 'CO', 39.7320, -104.9628,
 '24-acre urban garden with multiple themed sections and conservatories.',
 'private', array['Garden','Park','Floral'], true, 'verified',
 'Required permit: $250 portrait, $1500+ wedding.',
 'published', 'curated_v1', 4.7, 89),
('Union Station — Great Hall', 'Denver', 'CO', 39.7530, -105.0001,
 'Restored 1881 station with marble floors, leather benches, and grand exterior columns.',
 'public', array['Architecture','Historic','Indoor'], false, 'likely',
 'Public concourse. Commercial / wedding shoots require Union Station Alliance booking.',
 'published', 'curated_v1', 4.6, 87),
('Confluence Park', 'Denver', 'CO', 39.7546, -105.0073,
 'Cherry Creek meets the South Platte — pedestrian bridges, downtown skyline.',
 'public', array['Waterfront','Urban','Skyline'], false, 'likely',
 'Denver Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.5, 85),
('RiNo Art District', 'Denver', 'CO', 39.7702, -104.9789,
 'River North district with constantly-rotating murals on warehouse walls.',
 'public', array['Mural','Urban','Colorful'], false, 'unknown',
 'Public sidewalks. Some murals on private property.',
 'published', 'curated_v1', 4.6, 87),

-- ── Washington, DC ────────────────────────────────────────────────────────
('Lincoln Memorial — Reflecting Pool', 'Washington', 'DC', 38.8893, -77.0502,
 'Steps of the Lincoln Memorial with the long reflecting pool framing the Washington Monument.',
 'public', array['Iconic','Historic','Monument'], true, 'verified',
 'NPS National Mall permit required for any organized session — apply 2+ weeks ahead.',
 'published', 'curated_v1', 4.9, 95),
('Tidal Basin — Cherry Blossoms', 'Washington', 'DC', 38.8838, -77.0388,
 'Ring of Yoshino cherry trees around the Tidal Basin and Jefferson Memorial. Peak bloom is the photo event of DC.',
 'public', array['Floral','Iconic','Waterfront'], true, 'verified',
 'Same NPS permit. Crowds during cherry blossom festival (late March–early April).',
 'published', 'curated_v1', 4.9, 96),
('US Capitol — East Front', 'Washington', 'DC', 38.8899, -77.0090,
 'East steps of the Capitol with the dome rising directly behind.',
 'public', array['Iconic','Historic','Architecture'], true, 'likely',
 'US Capitol Police approval required for shoots; tripod-and-camera tourists OK.',
 'published', 'curated_v1', 4.7, 89),
('Georgetown — M Street & 31st', 'Washington', 'DC', 38.9047, -77.0626,
 'Historic Federal-style row houses, brick streets, and the iconic Cady''s Alley shops.',
 'public', array['Historic','Urban','Architecture'], false, 'likely',
 'Public sidewalks. Crews need DC film office permit.',
 'published', 'curated_v1', 4.6, 87),
('Library of Congress — Main Reading Room (Jefferson Building)', 'Washington', 'DC', 38.8887, -77.0047,
 'Beaux-Arts library with a 160-foot domed reading room, marble columns, and ornate iron.',
 'private', array['Architecture','Indoor','Historic'], true, 'verified',
 'Library of Congress photo permit required for non-personal use; tripods restricted.',
 'published', 'curated_v1', 4.8, 91),

-- ── Boston, MA ────────────────────────────────────────────────────────────
('Boston Public Garden — Lagoon Bridge', 'Boston', 'MA', 42.3539, -71.0723,
 'Iron suspension bridge over the lagoon with the Make Way for Ducklings sculptures nearby.',
 'public', array['Park','Bridge','Iconic'], true, 'verified',
 'City of Boston Parks photo permit required: $75 portrait.',
 'published', 'curated_v1', 4.7, 89),
('Acorn Street — Beacon Hill', 'Boston', 'MA', 42.3580, -71.0691,
 'Cobblestone street lined with 19th-century rowhouses — possibly the most photographed street in America.',
 'public', array['Historic','Cobblestone','Iconic'], false, 'likely',
 'Public street. Be respectful of residents — early morning is best.',
 'published', 'curated_v1', 4.8, 91),
('Boston Common — Frog Pond', 'Boston', 'MA', 42.3551, -71.0656,
 'Oldest public park in the US — Frog Pond with skyline behind, ice rink in winter.',
 'public', array['Park','Skyline','Historic'], true, 'likely',
 'Same Boston Parks permit applies.',
 'published', 'curated_v1', 4.5, 85),
('Castle Island — Fort Independence', 'Boston', 'MA', 42.3382, -71.0118,
 'Granite fort on a peninsula in South Boston, surrounded by harbor and skyline views.',
 'public', array['Historic','Coastal','Skyline'], false, 'unknown',
 'Public state park.',
 'published', 'curated_v1', 4.5, 86),
('Harvard Yard', 'Cambridge', 'MA', 42.3744, -71.1169,
 'Brick paths, ivy-covered halls, the iconic John Harvard statue.',
 'private', array['Architecture','Historic','Campus'], true, 'verified',
 'Harvard requires advance approval for commercial photography on campus.',
 'published', 'curated_v1', 4.6, 87),

-- ── Nashville, TN ─────────────────────────────────────────────────────────
('Nashville Skyline — Cumberland Park', 'Nashville', 'TN', 36.1640, -86.7691,
 'East-bank park with the AT&T Building and pedestrian bridge framing the skyline at sunset.',
 'public', array['Skyline','Sunset','Urban'], false, 'likely',
 'Metro Parks permit required for organized shoots.',
 'published', 'curated_v1', 4.7, 89),
('Cheekwood Estate & Gardens', 'Nashville', 'TN', 36.0910, -86.8728,
 '55-acre Georgian-style estate with formal gardens and Tennessee art collections.',
 'private', array['Garden','Mansion','Formal'], true, 'verified',
 'Cheekwood photography permit required: $100 portrait, $500+ wedding.',
 'published', 'curated_v1', 4.7, 90),
('Centennial Park — Parthenon', 'Nashville', 'TN', 36.1497, -86.8137,
 'Full-scale replica of the Athenian Parthenon — yes, in Nashville.',
 'public', array['Architecture','Park','Iconic'], true, 'likely',
 'Metro Parks permit required.',
 'published', 'curated_v1', 4.5, 85),
('Percy Warner Park — Belle Meade Boulevard Allée', 'Nashville', 'TN', 36.0586, -86.8961,
 'Stone gates and a tree-lined boulevard leading to 2,684-acre Percy Warner Park.',
 'public', array['Park','Trees','Quiet'], true, 'likely',
 'Metro Parks permit required.',
 'published', 'curated_v1', 4.5, 86),
('Downtown — "I Believe in Nashville" mural', 'Nashville', 'TN', 36.1458, -86.7706,
 '12 South neighborhood — the original location at 2702 12th Ave S.',
 'public', array['Mural','Urban','Colorful'], false, 'unknown',
 'Public sidewalk; long lines on weekends.',
 'published', 'curated_v1', 4.4, 82),

-- ── Detroit, MI ───────────────────────────────────────────────────────────
('Detroit Riverwalk — Spirit Plaza', 'Detroit', 'MI', 42.3296, -83.0414,
 'Three-mile riverwalk with the Renaissance Center, Belle Isle in distance, and the Windsor skyline across.',
 'public', array['Waterfront','Urban','Skyline'], false, 'likely',
 'City of Detroit film office permit needed for crews.',
 'published', 'curated_v1', 4.6, 87),
('Belle Isle — James Scott Memorial Fountain', 'Detroit', 'MI', 42.3382, -82.9766,
 'Marble fountain on a 982-acre island park in the Detroit River.',
 'public', array['Park','Fountain','Architecture'], true, 'likely',
 'Michigan State Parks permit required.',
 'published', 'curated_v1', 4.6, 87),
('Detroit Institute of Arts — Rivera Court', 'Detroit', 'MI', 42.3593, -83.0645,
 'Diego Rivera murals covering all four walls of a vast skylit court.',
 'private', array['Art','Indoor','Mural'], true, 'verified',
 'DIA approval required for any commercial / wedding photography.',
 'published', 'curated_v1', 4.7, 89),
('Eastern Market — Mural Walls', 'Detroit', 'MI', 42.3475, -83.0408,
 'Six blocks of warehouses covered in concentrated, world-class street art.',
 'public', array['Mural','Urban','Colorful'], false, 'unknown',
 'Public streets and sidewalks.',
 'published', 'curated_v1', 4.7, 89),
('Michigan Central Station', 'Detroit', 'MI', 42.3286, -83.0775,
 '1913 Beaux-Arts station, recently restored. Exterior is iconic.',
 'public', array['Architecture','Historic','Iconic'], false, 'likely',
 'Public sidewalk for exterior. Interior tours require booking through Ford.',
 'published', 'curated_v1', 4.7, 89),

-- ── Portland, OR ──────────────────────────────────────────────────────────
('Multnomah Falls', 'Bridal Veil', 'OR', 45.5762, -122.1158,
 '620-foot two-tier waterfall with the iconic Benson Bridge crossing the lower drop. 30 minutes east of Portland.',
 'public', array['Waterfall','Iconic','Outdoor'], false, 'likely',
 'USDA Forest Service permit required for commercial photography.',
 'published', 'curated_v1', 4.9, 95),
('Portland Japanese Garden', 'Portland', 'OR', 45.5189, -122.7081,
 '12 acres of stone, water, and seasonal plantings — peak in spring (cherry) and fall (maples).',
 'private', array['Garden','Asian','Quiet'], true, 'verified',
 'Garden photo permit required: $200 portrait, no weddings allowed.',
 'published', 'curated_v1', 4.8, 91),
('Pittock Mansion Lookout', 'Portland', 'OR', 45.5253, -122.7164,
 'Mount Hood, the Willamette, and the Portland skyline visible from the mansion grounds.',
 'public', array['Skyline','Mansion','Hilltop'], true, 'likely',
 'Pittock Mansion photo permit required for organized shoots.',
 'published', 'curated_v1', 4.7, 89),
('Cathedral Park — St. Johns Bridge', 'Portland', 'OR', 45.5848, -122.7641,
 'Park beneath the gothic-arched St. Johns Bridge — the columns frame perfect leading lines.',
 'public', array['Bridge','Park','Architecture'], false, 'likely',
 'Portland Parks permit required.',
 'published', 'curated_v1', 4.7, 89),
('Lan Su Chinese Garden', 'Portland', 'OR', 45.5258, -122.6731,
 'One-acre walled garden in Old Town built in the Suzhou tradition.',
 'private', array['Garden','Asian','Indoor'], true, 'verified',
 'Lan Su garden photo permit required: $250 portrait.',
 'published', 'curated_v1', 4.6, 87),

-- ── Las Vegas, NV ─────────────────────────────────────────────────────────
('Red Rock Canyon — Calico Hills', 'Las Vegas', 'NV', 36.1357, -115.4196,
 'Striped red and white sandstone formations 15 miles west of the Strip.',
 'public', array['Outdoor','Dramatic','Desert'], true, 'verified',
 'BLM commercial photography permit required ($150+).',
 'published', 'curated_v1', 4.8, 92),
('Valley of Fire State Park', 'Overton', 'NV', 36.4858, -114.5333,
 'Aztec sandstone formations 50 miles northeast of Vegas. Colors are unreal at golden hour.',
 'public', array['Outdoor','Desert','Dramatic'], true, 'verified',
 'Nevada State Parks photo permit required: $150 wedding/commercial.',
 'published', 'curated_v1', 4.9, 94),
('Las Vegas Sign — Welcome to Fabulous', 'Las Vegas', 'NV', 36.0820, -115.1728,
 'Iconic 1959 neon sign on the south end of the Strip.',
 'public', array['Iconic','Neon','Urban'], false, 'unknown',
 'Public median; small parking lot. Generally tolerated for personal sessions.',
 'published', 'curated_v1', 4.5, 85),
('The Neon Museum — Boneyard', 'Las Vegas', 'NV', 36.1836, -115.1370,
 'Vintage Vegas neon signs displayed outdoors. Day and night both work.',
 'private', array['Neon','Iconic','Indoor'], true, 'verified',
 'Required photography pass: $100+ depending on day. Strict no-tripod policy on standard tours.',
 'published', 'curated_v1', 4.7, 89),
('Bellagio Conservatory & Botanical Gardens', 'Las Vegas', 'NV', 36.1126, -115.1767,
 'Indoor seasonal floral displays on the casino floor — changes 5x/year.',
 'private', array['Garden','Indoor','Floral'], true, 'verified',
 'Bellagio approval required for commercial / wedding shoots; tourists welcome.',
 'published', 'curated_v1', 4.5, 85),

-- ── Memphis, TN ───────────────────────────────────────────────────────────
('Beale Street', 'Memphis', 'TN', 35.1395, -90.0526,
 'Historic neon-lit blues district, especially photogenic after dark.',
 'public', array['Historic','Neon','Urban'], false, 'likely',
 'City of Memphis film permit needed for crews.',
 'published', 'curated_v1', 4.5, 85),
('Mud Island River Park', 'Memphis', 'TN', 35.1505, -90.0568,
 'Park on a peninsula in the Mississippi River with downtown skyline framed across.',
 'public', array['Waterfront','Park','Skyline'], false, 'likely',
 'Memphis Parks permit required.',
 'published', 'curated_v1', 4.5, 85),
('Sun Studio', 'Memphis', 'TN', 35.1424, -90.0387,
 'Birthplace of rock ''n'' roll. Exterior is photo-friendly; interior requires tour booking.',
 'private', array['Historic','Iconic','Music'], true, 'verified',
 'Sun Studio approval required for interior shoots.',
 'published', 'curated_v1', 4.6, 87),
('Memphis Botanic Garden', 'Memphis', 'TN', 35.1175, -89.8730,
 '96 acres of themed gardens including a Japanese garden and rose garden.',
 'private', array['Garden','Park','Floral'], true, 'verified',
 'Garden photography permit required: $150 portrait.',
 'published', 'curated_v1', 4.5, 85),
('Big River Crossing — Harahan Bridge Walkway', 'Memphis', 'TN', 35.1290, -90.0716,
 'Mile-long pedestrian walkway across the Mississippi with skyline behind.',
 'public', array['Bridge','Waterfront','Skyline'], false, 'likely',
 'Public bridge.',
 'published', 'curated_v1', 4.5, 85),

-- ── Atlanta, GA ───────────────────────────────────────────────────────────
('Piedmont Park — Skyline Lawn', 'Atlanta', 'GA', 33.7857, -84.3722,
 '189 acres in midtown with the Atlanta skyline as backdrop.',
 'public', array['Park','Skyline','Urban'], true, 'verified',
 'Piedmont Park Conservancy photo permit required: $50 portrait, $250+ wedding.',
 'published', 'curated_v1', 4.7, 89),
('Atlanta BeltLine — Eastside Trail Murals', 'Atlanta', 'GA', 33.7745, -84.3666,
 'Reclaimed-rail trail with rotating murals between Krog and Inman Park.',
 'public', array['Mural','Urban','Trail'], false, 'unknown',
 'Public trail.',
 'published', 'curated_v1', 4.6, 87),
('Krog Street Tunnel', 'Atlanta', 'GA', 33.7541, -84.3617,
 'Pedestrian tunnel painted floor-to-ceiling with constantly-rotating street art.',
 'public', array['Mural','Urban','Tunnel'], false, 'unknown',
 'Public tunnel.',
 'published', 'curated_v1', 4.5, 85),
('Atlanta Botanical Garden', 'Atlanta', 'GA', 33.7902, -84.3729,
 '30 acres of formal gardens with the famous Earth Goddess sculpture.',
 'private', array['Garden','Park','Floral'], true, 'verified',
 'Garden photo permit required: $300 portrait.',
 'published', 'curated_v1', 4.7, 89),
('Stone Mountain — Carving Lawn', 'Stone Mountain', 'GA', 33.8053, -84.1450,
 'Granite dome with a controversial Confederate carving — visit for the geology and broad lawn views.',
 'public', array['Outdoor','Park','Hilltop'], true, 'verified',
 'Stone Mountain Park photo permit required: $50+ depending on shoot.',
 'published', 'curated_v1', 4.5, 85),

-- ── Miami, FL ─────────────────────────────────────────────────────────────
('Wynwood Walls', 'Miami', 'FL', 25.8009, -80.1995,
 'Open-air street art museum in the Wynwood Arts District.',
 'private', array['Mural','Urban','Colorful'], true, 'verified',
 'Wynwood Walls admission required; commercial shoots need booking.',
 'published', 'curated_v1', 4.7, 89),
('South Beach — Art Deco Historic District', 'Miami Beach', 'FL', 25.7853, -80.1305,
 'Pastel Art Deco hotels along Ocean Drive — the Versace Mansion, the Carlyle, the Colony.',
 'public', array['Architecture','Beach','Historic'], false, 'likely',
 'City of Miami Beach film permit required for crews. Tripod tourists OK.',
 'published', 'curated_v1', 4.7, 90),
('Vizcaya Museum & Gardens', 'Miami', 'FL', 25.7445, -80.2102,
 '1916 Italian Renaissance-style villa on Biscayne Bay with formal gardens and stone barge.',
 'private', array['Mansion','Garden','Historic'], true, 'verified',
 'Vizcaya photography permit required: $250 portrait, $1500+ wedding.',
 'published', 'curated_v1', 4.8, 92),
('Pérez Art Museum — Hanging Gardens', 'Miami', 'FL', 25.7857, -80.1862,
 'Concrete museum with hanging plants and the Biscayne Bay behind. Modernist architecture.',
 'public', array['Architecture','Modernist','Waterfront'], true, 'likely',
 'PAMM approval required for commercial photography on the verandas.',
 'published', 'curated_v1', 4.5, 85),
('Coconut Grove — Barnacle Historic State Park', 'Miami', 'FL', 25.7280, -80.2415,
 'Oldest house in Miami-Dade still on its original site, surrounded by tropical hardwood hammock and bayfront views.',
 'public', array['Historic','Park','Tropical'], true, 'likely',
 'Florida State Parks photo permit required for organized shoots.',
 'published', 'curated_v1', 4.5, 85),

-- ── Minneapolis, MN ───────────────────────────────────────────────────────
('Stone Arch Bridge', 'Minneapolis', 'MN', 44.9806, -93.2570,
 '1883 limestone bridge over the Mississippi River with the Minneapolis skyline behind.',
 'public', array['Bridge','Historic','Skyline'], false, 'likely',
 'Minneapolis Park & Rec permit needed for crews.',
 'published', 'curated_v1', 4.8, 91),
('Minnehaha Falls', 'Minneapolis', 'MN', 44.9156, -93.2110,
 '53-foot waterfall on Minnehaha Creek, frozen sculptural ice in winter.',
 'public', array['Waterfall','Park','Outdoor'], true, 'verified',
 'Minneapolis Park & Rec photo permit required: $25 portrait.',
 'published', 'curated_v1', 4.7, 89),
('Walker Art Center — Sculpture Garden', 'Minneapolis', 'MN', 44.9694, -93.2890,
 '11-acre garden including the Spoonbridge & Cherry sculpture.',
 'public', array['Sculpture','Iconic','Park'], true, 'likely',
 'Walker Art Center approval required for commercial photography.',
 'published', 'curated_v1', 4.6, 87),
('Lake of the Isles', 'Minneapolis', 'MN', 44.9573, -93.3072,
 'Chain of urban lakes with a 2.7-mile walking path and skyline views.',
 'public', array['Waterfront','Park','Skyline'], false, 'likely',
 'Same Park & Rec permit applies.',
 'published', 'curated_v1', 4.5, 85),
('Mill Ruins Park', 'Minneapolis', 'MN', 44.9785, -93.2580,
 'Excavated ruins of the 19th-century flour mills along the Mississippi.',
 'public', array['Ruins','Industrial','Historic'], true, 'likely',
 'Same Park & Rec permit applies.',
 'published', 'curated_v1', 4.6, 87),

-- ── Kansas City, MO ───────────────────────────────────────────────────────
('Country Club Plaza', 'Kansas City', 'MO', 39.0413, -94.5917,
 '1923 Spanish-style shopping district with fountains, towers, and pastel facades.',
 'public', array['Architecture','Urban','Historic'], false, 'likely',
 'Public streets; commercial requires Highwoods Properties approval.',
 'published', 'curated_v1', 4.6, 87),
('Loose Park — Rose Garden', 'Kansas City', 'MO', 39.0381, -94.5946,
 '4,000-bush rose garden in a 75-acre park near the Plaza.',
 'public', array['Garden','Park','Floral'], true, 'verified',
 'KC Parks photo permit required: $50 portrait.',
 'published', 'curated_v1', 4.6, 87),
('Union Station KC — Grand Hall', 'Kansas City', 'MO', 39.0850, -94.5856,
 '1914 Beaux-Arts terminal with marble floors, soaring arches, and bronze chandeliers.',
 'private', array['Architecture','Historic','Indoor'], true, 'verified',
 'Union Station photography permit required for any non-snapshot use.',
 'published', 'curated_v1', 4.7, 89),
('Liberty Memorial — National WWI Museum', 'Kansas City', 'MO', 39.0805, -94.5856,
 '217-foot tower with reflecting pool and full skyline views.',
 'public', array['Monument','Skyline','Historic'], false, 'likely',
 'KC Parks permit required for organized shoots on the lawn.',
 'published', 'curated_v1', 4.6, 88),
('West Bottoms — historic warehouses', 'Kansas City', 'MO', 39.1045, -94.6028,
 'Brick warehouses and freight elevators turned antique markets and breweries.',
 'public', array['Industrial','Urban','Historic'], false, 'unknown',
 'Public streets; some warehouses are private — ask for interior shoots.',
 'published', 'curated_v1', 4.4, 83),

-- ── San Francisco-area additions: Oakland (treated separately at #44) ─────

-- ── Tampa, FL ─────────────────────────────────────────────────────────────
('Tampa Riverwalk', 'Tampa', 'FL', 27.9466, -82.4569,
 '2.6-mile waterfront promenade through downtown with bridges and skyline.',
 'public', array['Waterfront','Urban','Skyline'], false, 'likely',
 'Tampa film office permit required for crews.',
 'published', 'curated_v1', 4.5, 85),
('Bayshore Boulevard', 'Tampa', 'FL', 27.9088, -82.4815,
 '4.5-mile continuous sidewalk along Hillsborough Bay — longest in the world. Sunset views.',
 'public', array['Waterfront','Sunset','Urban'], false, 'unknown',
 'Public sidewalk.',
 'published', 'curated_v1', 4.5, 85),
('Ybor City — historic district', 'Tampa', 'FL', 27.9601, -82.4382,
 'Cuban-American cigar factory district with brick streets, wrought-iron balconies, and tile entries.',
 'public', array['Historic','Urban','Cultural'], false, 'likely',
 'Tampa film permit needed for crews.',
 'published', 'curated_v1', 4.5, 85),
('Sunken Gardens', 'St. Petersburg', 'FL', 27.7886, -82.6485,
 '4-acre 100-year-old tropical garden 15 minutes from Tampa.',
 'private', array['Garden','Tropical','Floral'], true, 'verified',
 'Sunken Gardens photo permit required: $75+.',
 'published', 'curated_v1', 4.7, 89),
('Honeymoon Island State Park', 'Dunedin', 'FL', 28.0641, -82.8270,
 'White sand beaches and slash pine forests on a barrier island west of Tampa.',
 'public', array['Beach','Outdoor','Coastal'], true, 'verified',
 'Florida State Parks photo permit required.',
 'published', 'curated_v1', 4.7, 89),

-- ── New Orleans, LA ───────────────────────────────────────────────────────
('Jackson Square — French Quarter', 'New Orleans', 'LA', 29.9574, -90.0628,
 'Iron-fenced park in front of St. Louis Cathedral. The most photographed view in the South.',
 'public', array['Iconic','Historic','Architecture'], false, 'likely',
 'NOLA City Park & film office permit required for crews.',
 'published', 'curated_v1', 4.8, 91),
('City Park — Singing Oak', 'New Orleans', 'LA', 29.9847, -90.0941,
 '600-year-old live oak with wind chimes — and 1,300 acres of cypress and lagoons surrounding.',
 'public', array['Park','Trees','Quiet'], true, 'verified',
 'City Park photo permit required: $50 portrait.',
 'published', 'curated_v1', 4.7, 89),
('Garden District — Mansions of St. Charles', 'New Orleans', 'LA', 29.9251, -90.0814,
 'Greek Revival, Italianate, and Queen Anne mansions along oak-shaded boulevards.',
 'public', array['Architecture','Historic','Trees'], false, 'likely',
 'Public sidewalks. Be respectful — these are residences.',
 'published', 'curated_v1', 4.7, 90),
('Crescent Park — Piety Wharf', 'New Orleans', 'LA', 29.9695, -90.0492,
 'Mississippi-side park in the Bywater with a rusted "Mississippi Bridge" arch sculpture.',
 'public', array['Waterfront','Urban','Industrial'], false, 'likely',
 'Public park.',
 'published', 'curated_v1', 4.5, 85),
('Oak Alley Plantation', 'Vacherie', 'LA', 30.0061, -90.7917,
 '300-year-old quarter-mile of live oaks leading to an antebellum mansion. 1 hour west of NOLA.',
 'private', array['Trees','Historic','Iconic'], true, 'verified',
 'Oak Alley photography permit required: $300 portrait, $1500+ wedding.',
 'published', 'curated_v1', 4.9, 94);

-- 28 cities × 5 locations = 140 rows.
