-- National park hubs + regional destination seed. The previous batches
-- covered metros + tourist towns; this fills in the towns photographers
-- route through for outdoor sessions: Moab, Springdale (Zion),
-- Gatlinburg (Smokies), Estes Park (RMNP), West Glacier, Yosemite, etc.
-- Plus a handful of regional destinations photographers actually travel
-- to (Outer Banks, Tybee Island, Cape May, Ithaca's Finger Lakes).
--
-- Same conventions: coordinates within a block of landmarks, public-
-- knowledge descriptions, conservative permit info. Apostrophes escaped
-- with '' doubling. Re-running creates duplicates — run once.
--
-- Most national-park entries flag permit_required = true with a 'likely'
-- certainty; commercial photography on NPS land legitimately needs a
-- permit ($300+/day), and shoots without one risk fines, so the
-- conservative flag is the safe default.

insert into public.locations (
  name, city, state, latitude, longitude, description, access_type, tags,
  permit_required, permit_certainty, permit_notes,
  status, source, rating, quality_score
) values

-- ── Moab, UT ──────────────────────────────────────────────────────────────
('Delicate Arch', 'Moab', 'UT', 38.7436, -109.4993,
 '52-foot freestanding sandstone arch — Utah''s most-photographed natural feature, 1.5-mile uphill hike to reach.',
 'public', array['Iconic','Outdoor','Desert'], true, 'likely',
 'NPS Arches commercial photography permit required.',
 'published', 'curated_v1', 4.9, 95),
('Mesa Arch — Canyonlands', 'Moab', 'UT', 38.3886, -109.8694,
 'Cliff-edge arch in Canyonlands NP — sunrise lights the underside fiery orange, panorama of canyon rims behind.',
 'public', array['Iconic','Sunrise','Canyon'], true, 'likely',
 'NPS Canyonlands commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Park Avenue — Arches', 'Moab', 'UT', 38.6219, -109.5950,
 'Sandstone fins flanking a wide canyon floor — reads like a Manhattan-scale corridor of skyscrapers carved from rock.',
 'public', array['Canyon','Outdoor','Iconic'], true, 'likely',
 'NPS Arches commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Springdale, UT (Zion gateway) ─────────────────────────────────────────
('Zion Canyon — Court of the Patriarchs', 'Springdale', 'UT', 37.2169, -112.9544,
 'Three sandstone peaks — Abraham, Isaac, Jacob — towering over the Virgin River. Bus-stop overlook, easy access.',
 'public', array['Mountain','Iconic','Canyon'], true, 'likely',
 'NPS Zion commercial photography permit required.',
 'published', 'curated_v1', 4.8, 90),
('The Narrows — Riverside Walk', 'Springdale', 'UT', 37.2972, -112.9472,
 'Slot canyon waded via the Virgin River — paved approach trail, then river-walking through 1,000-foot sandstone walls.',
 'public', array['Canyon','River','Iconic'], true, 'likely',
 'NPS Zion commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),
('Canyon Junction Bridge', 'Springdale', 'UT', 37.2042, -112.9831,
 'Footbridge over the Virgin River — the iconic Watchman peak framed perfectly behind, sunset color on the cliffs.',
 'public', array['Bridge','Iconic','Sunset'], true, 'likely',
 'NPS Zion commercial photography permit required.',
 'published', 'curated_v1', 4.8, 90),

-- ── Bryce Canyon City, UT ────────────────────────────────────────────────
('Sunrise Point', 'Bryce Canyon City', 'UT', 37.6253, -112.1614,
 'Rim viewpoint over a hoodoo amphitheater — orange-pink spires, the iconic Bryce sunrise glow.',
 'public', array['Sunrise','Canyon','Iconic'], true, 'likely',
 'NPS Bryce Canyon commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Inspiration Point', 'Bryce Canyon City', 'UT', 37.6231, -112.1542,
 'High-vantage rim overlook — sweeping view across thousands of hoodoos, especially deep color at sunset.',
 'public', array['Canyon','Iconic','Sunset'], true, 'likely',
 'NPS Bryce Canyon commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),
('Bryce Amphitheater Floor — Wall Street', 'Bryce Canyon City', 'UT', 37.6253, -112.1644,
 'Switchbacks (Navajo Loop) into the heart of the amphitheater — towering hoodoos on both sides, Douglas firs squeezed between.',
 'public', array['Canyon','Outdoor','Iconic'], true, 'likely',
 'NPS Bryce Canyon commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),

-- ── Page, AZ ──────────────────────────────────────────────────────────────
('Horseshoe Bend', 'Page', 'AZ', 36.8791, -111.5104,
 '1,000-foot cliff overlooking a 270-degree turn of the Colorado River — sunrise colors, the most-photographed shot in the Southwest.',
 'public', array['Iconic','Canyon','Sunrise'], true, 'likely',
 'City of Page entry fee + commercial photography permit; NPS Glen Canyon NRA also applies for some uses.',
 'published', 'curated_v1', 4.9, 94),
('Lake Powell — Wahweap Overlook', 'Page', 'AZ', 36.9908, -111.4894,
 'Red-rock canyons flooded into a turquoise lake — Antelope Island, sandstone bays, dramatic against the desert.',
 'public', array['Lake','Canyon','Iconic'], true, 'likely',
 'NPS Glen Canyon NRA commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),
('Antelope Canyon (Lower)', 'Page', 'AZ', 36.9067, -111.4108,
 'Slot canyon on Navajo Nation land — wave-sculpted sandstone walls, light beams in summer mid-day.',
 'public', array['Canyon','Iconic','Outdoor'], true, 'likely',
 'Navajo Parks photography tour required; commercial use needs separate permit.',
 'published', 'curated_v1', 4.9, 93),

-- ── Grand Canyon Village, AZ ──────────────────────────────────────────────
('Mather Point — South Rim', 'Grand Canyon Village', 'AZ', 36.0625, -112.1090,
 'Most-visited overlook in the park — a railed promontory hanging over a mile of canyon depth.',
 'public', array['Canyon','Iconic','Overlook'], true, 'likely',
 'NPS Grand Canyon commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Hopi Point Sunset', 'Grand Canyon Village', 'AZ', 36.0719, -112.1481,
 'West-facing point on Hermit Road — best South Rim sunset overlook, deepest canyon view.',
 'public', array['Canyon','Sunset','Iconic'], true, 'likely',
 'NPS Grand Canyon commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),
('Bright Angel Trailhead — South Rim', 'Grand Canyon Village', 'AZ', 36.0573, -112.1442,
 'Iconic descent off the South Rim — first switchbacks, towering rim above, canyon depth opening below.',
 'public', array['Canyon','Hike','Outdoor'], true, 'likely',
 'NPS Grand Canyon commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Estes Park, CO (RMNP gateway) ────────────────────────────────────────
('Bear Lake', 'Estes Park', 'CO', 40.3119, -105.6450,
 'Sub-alpine glacial lake at 9,475 feet — Hallett Peak rising directly behind, easy paved loop, mirror reflections at dawn.',
 'public', array['Lake','Mountain','Iconic'], true, 'likely',
 'NPS Rocky Mountain commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Trail Ridge Road — Forest Canyon Overlook', 'Estes Park', 'CO', 40.4019, -105.7511,
 '11,716-foot overlook on the highest paved through-road in the US — alpine tundra, sweeping ridge views.',
 'public', array['Mountain','Outdoor','Overlook'], true, 'likely',
 'NPS Rocky Mountain commercial photography permit required; closed in winter.',
 'published', 'curated_v1', 4.8, 89),
('Sprague Lake', 'Estes Park', 'CO', 40.3225, -105.6092,
 'Calm sub-alpine lake — half-mile boardwalk loop, Continental Divide reflected on still mornings, accessible without a hike.',
 'public', array['Lake','Mountain','Outdoor'], true, 'likely',
 'NPS Rocky Mountain commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Joshua Tree, CA ───────────────────────────────────────────────────────
('Cholla Cactus Garden', 'Joshua Tree', 'CA', 33.9244, -115.9286,
 'Quarter-mile loop through dense teddy-bear cholla — backlit-fuzz halo at sunrise, pure desert texture.',
 'public', array['Desert','Outdoor','Sunrise'], true, 'likely',
 'NPS Joshua Tree commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),
('Skull Rock', 'Joshua Tree', 'CA', 33.9883, -116.0561,
 'Roadside boulder weathered into a skull-shaped form — easy parking, popular for portraits framed by desert behind.',
 'public', array['Desert','Iconic','Outdoor'], true, 'likely',
 'NPS Joshua Tree commercial photography permit required.',
 'published', 'curated_v1', 4.6, 85),
('Hidden Valley', 'Joshua Tree', 'CA', 34.0122, -116.1700,
 'Boulder-ringed valley with a 1-mile loop — Joshua trees, pile-of-marbles rock formations, climber playground.',
 'public', array['Desert','Outdoor','Mountain'], true, 'likely',
 'NPS Joshua Tree commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Yosemite Valley, CA ───────────────────────────────────────────────────
('Tunnel View', 'Yosemite Valley', 'CA', 37.7150, -119.6772,
 'Roadside overlook framing El Capitan, Bridalveil Fall, and Half Dome in one composition — Ansel Adams''s signature view.',
 'public', array['Iconic','Mountain','Overlook'], true, 'likely',
 'NPS Yosemite commercial photography permit required.',
 'published', 'curated_v1', 4.9, 95),
('Glacier Point', 'Yosemite Valley', 'CA', 37.7308, -119.5736,
 '7,214-foot rim overlook — Half Dome at eye level, the entire valley below. Closed in winter.',
 'public', array['Mountain','Iconic','Overlook'], true, 'likely',
 'NPS Yosemite commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('El Capitan Meadow', 'Yosemite Valley', 'CA', 37.7194, -119.6403,
 'Floor-of-the-valley meadow at the base of El Capitan — the 3,000-foot granite wall directly above, oaks framing.',
 'public', array['Mountain','Outdoor','Iconic'], true, 'likely',
 'NPS Yosemite commercial photography permit required.',
 'published', 'curated_v1', 4.8, 90),

-- ── Death Valley, CA (Furnace Creek) ──────────────────────────────────────
('Mesquite Flat Sand Dunes', 'Death Valley', 'CA', 36.6075, -117.1153,
 'Sweeping curves of golden sand — sunrise + sunset shadows are otherworldly, mountains framing the dune field.',
 'public', array['Desert','Iconic','Sunset'], true, 'likely',
 'NPS Death Valley commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Zabriskie Point', 'Death Valley', 'CA', 36.4203, -116.8114,
 'Eroded badlands of the Furnace Creek formation — gold + cream pleated rock at sunrise, accessed by a paved short walk.',
 'public', array['Desert','Sunrise','Iconic'], true, 'likely',
 'NPS Death Valley commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),
('Badwater Basin', 'Death Valley', 'CA', 36.2300, -116.7672,
 'Lowest point in North America (-282 feet) — hexagonal salt flat patterns extending to the horizon, surrounded by mountains.',
 'public', array['Desert','Iconic','Outdoor'], true, 'likely',
 'NPS Death Valley commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),

-- ── Crater Lake, OR ───────────────────────────────────────────────────────
('Watchman Overlook — Crater Lake', 'Crater Lake', 'OR', 42.9442, -122.1714,
 'West-rim overlook with Wizard Island directly below — deepest blue lake in the US, 1,943 feet deep.',
 'public', array['Lake','Iconic','Overlook'], true, 'likely',
 'NPS Crater Lake commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Discovery Point', 'Crater Lake', 'OR', 42.9100, -122.1797,
 'First overlook on the West Rim Drive — full panorama of the caldera, Phantom Ship rock formation visible.',
 'public', array['Lake','Mountain','Iconic'], true, 'likely',
 'NPS Crater Lake commercial photography permit required.',
 'published', 'curated_v1', 4.8, 90),
('Cleetwood Cove Trail', 'Crater Lake', 'OR', 42.9606, -122.0856,
 'Only legal access to the lakeshore — switchback trail down 700 vertical feet to the deep-blue water.',
 'public', array['Lake','Hike','Outdoor'], true, 'likely',
 'NPS Crater Lake commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Government Camp, OR (Mt Hood gateway) ────────────────────────────────
('Trillium Lake', 'Government Camp', 'OR', 45.2675, -121.7367,
 'Mountain lake with a perfect Mt Hood reflection — the postcard Oregon shot, easy lakeside access.',
 'public', array['Lake','Mountain','Iconic'], true, 'likely',
 'Mt Hood NF commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),
('Timberline Lodge', 'Government Camp', 'OR', 45.3308, -121.7108,
 '1937 WPA-built ski lodge at 6,000 feet on Mt Hood — hand-carved beams, stone fireplace, "The Shining" exterior shots filmed here.',
 'public', array['Architecture','Historic','Mountain'], true, 'likely',
 'Mt Hood NF + Timberline Lodge for commercial photography requests.',
 'published', 'curated_v1', 4.8, 89),
('Mirror Lake', 'Government Camp', 'OR', 45.3181, -121.7919,
 '1.5-mile hike to a small alpine lake — Mt Hood reflected when conditions are calm, surrounded by old-growth forest.',
 'public', array['Lake','Mountain','Hike'], true, 'likely',
 'Mt Hood NF commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Ashford, WA (Mt Rainier gateway) ─────────────────────────────────────
('Reflection Lakes', 'Ashford', 'WA', 46.7681, -121.7322,
 'Two roadside lakes mirroring Mt Rainier — easy access, popular at sunrise when the peak goes pink.',
 'public', array['Lake','Mountain','Sunrise'], true, 'likely',
 'NPS Mt Rainier commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Paradise — Wildflower Meadows', 'Ashford', 'WA', 46.7861, -121.7353,
 'Sub-alpine meadows at 5,400 feet — peak wildflower bloom late July, Mt Rainier rising directly above.',
 'public', array['Mountain','Outdoor','Iconic'], true, 'likely',
 'NPS Mt Rainier commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),
('Sunrise Visitor Area', 'Ashford', 'WA', 46.9144, -121.6422,
 'Highest road-accessible point in Mt Rainier NP at 6,400 feet — clearest mountain view, broad alpine ridge.',
 'public', array['Mountain','Overlook','Iconic'], true, 'likely',
 'NPS Mt Rainier commercial photography permit required.',
 'published', 'curated_v1', 4.8, 90),

-- ── Port Angeles, WA (Olympic NP gateway) ────────────────────────────────
('Hurricane Ridge', 'Port Angeles', 'WA', 47.9697, -123.4983,
 '5,200-foot ridge overlooking the Olympic Mountains — meadows, mountain goats, the entire Olympic range below.',
 'public', array['Mountain','Iconic','Overlook'], true, 'likely',
 'NPS Olympic commercial photography permit required.',
 'published', 'curated_v1', 4.8, 90),
('Hoh Rain Forest — Hall of Mosses', 'Port Angeles', 'WA', 47.8606, -123.9342,
 'Old-growth Sitka spruce + bigleaf maples draped in club moss — Spielberg-set primeval rainforest atmosphere.',
 'public', array['Forest','Iconic','Outdoor'], true, 'likely',
 'NPS Olympic commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),
('Ruby Beach', 'Port Angeles', 'WA', 47.7117, -124.4131,
 'Driftwood-strewn Pacific beach with sea stacks at the surf line — moody Pacific Northwest coast at its purest.',
 'public', array['Beach','Coastal','Iconic'], true, 'likely',
 'NPS Olympic commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),

-- ── West Glacier, MT ──────────────────────────────────────────────────────
('Lake McDonald', 'West Glacier', 'MT', 48.5186, -113.9844,
 'Largest lake in Glacier NP — multicolored pebble shore, glacier-scarred peaks beyond, the historic Lake McDonald Lodge nearby.',
 'public', array['Lake','Mountain','Iconic'], true, 'likely',
 'NPS Glacier commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Going-to-the-Sun Road — Logan Pass', 'West Glacier', 'MT', 48.6961, -113.7172,
 '6,646-foot Continental Divide pass — wildflower meadows, mountain goats, the Hidden Lake overlook hike.',
 'public', array['Mountain','Iconic','Outdoor'], true, 'likely',
 'NPS Glacier commercial photography permit required; vehicle reservation needed in summer.',
 'published', 'curated_v1', 4.9, 94),
('Many Glacier — Swiftcurrent Lake', 'West Glacier', 'MT', 48.8000, -113.6586,
 'Glacier-fed lake with the historic Many Glacier Hotel on the shore — Grinnell Glacier and Mt Gould rising beyond.',
 'public', array['Lake','Mountain','Architecture'], true, 'likely',
 'NPS Glacier commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),

-- ── West Yellowstone, MT ──────────────────────────────────────────────────
('Old Faithful', 'West Yellowstone', 'MT', 44.4605, -110.8281,
 'Yellowstone''s most-famous geyser — 130-foot eruption every 60-110 minutes, viewing benches arranged in a horseshoe.',
 'public', array['Iconic','Outdoor','Geothermal'], true, 'likely',
 'NPS Yellowstone commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Grand Prismatic Spring', 'West Yellowstone', 'MT', 44.5253, -110.8381,
 'Largest hot spring in the US — vivid orange-red rim, blue center, best from the overlook trail above the Midway Geyser Basin.',
 'public', array['Iconic','Outdoor','Geothermal'], true, 'likely',
 'NPS Yellowstone commercial photography permit required.',
 'published', 'curated_v1', 4.9, 94),
('Lower Falls of the Yellowstone — Artist Point', 'West Yellowstone', 'MT', 44.7197, -110.4781,
 '308-foot waterfall in the Grand Canyon of the Yellowstone — yellow rhyolite walls framing, Artist Point the iconic angle.',
 'public', array['Waterfall','Canyon','Iconic'], true, 'likely',
 'NPS Yellowstone commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),

-- ── Gatlinburg, TN (Smokies gateway) ──────────────────────────────────────
('Clingmans Dome', 'Gatlinburg', 'TN', 35.5628, -83.4986,
 'Highest point in the Smokies at 6,643 feet — observation tower with 360° rolling-blue-mountain views.',
 'public', array['Mountain','Overlook','Iconic'], true, 'likely',
 'NPS Great Smoky Mountains commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),
('Cades Cove Loop', 'Gatlinburg', 'TN', 35.6047, -83.7733,
 '11-mile auto loop through a wide mountain valley — historic log cabins, deer + black-bear sightings, peak fall color.',
 'public', array['Mountain','Outdoor','Historic'], true, 'likely',
 'NPS Great Smoky Mountains commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),
('Roaring Fork Motor Nature Trail', 'Gatlinburg', 'TN', 35.7036, -83.4781,
 '5.5-mile one-way road through old-growth forest — log cabins, Place of a Thousand Drips, mossy boulders.',
 'public', array['Forest','Historic','Outdoor'], true, 'likely',
 'NPS Great Smoky Mountains commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Manteo, NC (Outer Banks) ──────────────────────────────────────────────
('Bodie Island Lighthouse', 'Manteo', 'NC', 35.8186, -75.5631,
 '156-foot black-and-white-banded 1872 lighthouse — boardwalk through marsh leads to it, sunrise over the Atlantic behind.',
 'public', array['Lighthouse','Coastal','Iconic'], true, 'likely',
 'NPS Cape Hatteras National Seashore commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),
('Jockey''s Ridge State Park', 'Manteo', 'NC', 35.9628, -75.6281,
 'Tallest active sand dune system on the East Coast — 80-100 feet, hang gliders, pure dune vistas at sunset.',
 'public', array['Beach','Outdoor','Iconic'], true, 'likely',
 'NC State Parks commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),
('Cape Hatteras Lighthouse', 'Manteo', 'NC', 35.2503, -75.5286,
 '198-foot black-and-white-spiral 1870 lighthouse — tallest brick lighthouse in the US, isolated barrier-island setting.',
 'public', array['Lighthouse','Iconic','Coastal'], true, 'likely',
 'NPS Cape Hatteras National Seashore commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),

-- ── Cape May, NJ ──────────────────────────────────────────────────────────
('Cape May Lighthouse', 'Cape May', 'NJ', 38.9344, -74.9608,
 '157-foot 1859 lighthouse at the very tip of New Jersey — climb to the watch room, dunes + Atlantic on one side, Delaware Bay on the other.',
 'public', array['Lighthouse','Coastal','Historic'], true, 'likely',
 'Mid-Atlantic Center for the Arts handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Sunset Beach', 'Cape May', 'NJ', 38.9342, -74.9744,
 'West-facing Delaware Bay beach — the wreck of the SS Atlantus offshore, sunset directly over the water (rare for the East Coast).',
 'public', array['Beach','Sunset','Coastal'], false, 'unknown',
 'Public beach.',
 'published', 'curated_v1', 4.6, 85),
('Washington Street Mall', 'Cape May', 'NJ', 38.9347, -74.9214,
 'Pedestrianized brick street through downtown — gas lamps, Victorian B&B facades, century-old shade trees.',
 'public', array['Historic','Urban','Pedestrian'], false, 'unknown',
 'Public mall.',
 'published', 'curated_v1', 4.6, 85),

-- ── Tybee Island, GA ──────────────────────────────────────────────────────
('Tybee Island Lighthouse', 'Tybee Island', 'GA', 32.0214, -80.8456,
 '154-foot 1773 lighthouse — Georgia''s oldest, daymark-banded black-white-black, panoramic from the watch room.',
 'public', array['Lighthouse','Historic','Iconic'], true, 'likely',
 'Tybee Island Historical Society handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Tybee Pier and Pavilion', 'Tybee Island', 'GA', 32.0058, -80.8442,
 'Long pier extending into the Atlantic — sunrise over open ocean, weathered wood pilings, pavilion at the base.',
 'public', array['Coastal','Sunrise','Beach'], false, 'unknown',
 'Public pier.',
 'published', 'curated_v1', 4.6, 85),
('North Beach', 'Tybee Island', 'GA', 32.0264, -80.8483,
 'Wide quiet beach below the lighthouse — driftwood, dunes, the ship channel into Savannah passing close to shore.',
 'public', array['Beach','Coastal','Outdoor'], true, 'likely',
 'Tybee Island beach photography permit required for paid sessions.',
 'published', 'curated_v1', 4.6, 85),

-- ── Sturgeon Bay, WI (Door County) ───────────────────────────────────────
('Cave Point County Park', 'Sturgeon Bay', 'WI', 44.9286, -87.1781,
 'Limestone cliffs cut by Lake Michigan — sea-cave arches, wind-blasted cedars, dramatic east-coast Wisconsin shoreline.',
 'public', array['Coastal','Iconic','Outdoor'], true, 'likely',
 'Door County Parks photography permit required for commercial work.',
 'published', 'curated_v1', 4.8, 89),
('Eagle Bluff Lighthouse', 'Sturgeon Bay', 'WI', 45.1700, -87.2278,
 '1868 cream-brick lighthouse on a 76-foot bluff — Peninsula State Park surrounding, cedars + bay views.',
 'public', array['Lighthouse','Historic','Coastal'], true, 'likely',
 'Wisconsin State Parks photo permit required.',
 'published', 'curated_v1', 4.7, 87),
('Door Bluff Headlands', 'Sturgeon Bay', 'WI', 45.2761, -86.9931,
 'Cliff-top park at the very tip of Door County — Lake Michigan on three sides, old-growth cedars, raptor flyway in fall.',
 'public', array['Coastal','Forest','Outdoor'], true, 'unknown',
 'Door County Parks; permit may apply.',
 'published', 'curated_v1', 4.6, 85),

-- ── Ithaca, NY (Finger Lakes) ────────────────────────────────────────────
('Taughannock Falls', 'Ithaca', 'NY', 42.5417, -76.6014,
 '215-foot plunge waterfall — taller than Niagara, half-mile gorge trail leads to the base. Year-round, frozen ice column in winter.',
 'public', array['Waterfall','Iconic','Canyon'], true, 'likely',
 'NY State Parks commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Watkins Glen State Park', 'Ithaca', 'NY', 42.3739, -76.8736,
 '19 waterfalls along a 1.5-mile gorge — stone bridges, the Cavern Cascade, the Rainbow Falls walkway.',
 'public', array['Waterfall','Canyon','Iconic'], true, 'likely',
 'NY State Parks commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Buttermilk Falls', 'Ithaca', 'NY', 42.4128, -76.5167,
 '500-foot cascade just outside Ithaca — Gorge Trail walks beside the main fall, deep swimming pool at the base.',
 'public', array['Waterfall','Canyon','Outdoor'], true, 'likely',
 'NY State Parks commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Galveston, TX ─────────────────────────────────────────────────────────
('Bishop''s Palace', 'Galveston', 'TX', 29.3017, -94.7878,
 '1893 Victorian Gothic mansion — Texas''s most-photographed house, ornate ironwork, red sandstone, stained-glass interior.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Galveston Historical Foundation handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 88),
('The Strand Historic District', 'Galveston', 'TX', 29.3092, -94.7919,
 '19th-century iron-front commercial blocks — survived 1900 hurricane and now restored. Cobblestones, gas lamps, Victorian facades.',
 'public', array['Historic','Architecture','Street'], false, 'unknown',
 'Public sidewalks; respect storefronts.',
 'published', 'curated_v1', 4.6, 85),
('Galveston Beach + Pleasure Pier', 'Galveston', 'TX', 29.2858, -94.7892,
 'Gulf-front beaches with the historic Pleasure Pier — neon-lit Ferris wheel at dusk, 32 miles of sand and seawall promenade.',
 'public', array['Beach','Coastal','Iconic'], false, 'unknown',
 'Public beach; commercial crews check with city.',
 'published', 'curated_v1', 4.5, 84),

-- ── Mystic, CT ────────────────────────────────────────────────────────────
('Mystic Seaport Museum', 'Mystic', 'CT', 41.3683, -71.9650,
 'Recreated 19th-century coastal village + working shipyard — historic schooners docked, period storefronts, the Charles W. Morgan whaling ship.',
 'public', array['Historic','Waterfront','Coastal'], true, 'likely',
 'Mystic Seaport handles commercial photography requests.',
 'published', 'curated_v1', 4.8, 89),
('Mystic River Bascule Bridge', 'Mystic', 'CT', 41.3553, -71.9650,
 '1922 counterweighted drawbridge — opens regularly for sailboats, Mystic''s defining downtown landmark.',
 'public', array['Bridge','Historic','Waterfront'], false, 'unknown',
 'Public bridge.',
 'published', 'curated_v1', 4.6, 85),
('Olde Mistick Village', 'Mystic', 'CT', 41.3672, -71.9694,
 '1700s Colonial-style village shopping district — white-painted clapboard, water mill, formal gardens.',
 'public', array['Historic','Architecture','Street'], false, 'unknown',
 'Public walking village.',
 'published', 'curated_v1', 4.4, 82);
