-- Twin Cities (MSP) seed expansion. The original 20260426_seed_top_metros
-- shipped five Minneapolis entries and zero St. Paul entries — a beta
-- tester based in St. Paul reported "near me" returning ~5 results
-- across the whole metro. Add curated St. Paul locations + a handful
-- more popular Minneapolis spots so the metro has reasonable coverage
-- when a photographer based there opens the Explore map.

insert into public.locations (
  name, city, state, latitude, longitude, description, access_type, tags,
  permit_required, permit_certainty, permit_notes,
  status, source, rating, quality_score
) values

-- ── St. Paul, MN ───────────────────────────────────────────────────────────
('Cathedral of St. Paul', 'St. Paul', 'MN', 44.9466, -93.1093,
 'Iconic 1915 Beaux-Arts cathedral on Cathedral Hill — copper dome, marble interior, dramatic city overlook from the front steps.',
 'public', array['Architecture','Iconic','Historic'], true, 'likely',
 'Cathedral admin office requires sign-off for paid photography inside; exterior shots from the steps are typically fine.',
 'published', 'curated_v1', 4.7, 89),
('Como Park Conservatory', 'St. Paul', 'MN', 44.9824, -93.1521,
 'Victorian-style glass conservatory in Como Park — palm dome, sunken garden, year-round greenery for indoor shoots in winter.',
 'public', array['Garden','Architecture','Indoor'], true, 'likely',
 'Saint Paul Parks photo permit required for organized shoots inside the conservatory.',
 'published', 'curated_v1', 4.6, 87),
('Como Park — Lake Como', 'St. Paul', 'MN', 44.9774, -93.1490,
 'Lakeside park with mature trees, walking paths, and a 1905 pavilion. Family-session friendly.',
 'public', array['Park','Waterfront','Trees'], false, 'likely',
 'Saint Paul Parks photo permit applies for crews.',
 'published', 'curated_v1', 4.4, 83),
('Landmark Center', 'St. Paul', 'MN', 44.9444, -93.0967,
 '1902 Romanesque Revival former federal courthouse — pink granite, Cortile atrium, downtown St. Paul backdrop.',
 'public', array['Architecture','Historic','Indoor'], true, 'likely',
 'Landmark Center events office handles photography permissions for atrium + interior spaces.',
 'published', 'curated_v1', 4.5, 85),
('Summit Avenue', 'St. Paul', 'MN', 44.9410, -93.1310,
 'Longest Victorian boulevard in the country — mansions, mature elms, brownstone-lined sidewalks.',
 'public', array['Historic','Architecture','Street'], false, 'unknown',
 'Public sidewalks; respect private property — most homes are still residences.',
 'published', 'curated_v1', 4.4, 82),
('Harriet Island Regional Park', 'St. Paul', 'MN', 44.9388, -93.0907,
 'Mississippi riverfront park facing the downtown skyline — paved paths, the historic Wigington Pavilion, riverboat docks.',
 'public', array['Waterfront','Skyline','Park'], true, 'likely',
 'Saint Paul Parks photo permit applies.',
 'published', 'curated_v1', 4.5, 84),
('Mears Park', 'St. Paul', 'MN', 44.9486, -93.0871,
 'Tree-lined urban square in Lowertown — fountain, brick paths, exposed-brick warehouse buildings on every side.',
 'public', array['Urban','Trees','Architecture'], false, 'likely',
 'Saint Paul Parks permit for crews.',
 'published', 'curated_v1', 4.3, 80),
('Indian Mounds Regional Park', 'St. Paul', 'MN', 44.9418, -93.0533,
 'Bluff-top park with sweeping views over the Mississippi River and downtown St. Paul skyline.',
 'public', array['Skyline','Bluff','Outdoor'], false, 'likely',
 'Saint Paul Parks permit applies.',
 'published', 'curated_v1', 4.4, 82),

-- ── Minneapolis, MN (additional spots beyond the original five) ────────────
('Theodore Wirth Park — Quaking Bog', 'Minneapolis', 'MN', 44.9933, -93.3243,
 'Boardwalk through a tamarack bog inside Wirth Park — moody, wooded, completely different vibe from the lake parks.',
 'public', array['Forest','Nature','Boardwalk'], true, 'likely',
 'Minneapolis Park & Rec photo permit required for organized shoots.',
 'published', 'curated_v1', 4.4, 81),
('Loring Park', 'Minneapolis', 'MN', 44.9711, -93.2843,
 'Downtown lakeside park — Loring Pond, the iconic footbridge to the Sculpture Garden, skyline backdrop.',
 'public', array['Park','Skyline','Bridge'], true, 'likely',
 'Minneapolis Park & Rec photo permit applies.',
 'published', 'curated_v1', 4.5, 84),
('Bde Maka Ska (Lake Calhoun)', 'Minneapolis', 'MN', 44.9484, -93.3093,
 'Largest of the Chain of Lakes — paved paths, sailboats, sunset views over the western shore.',
 'public', array['Waterfront','Park','Sunset'], false, 'likely',
 'Minneapolis Park & Rec photo permit applies for crews.',
 'published', 'curated_v1', 4.5, 84),
('Boom Island Park', 'Minneapolis', 'MN', 44.9912, -93.2682,
 'Riverside park looking back at Stone Arch Bridge and the downtown skyline — popular boardwalk + lighthouse replica.',
 'public', array['Skyline','Waterfront','Bridge'], true, 'likely',
 'Minneapolis Park & Rec photo permit applies.',
 'published', 'curated_v1', 4.5, 85),
('Northeast Minneapolis Arts District', 'Minneapolis', 'MN', 45.0017, -93.2515,
 'Murals, exposed brick, industrial textures — a few blocks of warehouses-turned-galleries with photogenic walls on every corner.',
 'public', array['Murals','Urban','Industrial'], false, 'unknown',
 'Public sidewalks; some murals are on private buildings — respect signage.',
 'published', 'curated_v1', 4.5, 84),
('Foshay Tower Observation Deck', 'Minneapolis', 'MN', 44.9759, -93.2718,
 '1929 limestone tower — open-air 30th-floor observation deck with 360° downtown views.',
 'public', array['Skyline','Architecture','Indoor'], true, 'likely',
 'W Minneapolis (the hotel inside Foshay) handles photo bookings for the deck.',
 'published', 'curated_v1', 4.5, 83),
('Lake Harriet Bandshell', 'Minneapolis', 'MN', 44.9226, -93.3060,
 'Pastel-trimmed Victorian bandshell on the north shore of Lake Harriet — iconic backdrop, paved promenade.',
 'public', array['Waterfront','Architecture','Iconic'], true, 'likely',
 'Minneapolis Park & Rec photo permit applies.',
 'published', 'curated_v1', 4.6, 86);
