-- Top-50 metro coverage expansion. The original 20260426_seed_top_metros
-- covered ~28 metros at 5 locations each. This migration fills in 21
-- additional metros (the rest of the US top 50 by metro population)
-- with 3 well-known photogenic spots each, so a photographer in
-- Cincinnati, Cleveland, Sacramento, etc. opens the Explore map and
-- finds something nearby instead of staring at an empty radius.
--
-- Coordinates are accurate to within a block for famous landmarks and
-- ballpark for districts. Permit info is conservative — most rows are
-- flagged 'unknown' or 'likely' so photographers verify with the venue
-- before a paid shoot. Re-running this file will create duplicate rows;
-- run once.

insert into public.locations (
  name, city, state, latitude, longitude, description, access_type, tags,
  permit_required, permit_certainty, permit_notes,
  status, source, rating, quality_score
) values

-- ── San Antonio, TX ───────────────────────────────────────────────────────
('The Alamo', 'San Antonio', 'TX', 29.4260, -98.4861,
 '1718 Spanish mission and the most-photographed landmark in Texas — limestone facade, oak-shaded plaza in front.',
 'public', array['Historic','Iconic','Architecture'], true, 'likely',
 'Daughters of the Republic of Texas / Alamo Trust requires permission for commercial photography.',
 'published', 'curated_v1', 4.7, 88),
('San Antonio River Walk', 'San Antonio', 'TX', 29.4252, -98.4946,
 'Cypress-lined walkways one level below downtown — stone bridges, restaurants, water taxis. Best at golden hour or after dark with the lights.',
 'public', array['Waterfront','Urban','Iconic'], false, 'likely',
 'City of San Antonio permit required for crews with equipment.',
 'published', 'curated_v1', 4.7, 89),
('Mission San José', 'San Antonio', 'TX', 29.3536, -98.4781,
 'Largest of the San Antonio Missions — restored 18th-century Spanish colonial church with the iconic Rose Window.',
 'public', array['Historic','Architecture','Religious'], true, 'likely',
 'National Park Service photo permit required for organized shoots.',
 'published', 'curated_v1', 4.6, 86),

-- ── St. Louis, MO ─────────────────────────────────────────────────────────
('Gateway Arch', 'St. Louis', 'MO', 38.6247, -90.1848,
 '630-foot stainless steel monument and the symbol of St. Louis — sweeping curves, Mississippi riverfront framing.',
 'public', array['Iconic','Architecture','Modernist'], true, 'likely',
 'NPS photo permit required for commercial photography on Arch grounds.',
 'published', 'curated_v1', 4.8, 91),
('Forest Park', 'St. Louis', 'MO', 38.6357, -90.2845,
 '1,300-acre Victorian-era park hosting the World\'s Fair Pavilion, lagoons, mature oaks, and the Saint Louis Art Museum.',
 'public', array['Park','Architecture','Outdoor'], true, 'likely',
 'Forest Park Forever / city permit required for organized shoots.',
 'published', 'curated_v1', 4.7, 88),
('The Old Courthouse', 'St. Louis', 'MO', 38.6262, -90.1900,
 'Domed 1839 Federal Greek Revival courthouse — site of the Dred Scott trials, framed by the Arch behind.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'NPS / Gateway Arch park permit applies for commercial use.',
 'published', 'curated_v1', 4.6, 85),

-- ── Pittsburgh, PA ────────────────────────────────────────────────────────
('Mount Washington Overlook', 'Pittsburgh', 'PA', 40.4326, -80.0089,
 'Cliffside view from Grandview Avenue — three rivers meeting Pittsburgh\'s downtown skyline, especially dramatic at blue hour.',
 'public', array['Skyline','Overlook','Iconic'], false, 'likely',
 'Public sidewalk; large crews may need a city permit.',
 'published', 'curated_v1', 4.8, 91),
('Phipps Conservatory', 'Pittsburgh', 'PA', 40.4392, -79.9479,
 '1893 Victorian glasshouse in Schenley Park — palm court, sunken garden, year-round greenery for indoor sessions.',
 'public', array['Garden','Architecture','Indoor'], true, 'likely',
 'Phipps events team handles photography permissions.',
 'published', 'curated_v1', 4.7, 88),
('Roberto Clemente Bridge', 'Pittsburgh', 'PA', 40.4458, -80.0027,
 'Self-anchored suspension bridge in Allegheny Yellow — lattice girders, downtown skyline behind, riverside paths underneath.',
 'public', array['Bridge','Skyline','Iconic'], false, 'unknown',
 'Public bridge; verify if pedestrianized for events.',
 'published', 'curated_v1', 4.5, 84),

-- ── Cincinnati, OH ────────────────────────────────────────────────────────
('John A. Roebling Suspension Bridge', 'Cincinnati', 'OH', 39.0928, -84.5108,
 '1866 blue suspension bridge over the Ohio River — predecessor to the Brooklyn Bridge by the same designer. Cincinnati skyline behind.',
 'public', array['Bridge','Skyline','Historic'], false, 'likely',
 'Pedestrian access; commercial crews should check with KYTC.',
 'published', 'curated_v1', 4.7, 88),
('Smale Riverfront Park', 'Cincinnati', 'OH', 39.0969, -84.5073,
 'Modern riverfront park with the Roebling Bridge as backdrop — fountains, lawns, the iconic flying-pig sculpture.',
 'public', array['Park','Waterfront','Skyline'], true, 'likely',
 'Cincinnati Parks photo permit applies for crews.',
 'published', 'curated_v1', 4.5, 84),
('Eden Park', 'Cincinnati', 'OH', 39.1141, -84.4934,
 'Hilltop park overlooking the Ohio River — Krohn Conservatory glasshouse, Mirror Lake reflecting pool, mature oaks.',
 'public', array['Park','Overlook','Garden'], true, 'likely',
 'Cincinnati Parks photo permit applies.',
 'published', 'curated_v1', 4.6, 85),

-- ── Cleveland, OH ─────────────────────────────────────────────────────────
('Cleveland Museum of Art — Atrium', 'Cleveland', 'OH', 41.5093, -81.6126,
 'Glass-roofed atrium connecting the original 1916 Beaux-Arts wing to the new wings — soaring scale, free admission.',
 'public', array['Architecture','Indoor','Modernist'], true, 'likely',
 'CMA staff handles photo permissions for the atrium and galleries.',
 'published', 'curated_v1', 4.7, 87),
('Edgewater Park', 'Cleveland', 'OH', 41.4895, -81.7376,
 'Lake Erie beach park with Cleveland\'s skyline framed across the water — perfect for sunset sessions.',
 'public', array['Beach','Skyline','Sunset'], false, 'likely',
 'Cleveland Metroparks photo permit applies.',
 'published', 'curated_v1', 4.5, 84),
('West Side Market', 'Cleveland', 'OH', 41.4847, -81.7028,
 '1912 yellow-brick public market hall — vaulted ceiling, vendor stalls, dramatic side aisles for editorial shoots.',
 'public', array['Architecture','Indoor','Historic'], true, 'likely',
 'Market manager handles photography requests; busiest on Saturdays.',
 'published', 'curated_v1', 4.6, 85),

-- ── Columbus, OH ──────────────────────────────────────────────────────────
('Ohio Statehouse', 'Columbus', 'OH', 39.9622, -83.0007,
 '1857 Greek Revival statehouse — limestone facade, formal gardens, dramatic rotunda accessible to the public.',
 'public', array['Historic','Architecture','Government'], true, 'likely',
 'Capitol Square Foundation handles photography permissions.',
 'published', 'curated_v1', 4.6, 85),
('Franklin Park Conservatory', 'Columbus', 'OH', 39.9701, -82.9501,
 '1895 Victorian glasshouse with biome rooms (Himalayan, desert, rainforest) and the outdoor Chihuly glass garden.',
 'public', array['Garden','Architecture','Indoor'], true, 'likely',
 'Conservatory events office for paid photography.',
 'published', 'curated_v1', 4.7, 87),
('Short North Arts District', 'Columbus', 'OH', 39.9776, -83.0049,
 'High Street neighborhood with arched gateways, murals, and brick storefronts — a few blocks of urban texture.',
 'public', array['Urban','Murals','Architecture'], false, 'unknown',
 'Public sidewalks; respect private storefronts.',
 'published', 'curated_v1', 4.4, 82),

-- ── Milwaukee, WI ─────────────────────────────────────────────────────────
('Milwaukee Art Museum — Quadracci Pavilion', 'Milwaukee', 'WI', 43.0408, -87.8970,
 'Calatrava\'s 2001 sail-like white wing — the moving Burke Brise Soleil opens daily, Lake Michigan behind.',
 'public', array['Architecture','Modernist','Iconic'], true, 'likely',
 'MAM events team handles paid photography on the grounds.',
 'published', 'curated_v1', 4.8, 90),
('Bronze Fonz', 'Milwaukee', 'WI', 43.0397, -87.9105,
 'Riverside statue of the Happy Days character — kitsch landmark on the Milwaukee Riverwalk, easy crowd-pleaser shot.',
 'public', array['Iconic','Urban','Riverwalk'], false, 'unknown',
 'Public sidewalk on the riverwalk.',
 'published', 'curated_v1', 4.2, 78),
('Lake Park', 'Milwaukee', 'WI', 43.0716, -87.8758,
 'Olmsted-designed bluff park overlooking Lake Michigan — stone lighthouse, ravine trails, mature oaks.',
 'public', array['Park','Lake','Outdoor'], true, 'likely',
 'Milwaukee County Parks permit required for crews.',
 'published', 'curated_v1', 4.5, 84),

-- ── Sacramento, CA ────────────────────────────────────────────────────────
('California State Capitol', 'Sacramento', 'CA', 38.5766, -121.4934,
 '1874 white-domed neoclassical capitol — formal rose garden in front, gold-leaf details indoors.',
 'public', array['Historic','Architecture','Government'], true, 'likely',
 'California State Parks permit required for commercial photography.',
 'published', 'curated_v1', 4.6, 85),
('Tower Bridge', 'Sacramento', 'CA', 38.5805, -121.5060,
 'Gold-painted vertical-lift bridge over the Sacramento River — connects downtown to West Sacramento. Iconic at sunset.',
 'public', array['Bridge','Iconic','Sunset'], false, 'likely',
 'Public bridge with sidewalks; large crews check with city.',
 'published', 'curated_v1', 4.5, 84),
('Old Sacramento Waterfront', 'Sacramento', 'CA', 38.5837, -121.5045,
 'Restored 1850s Gold Rush-era district — wooden boardwalks, vintage facades, paddlewheel riverboats.',
 'public', array['Historic','Waterfront','Western'], true, 'likely',
 'Old Sacramento permit required for commercial use.',
 'published', 'curated_v1', 4.5, 84),

-- ── Salt Lake City, UT ────────────────────────────────────────────────────
('Salt Lake Temple Square', 'Salt Lake City', 'UT', 40.7708, -111.8920,
 'Granite temple, Tabernacle, and reflecting pools at the heart of SLC — meticulously kept gardens year-round.',
 'public', array['Architecture','Historic','Religious'], true, 'likely',
 'Church grounds — wedding photography by appointment; commercial shoots require permission.',
 'published', 'curated_v1', 4.7, 87),
('Bonneville Salt Flats', 'Salt Lake City', 'UT', 40.7611, -113.8772,
 'Endless white salt flats — surreal, otherworldly photo conditions an hour west of SLC. Best fall through spring.',
 'public', array['Desert','Iconic','Outdoor'], false, 'unknown',
 'BLM land — public access; verify conditions before driving on the flats.',
 'published', 'curated_v1', 4.8, 89),
('Ensign Peak Trail', 'Salt Lake City', 'UT', 40.7886, -111.8918,
 'Short hike above downtown — panoramic Salt Lake Valley + Wasatch + Great Salt Lake views from the peak.',
 'public', array['Hike','Overlook','Outdoor'], false, 'unknown',
 'Public trail; small parking lot — get there early.',
 'published', 'curated_v1', 4.5, 84),

-- ── Orlando, FL ───────────────────────────────────────────────────────────
('Lake Eola Park', 'Orlando', 'FL', 28.5440, -81.3724,
 'Downtown Orlando lake park — swan boats, the iconic fountain, skyline framing. The defining downtown photo spot.',
 'public', array['Park','Waterfront','Skyline'], true, 'likely',
 'Orlando Parks permit required for crews.',
 'published', 'curated_v1', 4.6, 85),
('Harry P. Leu Gardens', 'Orlando', 'FL', 28.5660, -81.3611,
 '50-acre botanical garden — rose garden, butterfly garden, Spanish-moss draped oaks, 1888 farmhouse.',
 'public', array['Garden','Outdoor','Tropical'], true, 'likely',
 'Leu Gardens charges a photo permit fee for paid sessions.',
 'published', 'curated_v1', 4.6, 85),
('Winter Park Boat Tour Canals', 'Orlando', 'FL', 28.5982, -81.3503,
 'Cypress-lined chain-of-lakes canals winding through historic Winter Park — passes lakefront mansions and Rollins College.',
 'public', array['Waterfront','Tropical','Architecture'], true, 'likely',
 'Boat tour available; private boat access also fine.',
 'published', 'curated_v1', 4.5, 84),

-- ── Raleigh, NC ───────────────────────────────────────────────────────────
('North Carolina State Capitol', 'Raleigh', 'NC', 35.7806, -78.6396,
 '1840 Greek Revival capitol — granite facade, Union Square gardens, oaks lining every approach.',
 'public', array['Historic','Architecture','Government'], true, 'likely',
 'NC Capitol staff handles commercial photography permissions.',
 'published', 'curated_v1', 4.5, 84),
('JC Raulston Arboretum', 'Raleigh', 'NC', 35.7967, -78.6985,
 '10-acre teaching arboretum at NC State — themed gardens, including the Japanese garden and color/lattice walks.',
 'public', array['Garden','Outdoor','Trees'], true, 'likely',
 'Photo permit required for paid sessions.',
 'published', 'curated_v1', 4.6, 85),
('Pullen Park', 'Raleigh', 'NC', 35.7831, -78.6680,
 '1887 Victorian-era park with a 1911 carousel, paddleboats, and oak-lined paths — pure nostalgia for family sessions.',
 'public', array['Park','Family','Vintage'], true, 'likely',
 'Raleigh Parks permit applies for crews.',
 'published', 'curated_v1', 4.5, 83),

-- ── Richmond, VA ──────────────────────────────────────────────────────────
('Virginia State Capitol', 'Richmond', 'VA', 37.5394, -77.4338,
 'Jefferson-designed 1788 neoclassical capitol — white columns, formal grounds, the only state capitol Jefferson designed.',
 'public', array['Historic','Architecture','Government'], true, 'likely',
 'Capitol staff requires permission for commercial photography.',
 'published', 'curated_v1', 4.6, 85),
('Maymont Italian Garden', 'Richmond', 'VA', 37.5371, -77.4767,
 '100-acre Gilded Age estate with Italian garden, Japanese garden, and the original 1893 mansion — hilltop river views.',
 'public', array['Garden','Historic','Architecture'], true, 'likely',
 'Maymont charges a photo permit fee — wedding photography popular here.',
 'published', 'curated_v1', 4.7, 88),
('Belle Isle', 'Richmond', 'VA', 37.5350, -77.4530,
 'Wooded island in the James River — granite outcrops, foot-bridge access, rapids and quarry pools, downtown skyline.',
 'public', array['River','Outdoor','Skyline'], false, 'unknown',
 'James River Park System — public island; check water levels.',
 'published', 'curated_v1', 4.5, 84),

-- ── Louisville, KY ────────────────────────────────────────────────────────
('Big Four Bridge', 'Louisville', 'KY', 38.2614, -85.7414,
 '1895 truss-bridge converted to a pedestrian span across the Ohio River — gold approach ramps, Louisville skyline behind.',
 'public', array['Bridge','Skyline','Iconic'], false, 'likely',
 'Pedestrian-only; crews check with Waterfront Park.',
 'published', 'curated_v1', 4.7, 88),
('Cherokee Park — Scenic Loop', 'Louisville', 'KY', 38.2367, -85.6939,
 '409-acre Olmsted park — rolling hills, mature trees, Beargrass Creek crossings, and the scenic loop drive for any mood.',
 'public', array['Park','Outdoor','Trees'], true, 'likely',
 'Louisville Metro Parks permit applies for crews.',
 'published', 'curated_v1', 4.6, 85),
('Old Louisville', 'Louisville', 'KY', 38.2289, -85.7619,
 'Largest collection of restored Victorian mansions in the US — Central Park, ironwork fences, gas lamps still in use.',
 'public', array['Historic','Architecture','Street'], false, 'unknown',
 'Public sidewalks; respect private homes.',
 'published', 'curated_v1', 4.5, 84),

-- ── Oklahoma City, OK ─────────────────────────────────────────────────────
('Oklahoma City National Memorial', 'Oklahoma City', 'OK', 35.4727, -97.5172,
 'Reflecting pool flanked by the Gates of Time and 168 empty chairs — solemn, deeply moving for tasteful editorial work.',
 'public', array['Memorial','Architecture','Iconic'], true, 'likely',
 'NPS / Memorial staff requires permission for commercial photography.',
 'published', 'curated_v1', 4.8, 89),
('Bricktown Canal', 'Oklahoma City', 'OK', 35.4634, -97.5104,
 'Renovated warehouse district with a downtown canal — water taxis, brick walls, cafe lighting at night.',
 'public', array['Urban','Waterfront','Architecture'], false, 'likely',
 'Public canal-side paths; bigger crews check with Bricktown.',
 'published', 'curated_v1', 4.4, 82),
('Myriad Botanical Gardens — Crystal Bridge', 'Oklahoma City', 'OK', 35.4660, -97.5204,
 '17-acre garden centered on the Crystal Bridge tropical conservatory — modernist architecture, year-round greenery.',
 'public', array['Garden','Architecture','Indoor'], true, 'likely',
 'Garden events team for paid photography.',
 'published', 'curated_v1', 4.6, 85),

-- ── Buffalo, NY ───────────────────────────────────────────────────────────
('Niagara Falls — American Side', 'Buffalo', 'NY', 43.0828, -79.0710,
 'World\'s most famous waterfall, 30 minutes from downtown Buffalo — Goat Island, Bridal Veil, the rainbow at the right hour.',
 'public', array['Waterfall','Iconic','Outdoor'], true, 'likely',
 'Niagara Falls State Park requires a permit for commercial photography.',
 'published', 'curated_v1', 4.9, 92),
('Frank Lloyd Wright\'s Darwin Martin House', 'Buffalo', 'NY', 42.9415, -78.8662,
 '1905 Prairie-style estate — horizontal lines, art-glass windows, restored interiors and gardens.',
 'public', array['Architecture','Historic','Iconic'], true, 'likely',
 'Martin House Conservancy handles paid photography requests.',
 'published', 'curated_v1', 4.7, 88),
('Buffalo City Hall Observation Deck', 'Buffalo', 'NY', 42.8866, -78.8788,
 '1931 Art Deco city hall — 32nd-floor observation deck with 360° views over downtown, Lake Erie, and the Peace Bridge.',
 'public', array['Architecture','Skyline','Indoor'], false, 'likely',
 'City Hall is publicly accessible; deck open weekdays.',
 'published', 'curated_v1', 4.6, 85),

-- ── Birmingham, AL ────────────────────────────────────────────────────────
('Vulcan Park & Museum', 'Birmingham', 'AL', 33.4892, -86.7916,
 'Hilltop park with a 56-foot iron statue of Vulcan — overlooks downtown Birmingham; especially good at sunset.',
 'public', array['Overlook','Iconic','Sunset'], true, 'likely',
 'Vulcan Park Foundation requires a photo permit for paid sessions.',
 'published', 'curated_v1', 4.7, 87),
('Sloss Furnaces', 'Birmingham', 'AL', 33.5217, -86.7997,
 '1882 industrial site — rusted furnaces, towering smokestacks, brick chimneys. Striking industrial backdrop.',
 'public', array['Industrial','Historic','Urban'], true, 'likely',
 'Sloss Furnaces National Historic Landmark charges a photography fee.',
 'published', 'curated_v1', 4.6, 85),
('Birmingham Botanical Gardens', 'Birmingham', 'AL', 33.4956, -86.7900,
 '67-acre free public garden — Japanese garden, conservatory, formal rose garden, fern glade.',
 'public', array['Garden','Outdoor','Tropical'], true, 'likely',
 'Garden events office for paid photography.',
 'published', 'curated_v1', 4.6, 86),

-- ── Providence, RI ────────────────────────────────────────────────────────
('Rhode Island State House', 'Providence', 'RI', 41.8307, -71.4144,
 '1904 white Georgia-marble capitol — fourth-largest unsupported marble dome in the world, formal grounds.',
 'public', array['Historic','Architecture','Government'], true, 'likely',
 'State House staff handles commercial photography permissions.',
 'published', 'curated_v1', 4.6, 85),
('Roger Williams Park — Japanese Garden', 'Providence', 'RI', 41.7849, -71.4117,
 '435-acre Victorian park with a Japanese garden, the Temple of Music, lakes, and the Botanical Center conservatory.',
 'public', array['Park','Garden','Architecture'], true, 'likely',
 'Providence Parks permit required for crews.',
 'published', 'curated_v1', 4.6, 85),
('Benefit Street', 'Providence', 'RI', 41.8259, -71.4032,
 '"Mile of History" — preserved 18th- and 19th-century homes, gas lamps, brick sidewalks, oak trees.',
 'public', array['Historic','Architecture','Street'], false, 'unknown',
 'Public sidewalks; respect private homes.',
 'published', 'curated_v1', 4.5, 84),

-- ── Hartford, CT ──────────────────────────────────────────────────────────
('Connecticut State Capitol', 'Hartford', 'CT', 41.7637, -72.6829,
 '1879 High Victorian Gothic — gold-leaf dome, marble interior, Bushnell Park lawn in front.',
 'public', array['Historic','Architecture','Government'], true, 'likely',
 'Capitol Police approval required for commercial photography on grounds.',
 'published', 'curated_v1', 4.5, 84),
('Bushnell Park', 'Hartford', 'CT', 41.7641, -72.6803,
 'America\'s oldest public park (1854) — Memorial Arch, the 1914 Stein & Goldstein carousel, the capitol behind.',
 'public', array['Park','Historic','Iconic'], true, 'likely',
 'Hartford Parks permit applies.',
 'published', 'curated_v1', 4.5, 83),
('Mark Twain House', 'Hartford', 'CT', 41.7678, -72.7012,
 '1874 painted-brick Victorian Gothic — orange-and-black exterior, deep porches, where Twain wrote his major novels.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Mark Twain House staff handles commercial photography.',
 'published', 'curated_v1', 4.6, 85),

-- ── Virginia Beach, VA ────────────────────────────────────────────────────
('Virginia Beach Boardwalk', 'Virginia Beach', 'VA', 36.8516, -75.9764,
 '3-mile oceanfront boardwalk — wide sand beach, the King Neptune statue, sunrise over the Atlantic.',
 'public', array['Beach','Sunrise','Boardwalk'], false, 'likely',
 'City of Virginia Beach permit for crews on the boardwalk.',
 'published', 'curated_v1', 4.5, 84),
('First Landing State Park', 'Virginia Beach', 'VA', 36.9221, -76.0533,
 'Cypress swamps, Spanish moss-draped trails, and the Chesapeake Bay shoreline — surreal Southern photo terrain.',
 'public', array['Park','Forest','Outdoor'], true, 'likely',
 'Virginia State Parks photography permit required.',
 'published', 'curated_v1', 4.6, 85),
('Cape Henry Lighthouse', 'Virginia Beach', 'VA', 36.9258, -76.0096,
 'Original 1792 sandstone lighthouse — climbable, with views of the Chesapeake Bay and the Atlantic. The "first" US public works project.',
 'public', array['Historic','Lighthouse','Coastal'], true, 'likely',
 'Preservation Virginia handles photography permissions.',
 'published', 'curated_v1', 4.6, 85),

-- ── Albuquerque, NM ───────────────────────────────────────────────────────
('Sandia Peak Tramway', 'Albuquerque', 'NM', 35.1903, -106.4275,
 'Aerial tram to a 10,378-foot peak — desert-to-alpine transition, sweeping Rio Grande valley views, sunset reds on the Sandias.',
 'public', array['Overlook','Mountain','Iconic'], true, 'likely',
 'Tramway operations + Cibola NF permit may apply.',
 'published', 'curated_v1', 4.7, 88),
('Old Town Albuquerque', 'Albuquerque', 'NM', 35.0964, -106.6699,
 'Adobe storefronts around a 1706 plaza — San Felipe de Neri church, courtyards, Southwestern textures.',
 'public', array['Historic','Architecture','Southwestern'], false, 'unknown',
 'Public plaza; commercial crews check with city.',
 'published', 'curated_v1', 4.6, 85),
('Petroglyph National Monument', 'Albuquerque', 'NM', 35.1325, -106.7475,
 'Volcanic basalt covered in 400-700-year-old petroglyphs — Boca Negra Canyon trails, desert vistas, dramatic skies.',
 'public', array['Desert','Outdoor','Historic'], true, 'likely',
 'NPS commercial photography permit required.',
 'published', 'curated_v1', 4.5, 84),

-- ── Tucson, AZ ────────────────────────────────────────────────────────────
('Saguaro National Park — East', 'Tucson', 'AZ', 32.1813, -110.7359,
 'Sonoran desert thickly forested with iconic saguaro cacti — sunset desert vistas with the Rincon Mountains behind.',
 'public', array['Desert','National Park','Iconic'], true, 'likely',
 'NPS commercial photography permit required.',
 'published', 'curated_v1', 4.8, 90),
('Mission San Xavier del Bac', 'Tucson', 'AZ', 32.1067, -110.9682,
 '"White Dove of the Desert" — 1797 Spanish colonial mission, brilliant white facade against the desert sky.',
 'public', array['Historic','Architecture','Religious'], true, 'likely',
 'Tohono O\'odham Nation requires permission for commercial photography.',
 'published', 'curated_v1', 4.8, 90),
('Sabino Canyon', 'Tucson', 'AZ', 32.3094, -110.8189,
 'Desert oasis canyon in the Santa Catalina foothills — saguaros, seasonal waterfalls, dramatic rock walls. Easy tram access.',
 'public', array['Desert','Canyon','Outdoor'], true, 'likely',
 'Coronado NF commercial photography permit required.',
 'published', 'curated_v1', 4.7, 88);
