-- Destination + tourist-town seed expansion. The previous seeds covered
-- big metros by population; this batch fills in the small-but-iconic
-- towns photographers actually travel to: Sedona, Santa Fe, Carmel,
-- Big Sur, Newport, Bar Harbor, etc. Photographers route through these
-- for elopements, family sessions, and travel work, so dropping a pin
-- in the Explore map for them is high-leverage.
--
-- Same conventions as prior seeds: coordinates within a block of
-- landmarks, public-knowledge descriptions, conservative permit info.
-- Re-running creates duplicates — run once.

insert into public.locations (
  name, city, state, latitude, longitude, description, access_type, tags,
  permit_required, permit_certainty, permit_notes,
  status, source, rating, quality_score
) values

-- ── Santa Fe, NM ──────────────────────────────────────────────────────────
('Santa Fe Plaza', 'Santa Fe', 'NM', 35.6870, -105.9378,
 '400-year-old central plaza — adobe walls, Native American jewelry market under the Palace of the Governors portal, gold autumn light on cottonwoods.',
 'public', array['Historic','Iconic','Southwestern'], false, 'unknown',
 'Public plaza; commercial crews check with City of Santa Fe.',
 'published', 'curated_v1', 4.8, 91),
('Loretto Chapel', 'Santa Fe', 'NM', 35.6856, -105.9367,
 '1878 Gothic Revival chapel housing the Miraculous Staircase — wrought-iron details, candle-lit interior.',
 'public', array['Historic','Architecture','Religious'], true, 'likely',
 'Loretto Chapel charges a photo permit fee — wedding photography popular.',
 'published', 'curated_v1', 4.7, 88),
('Canyon Road', 'Santa Fe', 'NM', 35.6862, -105.9261,
 'Half-mile of adobe galleries on a tree-lined street — the New Mexican art district, walled gardens, sculpture courtyards.',
 'public', array['Architecture','Southwestern','Historic'], false, 'unknown',
 'Public street; respect private gallery property.',
 'published', 'curated_v1', 4.7, 88),

-- ── Sedona, AZ ────────────────────────────────────────────────────────────
('Cathedral Rock', 'Sedona', 'AZ', 34.8252, -111.7867,
 'Spires of red sandstone rising from oak woodland — most-photographed natural landmark in Arizona, dramatic at sunset.',
 'public', array['Iconic','Outdoor','Sunset'], true, 'likely',
 'Coronado NF commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Chapel of the Holy Cross', 'Sedona', 'AZ', 34.8336, -111.7656,
 '1956 Catholic chapel built into a 200-foot red rock spur — sweeping views over Sedona, modernist concrete cross.',
 'public', array['Architecture','Religious','Iconic'], true, 'likely',
 'Diocese of Phoenix handles commercial photography requests.',
 'published', 'curated_v1', 4.8, 91),
('Bell Rock', 'Sedona', 'AZ', 34.8011, -111.7686,
 'Bell-shaped red sandstone butte — climbable lower slopes, easy access from State Route 179, vortex site.',
 'public', array['Outdoor','Iconic','Mountain'], true, 'likely',
 'Coronado NF commercial photography permit required.',
 'published', 'curated_v1', 4.7, 88),

-- ── Flagstaff, AZ ─────────────────────────────────────────────────────────
('Lowell Observatory — Mars Hill', 'Flagstaff', 'AZ', 35.2030, -111.6646,
 '1894 hilltop observatory where Pluto was discovered — historic dome buildings, ponderosa pines, dark-sky views.',
 'public', array['Historic','Architecture','Mountain'], true, 'likely',
 'Lowell Observatory handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Walnut Canyon National Monument', 'Flagstaff', 'AZ', 35.1719, -111.5083,
 '600-foot deep canyon with 800-year-old Sinagua cliff dwellings — Island Trail puts you at eye level with the rooms.',
 'public', array['Historic','Canyon','Outdoor'], true, 'likely',
 'NPS commercial photography permit required.',
 'published', 'curated_v1', 4.6, 85),
('San Francisco Peaks — Snowbowl', 'Flagstaff', 'AZ', 35.3306, -111.7117,
 '12,633-foot volcanic peaks — aspen groves blazing in autumn, alpine meadows, Arizona''s tallest skyline.',
 'public', array['Mountain','Outdoor','Iconic'], true, 'likely',
 'Coronado NF commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),

-- ── Aspen, CO ─────────────────────────────────────────────────────────────
('Maroon Bells', 'Aspen', 'CO', 39.0708, -106.9890,
 'Twin 14,000-foot peaks reflected in Maroon Lake — most-photographed mountain scene in North America, golden aspens late September.',
 'public', array['Mountain','Iconic','Lake'], true, 'likely',
 'White River NF commercial photography permit required; reservations needed for the access road.',
 'published', 'curated_v1', 4.9, 95),
('Independence Pass', 'Aspen', 'CO', 39.1186, -106.5631,
 '12,095-foot summit on the Continental Divide — alpine tundra, sweeping ridge views, closed in winter.',
 'public', array['Mountain','Outdoor','Overlook'], false, 'likely',
 'White River NF photo permit may apply for crews.',
 'published', 'curated_v1', 4.8, 89),
('Aspen Historic District', 'Aspen', 'CO', 39.1911, -106.8175,
 'Wagner Park, the Hotel Jerome, Victorian-era brick storefronts — preserved silver-mining-era core of Aspen.',
 'public', array['Historic','Architecture','Mountain'], false, 'unknown',
 'Public sidewalks; respect private property.',
 'published', 'curated_v1', 4.6, 85),

-- ── Telluride, CO ─────────────────────────────────────────────────────────
('Bridal Veil Falls', 'Telluride', 'CO', 37.9286, -107.7669,
 '365-foot waterfall — tallest free-falling cascade in Colorado, with the historic 1907 Smuggler-Union Hydroelectric Power Plant at the top.',
 'public', array['Waterfall','Mountain','Outdoor'], false, 'unknown',
 'Public viewing from below; upper area gated.',
 'published', 'curated_v1', 4.8, 89),
('Telluride Gondola — San Sophia Station', 'Telluride', 'CO', 37.9323, -107.8150,
 'Free year-round gondola — 10,540-foot ridge, 360° San Juan Mountains views, autumn aspen runs.',
 'public', array['Mountain','Overlook','Iconic'], false, 'likely',
 'Telluride Mountain Village handles commercial requests.',
 'published', 'curated_v1', 4.9, 91),
('Town Park', 'Telluride', 'CO', 37.9389, -107.8050,
 'East-end park along the San Miguel River — box canyon walls, mature spruces, dramatic mountain framing on every side.',
 'public', array['Park','Mountain','River'], true, 'likely',
 'Telluride Parks permit applies.',
 'published', 'curated_v1', 4.6, 86),

-- ── Jackson, WY ───────────────────────────────────────────────────────────
('Town Square Antler Arches', 'Jackson', 'WY', 43.4799, -110.7624,
 'Four arches built from 14,000+ shed elk antlers — town-square corners, defining Jackson Hole shot.',
 'public', array['Iconic','Western','Urban'], false, 'unknown',
 'Public square; commercial crews check with town.',
 'published', 'curated_v1', 4.6, 85),
('Mormon Row — Moulton Barn', 'Jackson', 'WY', 43.6589, -110.6692,
 'Pioneer-era barn with the Tetons rising directly behind — most-photographed barn in the world.',
 'public', array['Historic','Mountain','Iconic'], true, 'likely',
 'Grand Teton NPS commercial photography permit required.',
 'published', 'curated_v1', 4.9, 94),
('Schwabacher Landing', 'Jackson', 'WY', 43.7253, -110.6706,
 'Beaver-dammed Snake River backwater — Tetons reflected at sunrise, no wind = mirror-perfect water.',
 'public', array['Mountain','Sunrise','River'], true, 'likely',
 'Grand Teton NPS commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),

-- ── Park City, UT ─────────────────────────────────────────────────────────
('Park City Main Street', 'Park City', 'UT', 40.6428, -111.4965,
 'Mining-era brick storefronts on a steep historic street — string lights, Wasatch peaks above, year-round access.',
 'public', array['Historic','Architecture','Mountain'], false, 'unknown',
 'Public street; respect storefronts.',
 'published', 'curated_v1', 4.6, 85),
('Utah Olympic Park', 'Park City', 'UT', 40.7150, -111.5639,
 '2002 Olympic venue — ski jumps, bobsled track, mountain views, the Eccles Olympic Museum.',
 'public', array['Architecture','Mountain','Iconic'], true, 'likely',
 'Olympic Park handles commercial photography requests.',
 'published', 'curated_v1', 4.6, 85),
('Guardsman Pass', 'Park City', 'UT', 40.6033, -111.5575,
 'Scenic dirt road over the Wasatch — wildflower meadows in summer, orange aspen runs in fall, sweeping ridge vistas.',
 'public', array['Mountain','Outdoor','Overlook'], false, 'unknown',
 'Public road; closed in winter.',
 'published', 'curated_v1', 4.7, 87),

-- ── Bozeman, MT ───────────────────────────────────────────────────────────
('M Trail / Bridger Foothills', 'Bozeman', 'MT', 45.7156, -110.9658,
 'Foothills hike with sweeping views over the Gallatin Valley — Bridger and Spanish Peaks framing every angle.',
 'public', array['Mountain','Hike','Overlook'], false, 'likely',
 'Custer Gallatin NF photo permit may apply.',
 'published', 'curated_v1', 4.5, 84),
('Downtown Bozeman — Main Street', 'Bozeman', 'MT', 45.6794, -111.0383,
 'Brick storefronts on a wide western main street — mountain views down every cross street, lit signage at night.',
 'public', array['Historic','Western','Street'], false, 'unknown',
 'Public sidewalks.',
 'published', 'curated_v1', 4.5, 83),
('Palisade Falls', 'Bozeman', 'MT', 45.4858, -110.9486,
 '80-foot waterfall in Hyalite Canyon — short paved trail, ice-climbing destination in winter.',
 'public', array['Waterfall','Mountain','Outdoor'], true, 'likely',
 'Custer Gallatin NF photo permit may apply.',
 'published', 'curated_v1', 4.6, 85),

-- ── Bend, OR ──────────────────────────────────────────────────────────────
('Pilot Butte', 'Bend', 'OR', 44.0533, -121.2711,
 '500-foot volcanic cinder cone in the middle of Bend — short hike or drive to the summit, Cascades panorama.',
 'public', array['Overlook','Mountain','Outdoor'], true, 'likely',
 'Oregon State Parks commercial photography permit required.',
 'published', 'curated_v1', 4.6, 85),
('Smith Rock State Park', 'Bend', 'OR', 44.3667, -121.1383,
 'Welded volcanic tuff cliffs over the Crooked River — climbing mecca, Misery Ridge trail, sunset reds on the rock.',
 'public', array['Outdoor','Mountain','Iconic'], true, 'likely',
 'Oregon State Parks commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),
('Old Mill District', 'Bend', 'OR', 44.0408, -121.3214,
 'Riverside lumber-mill ruins reborn as shops + restaurants — three iconic smokestacks, Deschutes River paths, kayak launch.',
 'public', array['Industrial','Waterfront','Urban'], false, 'unknown',
 'Public paths; large crews check with property management.',
 'published', 'curated_v1', 4.5, 84),

-- ── Cannon Beach, OR ──────────────────────────────────────────────────────
('Haystack Rock', 'Cannon Beach', 'OR', 45.8842, -123.9678,
 '235-foot sea stack at the water''s edge — tide pools at low tide, tufted puffins in summer, the defining Oregon coast shot.',
 'public', array['Coastal','Iconic','Beach'], true, 'likely',
 'Oregon State Parks beach photography permit required for paid sessions.',
 'published', 'curated_v1', 4.9, 93),
('Ecola State Park', 'Cannon Beach', 'OR', 45.9242, -123.9772,
 'Headland park with cliff-edge overlooks — Indian Beach, sea-stack views down the coast, old-growth forest behind.',
 'public', array['Coastal','Park','Forest'], true, 'likely',
 'Oregon State Parks photo permit required.',
 'published', 'curated_v1', 4.8, 90),
('Cannon Beach Downtown', 'Cannon Beach', 'OR', 45.8923, -123.9619,
 'Cedar-shake storefronts a block from the beach — quaint Oregon coast vibe, garden-framed entries.',
 'public', array['Architecture','Street','Coastal'], false, 'unknown',
 'Public sidewalks.',
 'published', 'curated_v1', 4.5, 84),

-- ── Hood River, OR ────────────────────────────────────────────────────────
('Multnomah Falls', 'Hood River', 'OR', 45.5762, -122.1158,
 '620-foot two-tiered waterfall in the Columbia River Gorge — the Benson Footbridge between the upper and lower drops.',
 'public', array['Waterfall','Iconic','Bridge'], true, 'likely',
 'Mt Hood NF + Oregon Parks photo permit required for commercial work.',
 'published', 'curated_v1', 4.9, 94),
('Vista House at Crown Point', 'Hood River', 'OR', 45.5392, -122.2444,
 '1918 octagonal observatory on a 733-foot basalt promontory — sweeping Columbia Gorge view down to the river.',
 'public', array['Architecture','Historic','Overlook'], true, 'likely',
 'Oregon State Parks commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),
('Hood River Waterfront', 'Hood River', 'OR', 45.7128, -121.5181,
 'Columbia River windsurfing + kiteboarding hub — Mount Hood across the river, kite sails painting the sky.',
 'public', array['Waterfront','Mountain','Coastal'], false, 'unknown',
 'Public waterfront.',
 'published', 'curated_v1', 4.6, 85),

-- ── Carmel-by-the-Sea, CA ─────────────────────────────────────────────────
('Carmel Beach', 'Carmel-by-the-Sea', 'CA', 36.5547, -121.9286,
 'White-sand cove with cypress-tree silhouettes — sunset over the Pacific, dog-friendly, ranked among the best California beaches.',
 'public', array['Beach','Iconic','Sunset'], true, 'likely',
 'City of Carmel beach permit required for commercial photography.',
 'published', 'curated_v1', 4.8, 90),
('Carmel Mission Basilica', 'Carmel-by-the-Sea', 'CA', 36.5417, -121.9180,
 '1797 Spanish mission — sandstone facade, basilica with its painted ceiling, walled cemetery + gardens.',
 'public', array['Historic','Architecture','Religious'], true, 'likely',
 'Carmel Mission staff handles commercial photography.',
 'published', 'curated_v1', 4.7, 88),
('Carmel Downtown', 'Carmel-by-the-Sea', 'CA', 36.5552, -121.9233,
 'Storybook-cottage downtown — Hugh Comstock''s fairytale houses, hidden courtyards, no street numbers (the local thing).',
 'public', array['Architecture','Street','Iconic'], false, 'unknown',
 'Public sidewalks; respect private property.',
 'published', 'curated_v1', 4.7, 87),

-- ── Big Sur, CA ───────────────────────────────────────────────────────────
('Bixby Creek Bridge', 'Big Sur', 'CA', 36.3713, -121.9023,
 '1932 concrete arch bridge over the Big Sur coast — most-photographed bridge in California, Pacific stretching to the horizon.',
 'public', array['Bridge','Iconic','Coastal'], true, 'likely',
 'Caltrans + permits for filming on Highway 1.',
 'published', 'curated_v1', 4.9, 95),
('McWay Falls', 'Big Sur', 'CA', 36.1576, -121.6717,
 '80-foot waterfall dropping directly onto a Pacific sand cove — Julia Pfeiffer Burns SP, accessible only via the bluff trail overlook.',
 'public', array['Waterfall','Coastal','Iconic'], true, 'likely',
 'California State Parks photo permit required.',
 'published', 'curated_v1', 4.9, 93),
('Pfeiffer Beach — Keyhole Arch', 'Big Sur', 'CA', 36.2378, -121.8170,
 'Purple-sand beach with the iconic Keyhole rock — winter solstice light beam through the arch is the famous shot.',
 'public', array['Beach','Coastal','Iconic'], true, 'likely',
 'Los Padres NF photo permit required for commercial work.',
 'published', 'curated_v1', 4.8, 90),

-- ── Napa, CA ──────────────────────────────────────────────────────────────
('Castello di Amorosa', 'Napa', 'CA', 38.5567, -122.5439,
 '13th-century-style Tuscan castle winery in Calistoga — drawbridge, courtyards, period interior. Wedding-photography destination.',
 'public', array['Architecture','Historic','Wedding'], true, 'likely',
 'Castello di Amorosa charges photo permit fees for paid sessions.',
 'published', 'curated_v1', 4.7, 88),
('Domaine Carneros', 'Napa', 'CA', 38.2603, -122.3853,
 'Louis XV-style chateau winery — formal terrace overlooking estate vineyards, pink-marble facade, gold-hour glory.',
 'public', array['Architecture','Wedding','Historic'], true, 'likely',
 'Domaine Carneros handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Oxbow Public Market District', 'Napa', 'CA', 38.3014, -122.2864,
 'Riverside marketplace + walking district — string lights, food halls, the Napa River and historic downtown beyond.',
 'public', array['Urban','Waterfront','Architecture'], false, 'unknown',
 'Public sidewalks.',
 'published', 'curated_v1', 4.5, 84),

-- ── Sausalito, CA ─────────────────────────────────────────────────────────
('Sausalito Waterfront', 'Sausalito', 'CA', 37.8590, -122.4853,
 'Houseboat-lined coastline facing San Francisco — Golden Gate views east, ferry boats, Mediterranean-style hillside homes.',
 'public', array['Waterfront','Skyline','Iconic'], false, 'unknown',
 'Public waterfront paths.',
 'published', 'curated_v1', 4.7, 87),
('Marin Headlands — Battery Spencer', 'Sausalito', 'CA', 37.8311, -122.4795,
 'Old WWII gun emplacement directly across from the Golden Gate Bridge — the iconic full-bridge-with-skyline shot.',
 'public', array['Iconic','Bridge','Skyline'], true, 'likely',
 'Golden Gate NRA + NPS commercial photography permit required.',
 'published', 'curated_v1', 4.9, 93),
('Bridgeway Promenade', 'Sausalito', 'CA', 37.8597, -122.4847,
 'Main waterfront promenade — view across to Alcatraz and SF, mooring boats, sea-level cafes.',
 'public', array['Waterfront','Iconic','Urban'], false, 'unknown',
 'Public sidewalk; respect cafes.',
 'published', 'curated_v1', 4.6, 85),

-- ── Leavenworth, WA ───────────────────────────────────────────────────────
('Leavenworth Bavarian Village', 'Leavenworth', 'WA', 47.5965, -120.6614,
 'Entire downtown rebuilt in alpine-Bavarian style — flower-boxed balconies, painted murals, Cascades framing every street.',
 'public', array['Architecture','Iconic','Mountain'], false, 'unknown',
 'Public sidewalks; respect storefronts.',
 'published', 'curated_v1', 4.6, 86),
('Icicle Gorge', 'Leavenworth', 'WA', 47.5814, -120.7706,
 'Granite-walled canyon with the Icicle Creek tumbling through — easy loop trail, photogenic moss + ferns + clear pools.',
 'public', array['Outdoor','River','Forest'], true, 'likely',
 'Wenatchee NF photo permit may apply.',
 'published', 'curated_v1', 4.6, 85),
('Snow Lakes Trailhead — Enchantments', 'Leavenworth', 'WA', 47.5797, -120.7022,
 'Gateway to the Enchantments — granite peaks, alpine larch in October, glacier-fed lakes (though full Enchantments hike is permit-only).',
 'public', array['Mountain','Outdoor','Hike'], true, 'likely',
 'Wenatchee NF photo permit may apply; Enchantments lottery for overnight.',
 'published', 'curated_v1', 4.8, 89),

-- ── Friday Harbor, WA (San Juan Islands) ─────────────────────────────────
('Lime Kiln Point Lighthouse', 'Friday Harbor', 'WA', 48.5158, -123.1530,
 '1919 lighthouse on the rocky west coast of San Juan Island — orca-watching capital of the world, sunsets over Haro Strait.',
 'public', array['Lighthouse','Coastal','Iconic'], true, 'likely',
 'Washington State Parks commercial photography permit required.',
 'published', 'curated_v1', 4.8, 89),
('Roche Harbor Resort', 'Friday Harbor', 'WA', 48.6122, -123.1592,
 'Historic 1886 limeworks village + harbor — white-painted Hotel de Haro, formal gardens, sailboats lining the dock.',
 'public', array['Historic','Waterfront','Architecture'], true, 'likely',
 'Roche Harbor handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('English Camp', 'Friday Harbor', 'WA', 48.5836, -123.1444,
 'Pig War-era British encampment — preserved white wooden buildings, Garrison Bay, formal gardens, the iconic Royal Marines parade ground.',
 'public', array['Historic','Coastal','Outdoor'], true, 'likely',
 'NPS San Juan Island commercial photography permit required.',
 'published', 'curated_v1', 4.7, 86),

-- ── Coeur d''Alene, ID ────────────────────────────────────────────────────
('Tubbs Hill Trail', 'Coeur d''Alene', 'ID', 47.6717, -116.7894,
 '2-mile waterside trail around a forested peninsula — pebbled coves, Lake Coeur d''Alene panoramas at every turn.',
 'public', array['Lake','Outdoor','Hike'], false, 'likely',
 'Coeur d''Alene Parks permit applies for crews.',
 'published', 'curated_v1', 4.7, 87),
('Coeur d''Alene Resort Boardwalk', 'Coeur d''Alene', 'ID', 47.6764, -116.7924,
 'World''s longest floating boardwalk — 3,300 feet around the Coeur d''Alene Resort''s marina, lake-and-mountain views.',
 'public', array['Waterfront','Iconic','Boardwalk'], true, 'unknown',
 'CDA Resort handles commercial photography on the boardwalk.',
 'published', 'curated_v1', 4.6, 85),
('Mineral Ridge Trail', 'Coeur d''Alene', 'ID', 47.5478, -116.8642,
 '3.3-mile loop with sweeping views over Beauty Bay and Wolf Lodge Bay — bald-eagle habitat in winter, autumn colors in October.',
 'public', array['Hike','Lake','Mountain'], false, 'likely',
 'Idaho Panhandle NF photo permit may apply.',
 'published', 'curated_v1', 4.7, 87),

-- ── Bar Harbor, ME ────────────────────────────────────────────────────────
('Cadillac Mountain', 'Bar Harbor', 'ME', 44.3520, -68.2247,
 '1,530-foot summit in Acadia NP — first sunrise in the US (Oct-Mar), pink granite, sweeping ocean views.',
 'public', array['Mountain','Sunrise','Iconic'], true, 'likely',
 'NPS Acadia commercial photography permit required; sunrise reservation needed.',
 'published', 'curated_v1', 4.9, 93),
('Jordan Pond', 'Bar Harbor', 'ME', 44.3231, -68.2530,
 'Glacial pond in Acadia framed by The Bubbles — twin rounded peaks reflected on still mornings, the Jordan Pond House popovers nearby.',
 'public', array['Lake','Mountain','Iconic'], true, 'likely',
 'NPS Acadia commercial photography permit required.',
 'published', 'curated_v1', 4.9, 92),
('Thunder Hole', 'Bar Harbor', 'ME', 44.3211, -68.1880,
 'Coastal inlet where ocean swells boom into a granite cavern — Acadia''s most popular shoreline stop.',
 'public', array['Coastal','Outdoor','Iconic'], true, 'likely',
 'NPS Acadia commercial photography permit required.',
 'published', 'curated_v1', 4.7, 87),

-- ── Portland, ME ──────────────────────────────────────────────────────────
('Portland Head Light', 'Portland', 'ME', 43.6231, -70.2078,
 '1791 lighthouse — oldest in Maine, with the white-shingled keeper''s house, granite cliffs, Casco Bay framing.',
 'public', array['Lighthouse','Coastal','Iconic'], true, 'likely',
 'Cape Elizabeth photo permit required for commercial photography.',
 'published', 'curated_v1', 4.9, 93),
('Old Port', 'Portland', 'ME', 43.6573, -70.2526,
 'Cobblestoned waterfront district — 19th-century brick warehouses, tugboats and lobster docks below, gas lamps lit at dusk.',
 'public', array['Historic','Waterfront','Architecture'], false, 'unknown',
 'Public streets; respect storefronts and docks.',
 'published', 'curated_v1', 4.8, 89),
('Eastern Promenade', 'Portland', 'ME', 43.6700, -70.2444,
 'Bluff-top park overlooking Casco Bay + the Calendar Islands — sweeping Atlantic views, the Atlantic''s easternmost mainland.',
 'public', array['Park','Waterfront','Skyline'], true, 'likely',
 'Portland Parks photo permit applies.',
 'published', 'curated_v1', 4.7, 87),

-- ── Burlington, VT ────────────────────────────────────────────────────────
('Lake Champlain Waterfront', 'Burlington', 'VT', 44.4778, -73.2192,
 'Lake-side promenade and ECHO Center — Adirondacks rising on the western horizon, sailboats, sunsets over the water.',
 'public', array['Lake','Waterfront','Sunset'], true, 'likely',
 'Burlington Parks photo permit applies.',
 'published', 'curated_v1', 4.7, 87),
('Church Street Marketplace', 'Burlington', 'VT', 44.4775, -73.2125,
 'Pedestrianized brick street through downtown — string lights, mature elms, Vermont brick storefronts.',
 'public', array['Urban','Architecture','Pedestrian'], false, 'unknown',
 'Public mall; large crews check with city.',
 'published', 'curated_v1', 4.6, 85),
('Battery Park', 'Burlington', 'VT', 44.4828, -73.2192,
 'Bluff-top park with stairs down to the lake — sunset shots over Champlain, the historic Bandstand at the north end.',
 'public', array['Park','Sunset','Lake'], true, 'likely',
 'Burlington Parks photo permit applies.',
 'published', 'curated_v1', 4.5, 84),

-- ── Stowe, VT ─────────────────────────────────────────────────────────────
('Stowe Community Church', 'Stowe', 'VT', 44.4658, -72.6856,
 '1863 white-steepled Greek Revival church — most-photographed church in Vermont, Mount Mansfield rising directly behind.',
 'public', array['Architecture','Iconic','Mountain'], false, 'unknown',
 'Public street view; church staff for paid interior photography.',
 'published', 'curated_v1', 4.7, 88),
('Smugglers'' Notch', 'Stowe', 'VT', 44.5556, -72.7950,
 'Mountain pass through Mount Mansfield + Sterling Mountain — vertical 1,000-foot cliffs, boulders, cool ferns. Closed in winter.',
 'public', array['Mountain','Outdoor','Forest'], false, 'likely',
 'Mount Mansfield SF photo permit may apply.',
 'published', 'curated_v1', 4.7, 86),
('Trapp Family Lodge Meadows', 'Stowe', 'VT', 44.4825, -72.7186,
 'Sound-of-Music-style alpine meadow estate — log lodge, mountains, hayfields. The classic Vermont landscape.',
 'public', array['Mountain','Architecture','Outdoor'], true, 'likely',
 'Trapp Family Lodge handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),

-- ── Newport, RI ───────────────────────────────────────────────────────────
('Cliff Walk', 'Newport', 'RI', 41.4826, -71.2978,
 '3.5-mile coastal walkway between Gilded Age mansions and Atlantic cliffs — Marble House, The Breakers behind, ocean below.',
 'public', array['Coastal','Iconic','Historic'], true, 'likely',
 'City of Newport photo permit required for commercial photography.',
 'published', 'curated_v1', 4.8, 91),
('The Breakers', 'Newport', 'RI', 41.4700, -71.2978,
 '1895 Vanderbilt summer mansion — 70 rooms, gilt + marble interior, ocean lawn. The grandest Gilded Age estate in America.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Preservation Society of Newport handles commercial photography.',
 'published', 'curated_v1', 4.9, 92),
('Bowen''s Wharf', 'Newport', 'RI', 41.4878, -71.3142,
 'Historic working harbor — sailboats, weathered wood docks, lobster boats, ferry dock to Block Island.',
 'public', array['Waterfront','Historic','Coastal'], false, 'unknown',
 'Public docks; respect working boats.',
 'published', 'curated_v1', 4.7, 87),

-- ── Mackinac Island, MI ───────────────────────────────────────────────────
('Grand Hotel', 'Mackinac Island', 'MI', 45.8483, -84.6192,
 '1887 Victorian summer hotel — 660-foot porch (longest in the world), white-columned facade, formal gardens, Strait views.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Grand Hotel handles commercial photography permissions; admission fee for non-guests.',
 'published', 'curated_v1', 4.8, 89),
('Arch Rock', 'Mackinac Island', 'MI', 45.8525, -84.6058,
 '50-foot natural limestone arch on the bluff — the iconic Mackinac Island shot, Lake Huron framed below.',
 'public', array['Iconic','Coastal','Outdoor'], true, 'likely',
 'Mackinac SP photo permit required for commercial photography.',
 'published', 'curated_v1', 4.7, 87),
('Main Street', 'Mackinac Island', 'MI', 45.8500, -84.6181,
 'Car-free historic main street — horse-drawn carriages, fudge shops, Victorian storefronts, the harbor right there.',
 'public', array['Historic','Street','Iconic'], false, 'unknown',
 'Public street; no cars.',
 'published', 'curated_v1', 4.7, 87),

-- ── Annapolis, MD ─────────────────────────────────────────────────────────
('US Naval Academy — Bancroft Hall', 'Annapolis', 'MD', 38.9839, -76.4831,
 'World''s largest single dormitory — Beaux-Arts architecture, the central rotunda, formal Worden Field next door.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'USNA Public Affairs handles commercial photography requests; gate ID required.',
 'published', 'curated_v1', 4.8, 89),
('City Dock + Ego Alley', 'Annapolis', 'MD', 38.9783, -76.4856,
 'Working harbor at the foot of Main Street — sailboats and yachts, cobblestones, the 1772 William Paca House behind.',
 'public', array['Waterfront','Historic','Urban'], false, 'unknown',
 'Public dock area.',
 'published', 'curated_v1', 4.7, 87),
('Maryland State House', 'Annapolis', 'MD', 38.9789, -76.4906,
 'Oldest US state capitol still in legislative use (1772) — wooden dome, the Old Senate Chamber where Washington resigned.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'State House staff handles commercial photography permissions.',
 'published', 'curated_v1', 4.7, 87),

-- ── Williamsburg, VA ──────────────────────────────────────────────────────
('Colonial Williamsburg — Governor''s Palace', 'Williamsburg', 'VA', 37.2722, -76.7019,
 'Reconstructed 1722 royal governor''s residence — formal ballroom, walled topiary gardens, the green palace lawn.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Colonial Williamsburg Foundation handles commercial photography permits.',
 'published', 'curated_v1', 4.8, 89),
('Duke of Gloucester Street', 'Williamsburg', 'VA', 37.2710, -76.7014,
 'Mile-long preserved colonial main street — restored 18th-century buildings on every block, costumed interpreters, period storefronts.',
 'public', array['Historic','Street','Architecture'], true, 'likely',
 'Colonial Williamsburg permit applies for crews.',
 'published', 'curated_v1', 4.7, 87),
('Wren Building — College of William & Mary', 'Williamsburg', 'VA', 37.2715, -76.7106,
 'Oldest college building still in use in the US (1700) — red brick, wood-shuttered windows, classical lines.',
 'public', array['Historic','Architecture','Campus'], true, 'unknown',
 'W&M handles commercial photography permissions on campus.',
 'published', 'curated_v1', 4.7, 87),

-- ── Charlottesville, VA ───────────────────────────────────────────────────
('Monticello', 'Charlottesville', 'VA', 38.0089, -78.4533,
 'Jefferson''s 1772 hilltop estate — neoclassical white-domed plantation house, terraced vegetable garden, Blue Ridge views.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Monticello charges commercial photography fees — wedding photography popular.',
 'published', 'curated_v1', 4.8, 91),
('UVA Rotunda + The Lawn', 'Charlottesville', 'VA', 38.0356, -78.5034,
 'Jefferson-designed 1826 academic core — domed rotunda, ten pavilions, Lawn rooms, UNESCO World Heritage Site.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'UVA handles commercial photography permissions on Lawn.',
 'published', 'curated_v1', 4.8, 90),
('Carter Mountain Orchard', 'Charlottesville', 'VA', 37.9783, -78.4647,
 '1,800-foot working orchard with sweeping Blue Ridge views — apple-picking in fall, peach blooms in spring.',
 'public', array['Mountain','Outdoor','Overlook'], true, 'likely',
 'Carter Mountain handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),

-- ── St. Augustine, FL ─────────────────────────────────────────────────────
('Castillo de San Marcos', 'St. Augustine', 'FL', 29.8975, -81.3117,
 '1672 Spanish coquina-stone fort — oldest masonry fort in the US, star-shaped bastions, harbor views.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'NPS commercial photography permit required.',
 'published', 'curated_v1', 4.8, 90),
('Flagler College — Ponce de Leon Hall', 'St. Augustine', 'FL', 29.8939, -81.3133,
 'Henry Flagler''s 1888 Spanish Renaissance hotel turned college — Tiffany stained glass, palm courtyard, ornate facade.',
 'public', array['Historic','Architecture','Iconic'], true, 'likely',
 'Flagler College handles commercial photography requests.',
 'published', 'curated_v1', 4.8, 90),
('St. George Street', 'St. Augustine', 'FL', 29.8950, -81.3133,
 'Pedestrianized colonial-Spanish brick street — period storefronts, the Spanish Quarter, gas lamps at night.',
 'public', array['Historic','Street','Iconic'], false, 'unknown',
 'Public street; respect storefronts.',
 'published', 'curated_v1', 4.7, 87),

-- ── Key West, FL ──────────────────────────────────────────────────────────
('Mallory Square Sunset', 'Key West', 'FL', 24.5589, -81.8067,
 'Cuban-tile waterfront plaza — sunset celebration nightly, performers, the Gulf to the horizon, the cruise ships.',
 'public', array['Waterfront','Sunset','Iconic'], false, 'unknown',
 'Public square.',
 'published', 'curated_v1', 4.7, 87),
('Hemingway House', 'Key West', 'FL', 24.5519, -81.8000,
 '1851 Spanish Colonial mansion — Hemingway''s 1930s home, six-toed cats wandering the gardens, the writing studio still preserved.',
 'public', array['Historic','Iconic','Tropical'], true, 'likely',
 'Hemingway Home handles commercial photography requests.',
 'published', 'curated_v1', 4.7, 87),
('Southernmost Point', 'Key West', 'FL', 24.5460, -81.7973,
 'Painted concrete buoy marking 90 miles to Cuba — the iconic snapshot, almost always a line, but unmistakably Key West.',
 'public', array['Iconic','Coastal','Tropical'], false, 'unknown',
 'Public sidewalk.',
 'published', 'curated_v1', 4.5, 83),

-- ── Chattanooga, TN ───────────────────────────────────────────────────────
('Walnut Street Bridge', 'Chattanooga', 'TN', 35.0561, -85.3096,
 '1891 truss bridge — 2,376 feet, longest pedestrian bridge in the world, Tennessee River and downtown skyline framing.',
 'public', array['Bridge','Skyline','Historic'], false, 'likely',
 'Public bridge; large crews check with city.',
 'published', 'curated_v1', 4.8, 89),
('Lookout Mountain — Sunset Rock', 'Chattanooga', 'TN', 35.0089, -85.3447,
 'Sandstone overlook on Lookout Mountain — Tennessee River bend, downtown Chattanooga, seven-state view on clear days.',
 'public', array['Mountain','Overlook','Iconic'], false, 'likely',
 'Public viewpoint; commercial crews check with NPS Lookout Mt unit.',
 'published', 'curated_v1', 4.8, 89),
('Bluff View Art District', 'Chattanooga', 'TN', 35.0561, -85.3050,
 'Cliff-top arts district above the Tennessee River — gallery courtyards, the Hunter Museum''s modern wing, river-bend views.',
 'public', array['Architecture','Urban','Overlook'], false, 'unknown',
 'Public sidewalks; respect galleries.',
 'published', 'curated_v1', 4.6, 85);
